classdef FFTEnsembleProcessor < EnsembleProcessor
%FFTENSEMBLEPROCESSOR Parallel processor for computing FFTs of ensemble 
%   signals.
%
%   Efficiently computes and stores FFTs of temporal signal columns in 
%   ensemble member tables. Uses the ensemble's configured temporal 
%   snapshot  columns and spectral suffix to dynamically handle 
%   input/output naming.
%   Supports parallel processing with configurable worker count.
%
%   Properties:
%     numWorkers - Number of parallel workers (default: 2)
%     ensemble   - EnsembleBroker instance managing file and metadata 
%                  access
%
%   Methods:
%     FFTEnsembleProcessor(numWorkers, ensemble) - Constructor
%     process(computeHandle)                     - Computes FFT on ensemble
%
%   Notes:
%     - The static method compute performs FFT on all temporal snapshot 
%       columns using ensemble broker configuration.
%     - Designed as a lightweight, extensible spectral preprocessing step.
%
%   Example:
%       ensembleStruct = struct('Files', {fileList});
%       testEnsemble = EnsembleBroker(...
%           ensembleObject = ensembleStruct, ...
%           getFilesFunction = @(obj) obj.Files, ...
%           temporalSnapshotColumns = ...
%               {'HorizontalAcceleration','VerticalAcceleration'};);
%       processor = FFTEnsembleProcessor(...
%                 numWorkers = 2, ...
%                 ensemble = testCase.testEnsemble);
%     proc.process();
%
%   See also: EnsembleProcessor, EnsembleBroker, fft

    methods
        
        function obj = FFTEnsembleProcessor(args)
            arguments
                args.numWorkers (1,1) double ...
                    {mustBePositive, mustBeInteger} = 2
                args.ensemble EnsembleBroker = EnsembleBroker.empty
            end
            % explicit forwarding required given named parameters 
            obj = obj@EnsembleProcessor( ...
                numWorkers=args.numWorkers, ...
                ensemble=args.ensemble);
        end

        function params = getProcessParams(obj)
            %getProcessParams Get parameters for ensemble processing.
            %
            %   Returns an empty struct because no parameters are needed 
            %   for computing FFTs in this subclass. 
            %
            %   Output:
            %     params - (struct) Empty parameter structure.
            %
        
            params = struct();
            params.ensemble = obj.ensemble;
        end

        function process(obj,computeHandle)
        %PROCESS Compute FFTs for all ensemble members.
        %
        %   Inputs:
        %     obj           - FFTEnsembleProcessor instance
        %     computeHandle - Optional function handle to process each 
        %                     member.
        %                     Default the static method compute of this 
        %                     class.
        %
        %   This method is typically called internally and not directly by 
        %   users.
        %
        %   See also: FFTEnsembleProcessor.compute


            arguments
                obj
                computeHandle (1,1) ...
                    function_handle = @(memberTable, params) ...
                    FFTEnsembleProcessor.compute(memberTable, params)
            end
            process@EnsembleProcessor(obj, computeHandle);
        end

        
    end
    methods (Static, Access = protected)

        function updatedMember = compute(memberTable, params)
        % compute Perform FFT on ensemble member signal columns.
        %
        %   updatedMember = compute(memberTable, params) computes the FFT 
        %   of each temporal snapshot column in the ensemble provided via 
        %   params. The spectral results are stored in new columns with 
        %   names generated by appending the ensemble's configured spectral 
        %   suffix.
        %
        %   Input Arguments:
        %     memberTable - Table representing one ensemble member.
        %     params      - Struct containing processing parameters, 
        %                   must include:
        %                       .ensemble - EnsembleBroker instance.
        %
        %   Output Arguments:
        %     updatedMember - Member updated with spectral FFT columns.
        %
        %   This method dynamically uses ensemble.temporalSnapshotColumns 
        %   for input columns and ensemble.mapToSpectralColumn() 
        %   for output column names, ensuring consistency with ensemble 
        %   configuration.

            ensemble = params.ensemble;
            temporalCols = ensemble.temporalSnapshotColumns;
            log = SFRFsLogger.getLogger();
            for i = 1:numel(temporalCols)
                colName = temporalCols{i};
                spectralColName = ensemble.mapToSpectralColumn(colName);
                if log.isFineEnabled()
                    log.fine(...
                        sprintf(...
                        "Computing FFT for column %s..." + colName));
                end
                % Concatenate all snapshots
                x = [memberTable.(colName){:}]; 
                X = fft(x, [], 1);
                nSnapshots = size(x, 2);
                memberTable.(spectralColName) = ...
                    mat2cell(X, size(X,1), ones(1,nSnapshots)).';
                if log.isFineEnabled()
                    log.fine( sprintf( ...
                        "FFT for column %s stored in column %s.", ... 
                        colName,spectralColName));
                end
            end
            updatedMember = memberTable;
        end
    end
end
