classdef SFRFsParametersRollingBearings < SFRFsParameters
% SFRFsParametersRollingBearings  Store and validate SFRF parameters for
% bearing fault types.
%
% This value class stores validated Spectral Fault Receptive Field (SFRF)
% parameter sets for:
%   - Outer race (BPFO frequency band)
%   - Inner race (BPFI frequency band)
%   - Ball       (BSF frequency band)
%   - Cage       (FTF frequency band)
%
% Construction uses named (keyword) arguments and supports two modes.
%
% Examples:
% Mode 1 – Individual parameters for each fault type:
%   centerOuter   = GaussianMaskParameters(bandwidth = 5, sigmaRule = 7);
%   surroundOuter = SuperGaussianMaskParameters(alpha = 12, beta = 3);
%
%   paramsOuter = SFRFsParameters.buildSFRFsParameters( ...
%     order            = 2, ...
%     numSidebands     = 0, ...
%     centerMask       = centerOuter, ...
%     surroundMask     = surroundOuter, ...
%     inhibitionFactor = 0.2);
%
%   paramsInner = SFRFsParameters.buildSFRFsParameters( ...
%     order        = 1, ...
%     numHarmonics = 8);
%
%   paramsBall  = SFRFsParameters.buildSFRFsParameters( ...
%     order      = 0, ...
%     centerMask = GaussianMaskParameters(bandwidth = 4, sigmaRule = 6));
%
%   paramsCage  = SFRFsParameters.buildSFRFsParameters( ...
%     numSidebands = 0);
%
%   obj = SFRFsParametersRollingBearings( ...
%     outerRace = paramsOuter, ...
%     innerRace = paramsInner, ...
%     ball      = paramsBall, ...
%     cage      = paramsCage);
%
% Mode 2 – Shared SFRF parameters for all fault types:
%   sharedParams = SFRFsParameters.buildSFRFsParameters( ...
%     order            = 3, ...
%     numSidebands     = 4, ...
%     numHarmonics     = 8, ...
%     centerMask       = GaussianMaskParameters(...
%                           bandwidth = 5, sigmaRule = 7), ...
%     surroundMask     = SuperGaussianMaskParameters(...
%                           alpha = 12, beta = 4), ...
%     inhibitionFactor = 0.6);
%
%   obj = SFRFsParametersRollingBearings( ...
%     SameForAllFaultTypes = sharedParams);
%
% See also: SFRFsParameters
     

    properties
        outerRace   % SFRF params for Outer race faults
        innerRace   % SFRF params for Inner race faults
        ball        % SFRF params for Ball faults
        cage        % SFRF params for Cage faults
    end

    properties (Constant)
        % Fault type names
        OUTER_RACE_FAULT_TYPE_NAME = 'outerRace'
        INNER_RACE_FAULT_TYPE_NAME = 'innerRace'
        BALL_FAULT_TYPE_NAME       = 'ball'
        CAGE_FAULT_TYPE_NAME       = 'cage'
    
        % Collection of all supported fault types
        faultTypes = { ...
            SFRFsParametersRollingBearings.OUTER_RACE_FAULT_TYPE_NAME, ...
            SFRFsParametersRollingBearings.INNER_RACE_FAULT_TYPE_NAME, ...
            SFRFsParametersRollingBearings.BALL_FAULT_TYPE_NAME, ...
            SFRFsParametersRollingBearings.CAGE_FAULT_TYPE_NAME ...
        }
    
    end

    methods
        function obj = SFRFsParametersRollingBearings(args)
            arguments
                args.outerRace struct = struct()
                args.innerRace struct = struct()
                args.ball struct = struct()
                args.cage struct = struct()
                args.SameForAllFaultTypes struct = struct()
            end
            
            isEmptyStr = @SFRFsParametersRollingBearings.isEmptyStruct;
            valInputs = @SFRFsParametersRollingBearings.validateInputs;

            % Validate the input arguments
            valInputs(args);
            
            % Assign properties based on validation
            if ~isEmptyStr(args.SameForAllFaultTypes)
                obj.outerRace = args.SameForAllFaultTypes;
                obj.innerRace = args.SameForAllFaultTypes;
                obj.ball = args.SameForAllFaultTypes;
                obj.cage = args.SameForAllFaultTypes;
                % Set consistent values for sidebands
                % Force Outer & Cage to have 0 sidebands
                obj.outerRace.numSidebands = 0;
                obj.cage.numSidebands      = 0;
            else
                obj.outerRace = args.outerRace;
                obj.innerRace = args.innerRace;
                obj.ball = args.ball;
                obj.cage = args.cage;
                % validate no sidebands for OuterRace and Cage
                SFRFsParametersRollingBearings.validateNoSidebands(...
                obj.outerRace, ...
                SFRFsParametersRollingBearings.OUTER_RACE_FAULT_TYPE_NAME);
                SFRFsParametersRollingBearings.validateNoSidebands(...
                    obj.cage, ...
                    SFRFsParametersRollingBearings.CAGE_FAULT_TYPE_NAME);

            end

            log = SFRFsLogger.getLogger();
            if log.isFineEnabled()
                log.fine(obj.toString())
            end
        end

        function str = toString(obj)
            % toString Return a concise state representation of the object.

            str = sprintf( ...
                ['[SFRFsParametersRollingBearings:', ...
                ' outerRace=%s, innerRace=%s, ball=%s, cage=%s]'], ...
                SFRFsParametersRollingBearings.format(obj.outerRace), ...
                SFRFsParametersRollingBearings.format(obj.innerRace), ...
                SFRFsParametersRollingBearings.format(obj.ball), ...
                SFRFsParametersRollingBearings.format(obj.cage));
        end

        function params = getParamsForFaultType(obj, faultTypeName)
            % getParamsForFaultType Return the parameter struct for a given 
            % fault type.

            arguments
                obj (1,1) SFRFsParametersRollingBearings
                faultTypeName {mustBeTextScalar}
            end

            ft = string(faultTypeName);

            % Validate supported fault types
            if ~any(strcmp(ft, SFRFsParametersRollingBearings.faultTypes))
                error( ...
                    ['sfrfs:SFRFsParametersRollingBearings:' ...
                    'getParamsForFaultType:UnknownFaultType'], ...
                    'Unknown fault type "%s". Supported types: %s.', ...
                    ft, ...
                    strjoin(SFRFsParametersRollingBearings.faultTypes, ...
                    ', '));
            end

            params = obj.(ft);

        end

    end

    methods (Access = private, Static)

        function validateInputs(args)
            isEmptyStr = @SFRFsParametersRollingBearings.isEmptyStruct;
            getMissPar = ...
                @SFRFsParametersRollingBearings.getMissingParameters;

            % Validation when SameForAllFaultTypes is provided:
            if ~isEmptyStr(args.SameForAllFaultTypes)
                if ~isEmptyStr(args.outerRace) || ...
                        ~isEmptyStr(args.innerRace) || ...
                        ~isEmptyStr(args.ball) || ...
                        ~isEmptyStr(args.cage)
                    error(...
                        ['sfrfs:SFRFsParametersRollingBearings:' ...
                        'validateInputs:ConflictingArguments'],...
                        ['Not additional arguments allowed for ' ...
                        'SameForAllFaultTypes option']);
                end
                SFRFsParametersRollingBearings.checkDuplicateParams( ...
                    args.SameForAllFaultTypes, 'SameForAllFaultTypes');
                missingSFRFParams = getMissPar(...
                    'SameForAllFaultTypes', args);
            else
                missingFaults = ...
                    SFRFsParametersRollingBearings.getMissingFaultTypes(...
                    args);
                if ~isempty(missingFaults)
                    error(...
                        ['sfrfs:SFRFsParametersRollingBearings:' ...
                        'validateInputs:MissingArguments'], ...
                        'Missing fault type parameters: %s.', ...
                        strjoin(missingFaults, ', '));
                end
                % validate params of fault types
                fts = SFRFsParametersRollingBearings.faultTypes;
                missingSFRFParams = {};

                for i = 1:numel(fts)
                    ft = fts{i};

                    SFRFsParametersRollingBearings.checkDuplicateParams(...
                        args.(ft), ft);

                    misspars = getMissPar(ft, args);

                    if ~isempty(misspars)
                        missingSFRFParams = ...
                            [missingSFRFParams, misspars]; %#ok<AGROW>
                    end
                end
            end
            
            if ~isempty(missingSFRFParams)
                error(...
                    ['sfrfs:SFRFsParametersRollingBearings:' ...
                    'validateInputs:MissingSFRFsParameters'], ...
                    'Missing or incomplete SFRF parameters: %s.', ...
                    strjoin(missingSFRFParams, '; '));
            end
        end

        function tf = isEmptyStruct(s)
            % Helper to check if a struct is empty (no fields)
            tf = isempty(fieldnames(s));
        end

        function missingParams = getMissingParameters(name, args)
            missingParams = {};
            fname = string(name);
            missingFields = ...
                SFRFsParametersRollingBearings.missingPars(args.(fname));
            if ~isempty(missingFields)
                missingParams{end+1} = sprintf('%s (%s)', ...
                    fname, strjoin(missingFields, '; '));
            end

        end

        function missingFaults = getMissingFaultTypes(args)
            isEmptyStr = @SFRFsParametersRollingBearings.isEmptyStruct;
            fts = SFRFsParametersRollingBearings.faultTypes;
            argsStructs = {...
                args.outerRace, args.innerRace, args.ball, args.cage};
            isMissing = cellfun(isEmptyStr, argsStructs);
            missingFaults = fts(isMissing);
        end

        function missingFields = missingPars(paramStruct)
        
            coreFields = { ...
                SFRFsParameters.ORDER_PARAM_NAME, ...
                SFRFsParameters.NUM_SIDEBANDS_PARAM_NAME, ...
                SFRFsParameters.NUM_HARMONICS_PARAM_NAME, ...
                SFRFsParameters.INHIBITION_FACTOR_PARAM_NAME };
        
            legacyFields = { ...
                SFRFsParameters.SIGMA_CENTER_PARAM_NAME, ...
                SFRFsParameters.SIGMA_SURROUND_PARAM_NAME };
        
            maskFields = { ...
                SFRFsParameters.CENTER_MASK_PARAM_NAME, ...
                SFRFsParameters.SURROUND_MASK_PARAM_NAME };
        
            missingCore   = ...
                coreFields(~isfield(paramStruct, coreFields));
            missingLegacy = ...
                legacyFields(~isfield(paramStruct, legacyFields));
            missingMasks  = ...
                maskFields(~isfield(paramStruct, maskFields));
        
            missingFields = {};
        
            % Always include core if missing
            if ~isempty(missingCore)
                missingFields{end+1} = sprintf( ...
                    'Missing core fields: %s', strjoin(missingCore, ', '));
            end
        
            % 2b interface semantics:
            % - center must be defined via: sigmaCenter OR centerMask
            % - surround must be defined via: sigmaSurround OR surroundMask
        
            hasSigmaCenter = isfield(paramStruct, ...
                SFRFsParameters.SIGMA_CENTER_PARAM_NAME);
            hasCenterMask  = isfield(paramStruct, ...
                SFRFsParameters.CENTER_MASK_PARAM_NAME);
        
            hasSigmaSurround = isfield(paramStruct, ...
                SFRFsParameters.SIGMA_SURROUND_PARAM_NAME);
            hasSurroundMask  = isfield(paramStruct, ...
                SFRFsParameters.SURROUND_MASK_PARAM_NAME);
        
            centerDefined   = hasSigmaCenter   || hasCenterMask;
            surroundDefined = hasSigmaSurround || hasSurroundMask;
        
            if ~(centerDefined && surroundDefined)
                if ~centerDefined
                    % Tailored suggestions using what is actually missing
                    missingFields{end+1} = sprintf( ...
                        ['Center undefined: ' ...
                         'provide %s or %s (missing: %s)'], ...
                        SFRFsParameters.SIGMA_CENTER_PARAM_NAME, ...
                        SFRFsParameters.CENTER_MASK_PARAM_NAME, ...
                        strjoin(intersect( ...
                            {SFRFsParameters.SIGMA_CENTER_PARAM_NAME, ...
                             SFRFsParameters.CENTER_MASK_PARAM_NAME}, ...
                            [missingLegacy, missingMasks], ...
                            'stable'), ', '));
                end
        
                if ~surroundDefined
                    missingFields{end+1} = sprintf( ...
                        ['Surround undefined: ' ...
                         'provide %s or %s (missing: %s)'], ...
                        SFRFsParameters.SIGMA_SURROUND_PARAM_NAME, ...
                        SFRFsParameters.SURROUND_MASK_PARAM_NAME, ...
                        strjoin(intersect( ...
                            {SFRFsParameters.SIGMA_SURROUND_PARAM_NAME, ...
                             SFRFsParameters.SURROUND_MASK_PARAM_NAME}, ...
                            [missingLegacy, missingMasks], ...
                            'stable'), ', '));
                end
            end
        end


        function checkDuplicateParams(paramStruct, label)
        % checkDuplicateParams
        % Reject duplicate parameterization unless it is a consistent, 
        % redundant legacy-to-mask canonization (old sigma parameters
        % are converted to MaskParameters objects and added as additional
        % fileds).
        %
        % Allowed:
        %   - Center: sigmaCenter OR centerMask
        %   - Surround: sigmaSurround OR surroundMask
        %   - Mixed across center/surround is allowed 
        %   - If BOTH are present for center/surround, allowed only when:
        %       * mask is GaussianMaskParameters
        %       * mask params match sigma vector exactly
        
            function tf = isGaussianMask(maskObj)
                tf = isa(maskObj, 'GaussianMaskParameters');
            end
        
            function [bw, sr] = getGaussianParams(maskObj)
                % Try common representations
                if isprop(maskObj, 'bandwidth') && ...
                        isprop(maskObj, 'sigmaRule')
                    bw = maskObj.bandwidth;
                    sr = maskObj.sigmaRule;
                    return
                end
                if isprop(maskObj, 'params') && ... 
                    isstruct(maskObj.params) && ...
                        isfield(maskObj.params, 'bandwidth') && ...
                        isfield(maskObj.params, 'sigmaRule')
                    bw = maskObj.params.bandwidth;
                    sr = maskObj.params.sigmaRule;
                    return
                end
                error(['sfrfs:SFRFsParametersRollingBearings:' ...
                       'validateInputs:GaussianMaskParamsUnavailable'], ...
                      ['Cannot access GaussianMaskParameters' ...
                       'to validate consistency in "%s".'], label);
            end
        
            function tf = matchesSigma(maskObj, sigmaVec)
                % sigmaVec = [bandwidth, sigmaRule]
                [bw, sr] = getGaussianParams(maskObj);
                tf = isequal([bw, sr], sigmaVec);
            end
        
            function dupError(idSuffix, msgFmt, varargin)
                error( ...
                ['sfrfs:SFRFsParametersRollingBearings:validateInputs:' ...
                idSuffix], msgFmt, varargin{:});
            end
        
            % check defined params
            hasSigmaCenter = isfield( ...
                paramStruct, SFRFsParameters.SIGMA_CENTER_PARAM_NAME);
            hasCenterMask = isfield( ...
                paramStruct, SFRFsParameters.CENTER_MASK_PARAM_NAME);
            hasSigmaSurround = isfield( ...
                paramStruct, SFRFsParameters.SIGMA_SURROUND_PARAM_NAME);
            hasSurroundMask  = isfield( ...
                paramStruct, SFRFsParameters.SURROUND_MASK_PARAM_NAME);
        
            % duplicate in definition of center params
            if hasSigmaCenter && hasCenterMask
                maskObj  = ...
                    paramStruct.(SFRFsParameters.CENTER_MASK_PARAM_NAME);
                sigmaVec = ...
                    paramStruct.(SFRFsParameters.SIGMA_CENTER_PARAM_NAME);
        
                % Allow only if mask is Gaussian and matches sigmaCenter
                if ~(isGaussianMask(maskObj) && ...
                        matchesSigma(maskObj, sigmaVec))
                    dupError('DuplicateCenterParameterization', ...
                        ['Inconsistent CENTER parameterization in ' ...
                         '"%s": sigmaCenter and centerMask are both ' ...
                         'provided but do not match.'], ...
                        label);
                end
            end
        
            % duplicate in definition of surround params
            if hasSigmaSurround && hasSurroundMask
                maskObj  = paramStruct.(...
                    SFRFsParameters.SURROUND_MASK_PARAM_NAME);
                sigmaVec = paramStruct.(...
                    SFRFsParameters.SIGMA_SURROUND_PARAM_NAME);
        
                % check if they match
                if ~(isGaussianMask(maskObj) && ...
                        matchesSigma(maskObj, sigmaVec))
                    dupError('DuplicateSurroundParameterization', ...
                        ['Inconsistent SURROUND parameterization ' ...
                         'in "%s": sigmaSurround and surroundMask are ' ...
                         'both provided but do not match.'], ...
                        label);
                end
            end
        end

        function validateNoSidebands(paramStruct, faultTypeName)
            if paramStruct.numSidebands > 0
                error(...
                    ['sfrfs:SFRFsParametersRollingBearings:'...
                    'InvalidNumSidebands'], ...
                    '%s fault type must have NumSidebands = 0.', ...
                    faultTypeName);
            end
        end

        function s = format(p)
            % Extract state-only view of an SFRF parameter struct.

            s = jsonencode(struct( ...
                'order', p.order, ...
                'numSidebands', p.numSidebands, ...
                'numHarmonics', p.numHarmonics, ...
                'centerMask', struct( ...
                'type', class(p.centerMask), ...
                'params', p.centerMask.params), ...
                'surroundMask', struct( ...
                'type', class(p.surroundMask), ...
                'params', p.surroundMask.params), ...
                'inhibitionFactor', p.inhibitionFactor));
        end

    end
end