classdef TestParametersRollingBearings < matlab.unittest.TestCase
    % Test suite for the ParametersRollingBearings class.
    %
    % Covers:
    %   - Valid construction with all required arguments
    %   - Validation errors for invalid or missing values 
    %     (type, sign, range)
    %   - Immutability enforcement after construction

    properties
        validArgs
    end

    methods (TestMethodSetup)
        function createValidArgs(testCase)
            testCase.validArgs = { ...
                'numRollingElements', 8, ...
                'ballDiameter',       7.92, ...
                'pitchDiameter',      34.55, ...
                'contactAngle',       0 };
        end
    end

    methods (Test)
        function testValidConstruction(testCase)
            obj = ParametersRollingBearings(testCase.validArgs{:});
            testCase.verifyEqual(obj.numRollingElements, 8);
            testCase.verifyEqual(obj.ballDiameter, 7.92);
            testCase.verifyEqual(obj.pitchDiameter, 34.55);
            testCase.verifyEqual(obj.contactAngle, 0);
        end

        function testMissingArgumentsError(testCase)
            % Omit BallDiameter
            testCase.verifyError(@() ParametersRollingBearings( ...
                'numRollingElements',8, ...
                'pitchDiameter',34.55, ...
                'contactAngle',0), 'MATLAB:nonExistentField');
        end

        function testInvalidTypeError(testCase)
            % Wrong type for NumRollingElements
            testCase.verifyError(@() ParametersRollingBearings( ...
                'numRollingElements','eight', ...
                'ballDiameter',7.92, ...
                'pitchDiameter',34.55, ...
                'contactAngle',0), ...
                'MATLAB:validation:IncompatibleSize');
        end

        function testInvalidValueError(testCase)
            % Out-of-range ContactAngle
            testCase.verifyError(@() ParametersRollingBearings( ...
                'numRollingElements',8, ...
                'ballDiameter',7.92, ...
                'pitchDiameter',34.55, ...
                'contactAngle',100), ...
                'MATLAB:validators:mustBeLessThanOrEqual');
        end

        function testImmutablePropertyError(testCase)
            % Should not allow property reassignment after construction
            obj = ParametersRollingBearings(testCase.validArgs{:});
            testCase.verifyError(@() setfield(obj, 'ballDiameter', 8.0), ...
                'MATLAB:class:SetProhibited');
        end


        function testNegativeRollingElements(testCase)
            % Negative number of rolling elements (should error)
            testCase.verifyError(@() ParametersRollingBearings( ...
                'numRollingElements', -1, ...
                'ballDiameter', 7.92, ...
                'pitchDiameter', 34.55, ...
                'contactAngle', 0), ...
                'MATLAB:validators:mustBePositive');
        end

        function testZeroBallDiameter(testCase)
            % Zero diameter (should error for mustBePositive)
            testCase.verifyError(@() ParametersRollingBearings( ...
                'numRollingElements', 8, ...
                'ballDiameter', 0, ...
                'pitchDiameter', 34.55, ...
                'contactAngle', 0), ...
                'MATLAB:validators:mustBePositive');
        end

        function testNegativePitchDiameter(testCase)
            % Negative pitch diameter
            testCase.verifyError(@() ParametersRollingBearings( ...
                'numRollingElements', 8, ...
                'ballDiameter', 7.92, ...
                'pitchDiameter', -0.1, ...
                'contactAngle', 0), ...
                'MATLAB:validators:mustBePositive');
        end

        function testNegativeContactAngle(testCase)
            % Negative contact angle (must be >=0)
            testCase.verifyError(@() ParametersRollingBearings( ...
                'numRollingElements',8, ...
                'ballDiameter',7.92, ...
                'pitchDiameter',34.55, ...
                'contactAngle', -1), ...
                'MATLAB:validators:mustBeGreaterThanOrEqual');
        end

        function testContactAngleUpperBoundary(testCase)
            % Contact angle just at upper bound (should succeed)
            obj = ParametersRollingBearings( ...
                'numRollingElements',8, ...
                'ballDiameter',7.92, ...
                'pitchDiameter',34.55, ...
                'contactAngle',90);
            testCase.verifyEqual(obj.contactAngle, 90);
        end

        function testContactAngleLowerBoundary(testCase)
            % Contact angle just at lower bound (should succeed)
            obj = ParametersRollingBearings( ...
                'numRollingElements',8, ...
                'ballDiameter',7.92, ...
                'pitchDiameter',34.55, ...
                'contactAngle',0);
            testCase.verifyEqual(obj.contactAngle, 0);
        end
    end
end
