classdef TestIntegerPowerLaw < matlab.unittest.TestCase
% TestIntegerPowerLaw
%
% Unit tests for:
%   epistemic.tools.evolutionary.operators.mutation.IntegerPowerLaw

    methods (Test)

        function ConstructorStoresParameters(testCase)

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                IntegerPowerLaw( ...
                lo = 0, ...
                hi = 10, ...
                alpha = 1.5);

            testCase.verifyEqual(obj.lo, 0);
            testCase.verifyEqual(obj.hi, 10);
            testCase.verifyEqual(obj.alpha, 1.5);
            testCase.verifyEqual(obj.rMin, 0.5);
        end

        function ConstructorThrowsForNonIntegerLo(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.operators.mutation. ...
                IntegerPowerLaw( ...
                lo = 0.1, ...
                hi = 10, ...
                alpha = 1.5), ...
                "sfrfs:IntegerPowerLaw:BadLo");
        end

        function ConstructorThrowsForNonIntegerHi(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.operators.mutation. ...
                IntegerPowerLaw( ...
                lo = 0, ...
                hi = 10.1, ...
                alpha = 1.5), ...
                "sfrfs:IntegerPowerLaw:BadHi");
        end

        function ConstructorThrowsForNonPositiveAlpha(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.operators.mutation. ...
                IntegerPowerLaw( ...
                lo = 0, ...
                hi = 10, ...
                alpha = 0), ...
                "sfrfs:IntegerPowerLaw:BadAlpha");
        end

        function SampleReturnsSameShapeAsInput(testCase)

            rng(1);

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                IntegerPowerLaw( ...
                lo = 0, ...
                hi = 10, ...
                alpha = 1.5);

            x = [2, 5, 8];
            delta = obj.sample(x);

            testCase.verifySize(delta, size(x));
        end

        function SampleReturnsIntegerValuedIncrements(testCase)

            rng(2);

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                IntegerPowerLaw( ...
                lo = 0, ...
                hi = 10, ...
                alpha = 1.5);

            x = [2, 5, 8];
            xRep = repmat(x, 1, 2000);

            delta = obj.sample(xRep);

            testCase.verifyEqual(delta, round(delta));
        end

        function SampleThrowsForNonIntegerCurrentValues(testCase)

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                IntegerPowerLaw( ...
                lo = 0, ...
                hi = 10, ...
                alpha = 1.5);

            testCase.verifyError(@() obj.sample([1, 2.5]), ...
                "sfrfs:IntegerPowerLaw:BadCurrentValues");
        end

        function SampleThrowsForValuesBelowDomain(testCase)

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                IntegerPowerLaw( ...
                lo = 0, ...
                hi = 10, ...
                alpha = 1.5);

            testCase.verifyError(@() obj.sample(-1), ...
                "sfrfs:IntegerPowerLaw:BadCurrentValues");
        end

        function SampleThrowsForValuesAboveDomain(testCase)

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                IntegerPowerLaw( ...
                lo = 0, ...
                hi = 10, ...
                alpha = 1.5);

            testCase.verifyError(@() obj.sample(11), ...
                "sfrfs:IntegerPowerLaw:BadCurrentValues");
        end

        function SampleKeepsMutatedValuesInsideDomain(testCase)

            rng(3);

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                IntegerPowerLaw( ...
                lo = 0, ...
                hi = 10, ...
                alpha = 1.5);

            x = [1, 5, 9];
            xRep = repmat(x, 1, 2000);

            delta = obj.sample(xRep);
            y = xRep + delta;

            testCase.verifyEqual(y, round(y));
            testCase.verifyGreaterThanOrEqual(y, obj.lo);
            testCase.verifyLessThanOrEqual(y, obj.hi);
        end

        function SampleAtCenterIsSymmetricInMean(testCase)

            rng(4);

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                IntegerPowerLaw( ...
                lo = 0, ...
                hi = 10, ...
                alpha = 1.5);

            x = 5 * ones(1, 50000);
            delta = obj.sample(x);

            testCase.verifyLessThan(abs(mean(delta)), 1.0e-2);
        end

        function SampleNearUpperBoundaryIsBiasedNegative(testCase)

            rng(5);

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                IntegerPowerLaw( ...
                lo = 0, ...
                hi = 10, ...
                alpha = 1.5);

            x = 9 * ones(1, 50000);
            delta = obj.sample(x);

            testCase.verifyLessThan(mean(delta), 0.0);
            testCase.verifyLessThanOrEqual(max(delta), 1);
        end

        function LargerAlphaProducesSmallerTypicalSteps(testCase)

            rng(6);

            objLow = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                IntegerPowerLaw( ...
                lo = 0, ...
                hi = 10, ...
                alpha = 0.7);

            objHigh = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                IntegerPowerLaw( ...
                lo = 0, ...
                hi = 10, ...
                alpha = 1.5);

            x = 5 * ones(1, 50000);

            deltaLow = objLow.sample(x);
            deltaHigh = objHigh.sample(x);

            meanAbsLow = mean(abs(deltaLow));
            meanAbsHigh = mean(abs(deltaHigh));

            testCase.verifyGreaterThan(meanAbsLow, meanAbsHigh);
        end

    end
end