classdef TestIntDecoders < matlab.unittest.TestCase
% TestIntDecoders
%
% Unit tests for IntDecoders.
%
% Contract:
%   - All decoders operate on MetagenomeBlock instances.
%   - Individuals are represented by rows in the source block.
%   - Decoded outputs must preserve that semantics consistently.

    methods (Test)

        function inferRejectsUnknownSourceBlockType(testCase)
            f = @() epistemic.tools.evolutionary.phenotype.decoders. ...
                IntDecoders.infer(sourceBlockType="weird");

            testCase.verifyError( ...
                f, ...
                "sfrfs:IntDecoders:UnsupportedSourceBlockType");
        end

        function inferAcceptsComplexSourceBlockType(testCase)
            decodeFcn = epistemic.tools.evolutionary.phenotype. ...
                decoders.IntDecoders.infer( ...
                sourceBlockType="complex");

            testCase.verifyClass(decodeFcn, "function_handle");
        end

        function fromIntDecodesIntegerBlock(testCase)
            G = [-2 -1 0 1 2; 3 4 5 6 7];

            spec = testCase.makeIntSpec_([1 5], -10, 10);

            lo = min(G(:));
            hi = max(G(:));

            block = epistemic.tools.evolutionary.genomes. ...
                IntegerMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=5, ...
                lo=lo, ...
                hi=hi, ...
                value=G);

            actual = epistemic.tools.evolutionary.phenotype. ...
                decoders.IntDecoders.fromInt(block, spec);

            expected = double(G);

            testCase.verifyEqual(actual, expected);
        end

        function fromIntRejectsBadShape(testCase)
            spec = testCase.makeIntSpec_([1 5], 0, 7);

            block = epistemic.tools.evolutionary.genomes. ...
                IntegerMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=4, ...
                lo=0, ...
                hi=10);

            f = @() epistemic.tools.evolutionary.phenotype. ...
                decoders.IntDecoders.fromInt(block, spec);

            testCase.verifyError(f, "sfrfs:IntDecoders:BadShape");
        end

        function fromBoolDecodesBinaryGroups(testCase)
            spec = testCase.makeIntSpec_([1 2], 3, 6);

            G = logical([ ...
                0 0 1 1; ...
                1 0 0 1]);

            block = epistemic.tools.evolutionary.genomes. ...
                BooleanMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=4, ...
                value=G);

            actual = epistemic.tools.evolutionary.phenotype. ...
                decoders.IntDecoders.fromBool(block, spec);

            % Row 1: 00 | 11 -> 3 | 6
            % Row 2: 10 | 01 -> 5 | 4
            expected = [3 6; 5 4];

            testCase.verifyEqual(actual, expected);
        end

        function fromBoolRecoversLowMidHighRowwise(testCase)
            spec = testCase.makeIntSpec_([1 4], 3, 6);

            G = logical([ ...
                0 0 0 1 1 0 1 1; ...
                1 1 1 0 0 1 0 0]);

            block = epistemic.tools.evolutionary.genomes. ...
                BooleanMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=8, ...
                value=G);

            actual = epistemic.tools.evolutionary.phenotype. ...
                decoders.IntDecoders.fromBool(block, spec);

            % Row 1: 00 | 01 | 10 | 11 -> 3 | 4 | 5 | 6
            % Row 2: 11 | 10 | 01 | 00 -> 6 | 5 | 4 | 3
            expected = [3 4 5 6; 6 5 4 3];

            testCase.verifyEqual(actual, expected);
        end

        function fromBoolRejectsBadShape(testCase)
            spec = testCase.makeIntSpec_([1 3], 0, 7);

            block = epistemic.tools.evolutionary.genomes. ...
                BooleanMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=5, ...
                value=false);

            f = @() epistemic.tools.evolutionary.phenotype. ...
                decoders.IntDecoders.fromBool(block, spec);

            testCase.verifyError(f, "sfrfs:IntDecoders:BadShape");
        end

        function fromRealDecodesCircularly(testCase)
            spec = testCase.makeIntSpec_([1 6], 3, 6);

            G = [-1.6 -1.5 -1.4 0.4 0.5 0.6];

            lo = min(G(:));
            hi = max(G(:));

            block = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals=1, ...
                nAtoms=6, ...
                lo=lo, ...
                hi=hi, ...
                value=G);

            actual = epistemic.tools.evolutionary.phenotype. ...
                decoders.IntDecoders.fromReal(block, spec);

            lo = spec.domain.lo;
            hi = spec.domain.hi;
            L = hi - lo + 1;

            Y = lo + mod(double(G) - lo, L);
            expected = round(Y - 0.5);

            testCase.verifyEqual(actual, expected);
        end

        function fromRealPreservesRowwiseIndividuals(testCase)
            spec = testCase.makeIntSpec_([1 3], 3, 6);

            G = [ ...
                -1.6 -0.4 0.6; ...
                 1.4  2.4 3.4];

            lo = min(G(:));
            hi = max(G(:));

            block = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=3, ...
                lo=lo, ...
                hi=hi, ...
                value=G);

            actual = epistemic.tools.evolutionary.phenotype. ...
                decoders.IntDecoders.fromReal(block, spec);

            lo = spec.domain.lo;
            hi = spec.domain.hi;
            L = hi - lo + 1;

            Y = lo + mod(double(G) - lo, L);
            expected = round(Y - 0.5);

            testCase.verifyEqual(actual, expected);
        end

        function fromRealRejectsBadShape(testCase)
            spec = testCase.makeIntSpec_([1 5], 0, 3);

            block = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=4, ...
                lo=-1, ...
                hi=1);

            f = @() epistemic.tools.evolutionary.phenotype. ...
                decoders.IntDecoders.fromReal(block, spec);

            testCase.verifyError(f, "sfrfs:IntDecoders:BadShape");
        end

        function fromComplexDecodesRadially(testCase)
            spec = testCase.makeIntSpec_([1 6], 3, 6);

            G = [ ...
                0.2 * exp(1i * 0), ...
                0.6 * exp(1i * pi / 3), ...
                1.2 * exp(1i * pi / 2), ...
                1.6 * exp(1i * pi), ...
                2.5 * exp(1i * 3 * pi / 2), ...
                3.6 * exp(1i * pi / 4)];

            block = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=1, ...
                nAtoms=6, ...
                lo=0, ...
                hi=4, ...
                value=G);

            actual = epistemic.tools.evolutionary.phenotype. ...
                decoders.IntDecoders.fromComplex(block, spec);

            lo = spec.domain.lo;
            hi = spec.domain.hi;
            L = hi - lo + 1;

            Y = lo + mod(abs(G) - lo, L);
            expected = round(Y - 0.5);

            testCase.verifyEqual(actual, expected);
        end

        function fromComplexPreservesRowwiseIndividuals(testCase)
            spec = testCase.makeIntSpec_([1 3], 3, 6);

            G = [ ...
                0.2 * exp(1i * 0), ...
                1.2 * exp(1i * pi / 2), ...
                2.6 * exp(1i * pi); ...
                3.6 * exp(1i * pi / 4), ...
                0.6 * exp(1i * pi / 3), ...
                1.6 * exp(1i * 3 * pi / 2)];

            block = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=3, ...
                lo=0, ...
                hi=4, ...
                value=G);

            actual = epistemic.tools.evolutionary.phenotype. ...
                decoders.IntDecoders.fromComplex(block, spec);

            lo = spec.domain.lo;
            hi = spec.domain.hi;
            L = hi - lo + 1;

            Y = lo + mod(abs(G) - lo, L);
            expected = round(Y - 0.5);

            testCase.verifyEqual(actual, expected);
        end

        function fromComplexRejectsBadShape(testCase)
            spec = testCase.makeIntSpec_([1 5], 0, 3);

            block = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=4, ...
                lo=0, ...
                hi=2);

            f = @() epistemic.tools.evolutionary.phenotype. ...
                decoders.IntDecoders.fromComplex(block, spec);

            testCase.verifyError(f, "sfrfs:IntDecoders:BadShape");
        end

    end

    methods (Access = private)

        function spec = makeIntSpec_(~, shape, lo, hi)
            spec = struct();
            spec.shape = shape;
            spec.domain = struct();
            spec.domain.lo = lo;
            spec.domain.hi = hi;
        end

    end

end