classdef TestParametersSnapshot < matlab.unittest.TestCase
    % Unit tests for ParametersSnapshot class

    methods(Test)
        function testCreationAndProperties(testCase)
            % Test construction and property assignments
            obj = ParametersSnapshot( ...
                'samplingFrequency', 25600, ...
                'duration', 1.28, ...
                'stride', 60);
            
            testCase.verifyEqual(obj.samplingFrequency, 25600);
            testCase.verifyEqual(obj.duration, 1.28);
            testCase.verifyEqual(obj.stride, 60);
        end
        
        function testGetTotalSamplesComputation(testCase)
            % Test the total samples calculation and memoization
            obj = ParametersSnapshot( ...
                'samplingFrequency', 1000, ...
                'duration', 2, ...
                'stride', 1);
            
            expectedSamples = 2000; % 1000 * 2
            
            n1 = obj.getTotalSamples();
            testCase.verifyEqual(n1, expectedSamples);
        
            n2 = obj.getTotalSamples();
            testCase.verifyEqual(n2, expectedSamples);
        end
        
        function testNegativeOrZeroValuesThrow(testCase)
            testCase.verifyError(@() ParametersSnapshot( ...
                'samplingFrequency', 0, ...
                'duration', 1, ...
                'stride', 1), ...
                'MATLAB:validators:mustBePositive');
            testCase.verifyError(@() ParametersSnapshot( ...
                'samplingFrequency', 1, ...
                'duration', 0, ...
                'stride', 1), ...
                'MATLAB:validators:mustBePositive');
            testCase.verifyError(@() ParametersSnapshot( ...
                'samplingFrequency', 1, ...
                'duration', 1, ...
                'stride', 0), ...
                'MATLAB:validators:mustBePositive');
            testCase.verifyError(@() ParametersSnapshot( ...
                'samplingFrequency', -1, ...
                'duration', 1, ...
                'stride', 1), ...
                'MATLAB:validators:mustBePositive');
        end

        function testGetFrequencyDomain(testCase)
            % Create an instance of ParametersSnapshot with known values
            params = ParametersSnapshot(...
                'samplingFrequency', 4, ...
                'duration', 2, ...
                'stride', 1);
            
            % Expected frequency vector for FFT with N=8 and Fs=4 Hz
            expectedFreq = (0:7)' * (4/8); % [0; 0.5; 1;...;3.5]
            
            % Call the method
            freqAxis = params.getFrequencyDomain();
        
            % Verify output matches expected
            testCase.verifyEqual(...
                freqAxis, expectedFreq, 'AbsTol', 1e-12, ...
                'Frequency axis does not match expected values.');
        end

        function testGetTimeAxisFromProperties(testCase)
            % Arrange
            sf = 12345;          % Arbitrary sampling rate
            duration = 2.5;      % Arbitrary duration
            stride = 42;         % Arbitrary stride (unused here)
            obj = ParametersSnapshot(...
                'samplingFrequency', sf, ...
                'duration', duration, ...
                'stride', stride);
        
            % Get expected properties directly from the object
            N_expected = obj.getTotalSamples();
            fs = obj.samplingFrequency;
        
            % Act
            t = obj.getTimeAxis();
        
            % Assert
            testCase.verifyEqual(...
                t(1), 0, 'First time value should be zero');
            testCase.verifyEqual(...
                length(t), N_expected, ...
                'Time axis length should match total samples');
            testCase.verifyEqual(...
                t(end), (N_expected-1)/fs, ...
                'Last time should match total duration minus one period');
            testCase.verifyGreaterThanOrEqual(...
                t, 0, 'All time axis values should be non-negative');
        end

    end
end