classdef TestMutators < matlab.unittest.TestCase
% TestMutators
%
% Unit tests for:
%   epistemic.tools.evolutionary.operators.mutation.Mutators

    methods (Test)

        function InferReturnsCallableForBooleanBlock(testCase)

            block = epistemic.tools.evolutionary.genomes. ...
                BooleanMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                value = true);

            cfg = epistemic.tools.evolutionary.EngineConfig( ...
                powerLawAlpha = 1.5, ...
                powerLawRMin = 1.0e-3);

            mutateFcn = epistemic.tools.evolutionary. ...
                operators.mutation.Mutators.infer( ...
                block = block, ...
                config = cfg);

            testCase.verifyClass(mutateFcn, "function_handle");
        end

        function InferReturnsCallableForIntegerBlock(testCase)

            block = epistemic.tools.evolutionary.genomes. ...
                IntegerMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = 0, ...
                hi = 10, ...
                value = [ ...
                    0 1 2 3 4; ...
                    5 6 7 8 9]);

            cfg = epistemic.tools.evolutionary.EngineConfig( ...
                powerLawAlpha = 1.5, ...
                powerLawRMin = 1.0e-3);

            mutateFcn = epistemic.tools.evolutionary. ...
                operators.mutation.Mutators.infer( ...
                block = block, ...
                config = cfg);

            testCase.verifyClass(mutateFcn, "function_handle");
        end

        function InferReturnsCallableForRealBlock(testCase)

            block = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = 0.0, ...
                hi = 1.0, ...
                value = [ ...
                    0.1 0.2 0.3 0.4 0.5; ...
                    0.6 0.7 0.8 0.9 1.0]);

            cfg = epistemic.tools.evolutionary.EngineConfig( ...
                powerLawAlpha = 1.5, ...
                powerLawRMin = 1.0e-3);

            mutateFcn = epistemic.tools.evolutionary. ...
                operators.mutation.Mutators.infer( ...
                block = block, ...
                config = cfg);

            testCase.verifyClass(mutateFcn, "function_handle");
        end

        function InferReturnsCallableForComplexBlock(testCase)

            block = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = 0.5, ...
                hi = 2.0, ...
                value = [ ...
                    exp(1i * 0.1)  1.2 * exp(1i * 0.2) ...
                    1.3 * exp(1i * 0.3)  1.4 * exp(1i * 0.4) ...
                    1.5 * exp(1i * 0.5); ...
                    0.8 * exp(-1i * 0.1)  0.9 * exp(-1i * 0.2) ...
                    1.0 * exp(-1i * 0.3)  1.1 * exp(-1i * 0.4) ...
                    1.2 * exp(-1i * 0.5)]);

            cfg = epistemic.tools.evolutionary.EngineConfig( ...
                powerLawAlpha = 1.5, ...
                powerLawRMin = 1.0e-3);

            mutateFcn = epistemic.tools.evolutionary. ...
                operators.mutation.Mutators.infer( ...
                block = block, ...
                config = cfg);

            testCase.verifyClass(mutateFcn, "function_handle");
        end

        function InferReturnsCallableForPermutationBlock(testCase)

            block = epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                value = [ ...
                    1 2 3 4 5; ...
                    5 4 3 2 1]);

            cfg = epistemic.tools.evolutionary.EngineConfig( ...
                powerLawAlpha = 1.5, ...
                powerLawRMin = 1.0e-3);

            mutateFcn = epistemic.tools.evolutionary. ...
                operators.mutation.Mutators.infer( ...
                block = block, ...
                config = cfg);

            testCase.verifyClass(mutateFcn, "function_handle");
        end

        function InferRejectsUnsupportedBlockType(testCase)

            block = testCase.unsupportedBlock_();

            cfg = epistemic.tools.evolutionary.EngineConfig( ...
                powerLawAlpha = 1.5, ...
                powerLawRMin = 1.0e-3);

            f = @() epistemic.tools.evolutionary. ...
                operators.mutation.Mutators.infer( ...
                block = block, ...
                config = cfg);

            testCase.verifyError(f, ...
                "sfrfs:Mutators:UnsupportedBlockType");
        end

    end

    methods (Access = private)

        function block = unsupportedBlock_(~)
            block = LocalUnsupportedBlockMock( ...
                matrix = zeros(2, 3));
        end

    end

end
