classdef TestComplexMutators < matlab.unittest.TestCase
% TestComplexMutators
%
% Unit tests for:
%   epistemic.tools.evolutionary.operators.mutation.ComplexMutators

    methods (Test)

        function InferReturnsCallableMutationFunction(testCase)

            cfg = epistemic.tools.evolutionary.EngineConfig( ...
                powerLawAlpha = 1.5, ...
                powerLawRMin = 1.0e-3);

            mutateFcn = epistemic.tools.evolutionary. ...
                operators.mutation.ComplexMutators.infer( ...
                config = cfg);

            testCase.verifyClass(mutateFcn, "function_handle");
        end

        function MutateChangesSelectedAtomsOnly(testCase)

            rng(1);

            G0 = [ ...
                0.60 * exp(1i * 0.10), ...
                0.70 * exp(1i * 0.20), ...
                0.80 * exp(1i * 0.30), ...
                0.90 * exp(1i * 0.40), ...
                0.95 * exp(1i * 0.50); ...
                1.00 * exp(-1i * 0.10), ...
                1.10 * exp(-1i * 0.20), ...
                1.20 * exp(-1i * 0.30), ...
                1.30 * exp(-1i * 0.40), ...
                1.40 * exp(-1i * 0.50)];

            block = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = 0.5, ...
                hi = 2.0, ...
                value = G0);

            cfg = epistemic.tools.evolutionary.EngineConfig( ...
                powerLawAlpha = 1.5, ...
                powerLawRMin = 1.0e-3);

            mutateFcn = epistemic.tools.evolutionary. ...
                operators.mutation.ComplexMutators.infer( ...
                config = cfg);

            idx = [2; 4];
            mutateFcn(block, 2, idx);

            G = block.asMatrix();

            testCase.verifyEqual(G(1, :), G0(1, :));
            testCase.verifyEqual(G(2, [1 3 5]), G0(2, [1 3 5]));

            testCase.verifyNotEqual(G(2, 2), G0(2, 2));
            testCase.verifyNotEqual(G(2, 4), G0(2, 4));
        end

        function MutateKeepsSelectedAtomsWithinDeclaredRadialDomain( ...
                testCase)

            rng(2);

            G0 = [ ...
                0.51 * exp(1i * 0.10), ...
                0.70 * exp(1i * 0.20), ...
                1.00 * exp(1i * 0.30), ...
                1.60 * exp(1i * 0.40), ...
                1.99 * exp(1i * 0.50); ...
                0.60 * exp(-1i * 0.10), ...
                0.80 * exp(-1i * 0.20), ...
                1.10 * exp(-1i * 0.30), ...
                1.50 * exp(-1i * 0.40), ...
                1.90 * exp(-1i * 0.50)];

            block = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = 0.5, ...
                hi = 2.0, ...
                value = G0);

            cfg = epistemic.tools.evolutionary.EngineConfig( ...
                powerLawAlpha = 0.7, ...
                powerLawRMin = 1.0e-3);

            mutateFcn = epistemic.tools.evolutionary. ...
                operators.mutation.ComplexMutators.infer( ...
                config = cfg);

            idx = [1; 3; 5];
            mutateFcn(block, 1, idx);

            values = block.getAtoms( ...
                individualIndex = 1, ...
                atomIndices = idx);

            testCase.verifyGreaterThanOrEqual(abs(values), block.lo);
            testCase.verifyLessThanOrEqual(abs(values), block.hi);
        end

        function MutateChangesRadiusOrPhaseForSelectedAtoms(testCase)

            rng(3);

            G0 = [ ...
                0.70 * exp(1i * 0.10), ...
                0.80 * exp(1i * 0.20), ...
                0.90 * exp(1i * 0.30); ...
                1.00 * exp(-1i * 0.10), ...
                1.10 * exp(-1i * 0.20), ...
                1.20 * exp(-1i * 0.30)];

            block = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 3, ...
                lo = 0.5, ...
                hi = 2.0, ...
                value = G0);

            cfg = epistemic.tools.evolutionary.EngineConfig( ...
                powerLawAlpha = 1.5, ...
                powerLawRMin = 1.0e-3);

            mutateFcn = epistemic.tools.evolutionary. ...
                operators.mutation.ComplexMutators.infer( ...
                config = cfg);

            idx = [1; 2; 3];
            mutateFcn(block, 2, idx);

            z0 = G0(2, :);
            z1 = block.getAtoms( ...
                individualIndex = 2, ...
                atomIndices = idx);

            sameRadius = abs(z1) == abs(z0);
            samePhase = angle(z1) == angle(z0);

            testCase.verifyFalse(all(sameRadius & samePhase));
        end

    end

end