classdef TestComplexMetagenomeBlock < matlab.unittest.TestCase
    methods (Test)

        function testValueCreatesGivenComplexMatrix(testCase)
            G0 = [1+1i, 2+0i; 0.5-0.5i, -1i];

            b = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=2, nAtoms=2, ...
                lo=0, hi=2.1, value=G0);

            G = b.asMatrix();

            testCase.verifySize(G, [2, 2]);
            testCase.verifyEqual(G, G0);
        end

        function testRandomGenerationCreatesMatrixInAnnulus(testCase)
            lo = 0.5;
            hi = 2.0;

            b = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=5, nAtoms=6, lo=lo, hi=hi);

            G = b.asMatrix();

            testCase.verifySize(G, [5, 6]);
            testCase.verifyClass(G, "double");
            testCase.verifyGreaterThanOrEqual(abs(G), lo);
            testCase.verifyLessThanOrEqual(abs(G), hi);
        end

        function testZeroRadiusCreatesAllZeros(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=3, nAtoms=4, lo=0, hi=0);

            G = b.asMatrix();

            testCase.verifyEqual(G, zeros(3, 4));
        end

        function testNegativeLoThrowsError(testCase)
            f = @() epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=1, nAtoms=1, lo=-eps, hi=1);

            testCase.verifyError(f, ...
                "sfrfs:ComplexMetagenomeBlock:BadArg");
        end

        function testLoGreaterThanHiThrowsError(testCase)
            f = @() epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=1, nAtoms=1, lo=2, hi=1);

            testCase.verifyError(f, ...
                "sfrfs:ComplexMetagenomeBlock:BadRange");
        end

        function testValueMustBeFiniteComplexMatrix(testCase)
            f1 = @() epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=1, nAtoms=1, value=Inf + 1i);

            testCase.verifyError(f1, ...
                "sfrfs:ComplexMetagenomeBlock:BadArg");

            f2 = @() epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=1, nAtoms=1, value=NaN + 1i);

            testCase.verifyError(f2, ...
                "sfrfs:ComplexMetagenomeBlock:BadArg");
        end

        function testValueMustMatchRequestedSize(testCase)
            G0 = [1+1i, 2+2i];

            f = @() epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=2, nAtoms=2, value=G0);

            testCase.verifyError(f, ...
                "sfrfs:ComplexMetagenomeBlock:BadArg");
        end

        function testValueMustRespectAnnulusBounds(testCase)
            G0 = [0.1, 1.5];

            f = @() epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=1, nAtoms=2, ...
                lo=0.5, hi=1.0, value=G0);

            testCase.verifyError(f, ...
                "sfrfs:ComplexMetagenomeBlock:BadValue");
        end

        function testValueOnAnnulusBoundaryIsAccepted(testCase)
            G0 = [0.5, 1.0 * exp(1i * pi / 3)];

            b = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=1, nAtoms=2, ...
                lo=0.5, hi=1.0, value=G0);

            G = b.asMatrix();

            testCase.verifyEqual(G, G0);
        end

        function testStoresDeclaredDomain(testCase)
            lo = 0.5;
            hi = 2.0;

            b = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=5, nAtoms=6, lo=lo, hi=hi);

            testCase.verifyEqual(b.lo, lo);
            testCase.verifyEqual(b.hi, hi);
        end

        function testStoresDeclaredDomainWhenValueProvided(testCase)
            G0 = [1+1i, 2+0i; 0.5-0.5i, -1i];

            b = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=2, nAtoms=2, ...
                lo=0, hi=2.1, value=G0);

            testCase.verifyEqual(b.asMatrix(), G0);
            testCase.verifyEqual(b.lo, 0);
            testCase.verifyEqual(b.hi, 2.1);
        end

        function testGetAtomsReturnsSelectedRowLocalValues(testCase)
            G0 = [ ...
                0.5, 1.0 * exp(1i * pi / 3), 1.5; ...
                0.75 * exp(-1i * pi / 4), 1.25, 2.0];

            b = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=2, nAtoms=3, ...
                lo=0.5, hi=2.0, value=G0);

            values = b.getAtoms( ...
                individualIndex=2, ...
                atomIndices=[1; 3]);

            testCase.verifyEqual(values, G0(2, [1 3]));
        end

        function testGetAtomsRejectsBadIndividualIndex(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=2, nAtoms=3, ...
                lo=0.5, hi=2.0);

            f = @() b.getAtoms( ...
                individualIndex=0, ...
                atomIndices=[1; 2]);

            testCase.verifyError(f, ...
                "sfrfs:ComplexMetagenomeBlock:BadArg");
        end

        function testGetAtomsRejectsBadAtomIndices(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=2, nAtoms=3, ...
                lo=0.5, hi=2.0);

            f = @() b.getAtoms( ...
                individualIndex=1, ...
                atomIndices=[1; 4]);

            testCase.verifyError(f, ...
                "sfrfs:ComplexMetagenomeBlock:BadArg");
        end

        function testSetAtomsUpdatesSelectedAtomsOnlyWithVector(testCase)
        
            G0 = [ ...
                0.5, 1.0 * exp(1i * pi / 3), 1.5; ...
                0.75 * exp(-1i * pi / 4), 1.25, 2.0];
        
            b = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=2, nAtoms=3, ...
                lo=0.5, hi=2.0, value=G0);
        
            values = [ ...
                0.6 * exp(-1i * pi / 6), ...
                1.8 * exp( 1i * pi / 2)];
        
            b.setAtoms( ...
                individualIndex=1, ...
                atomIndices=[1; 3], ...
                values=values);
        
            G = b.asMatrix();
        
            testCase.verifyEqual(G(1, [1 3]), values);
            testCase.verifyEqual(G(1, 2), G0(1, 2));
            testCase.verifyEqual(G(2, :), G0(2, :));
        end

        function testSetAtomsReplicatesScalarValue(testCase)
            G0 = [ ...
                0.5, 1.0 * exp(1i * pi / 3), 1.5; ...
                0.75 * exp(-1i * pi / 4), 1.25, 2.0];

            b = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=2, nAtoms=3, ...
                lo=0.5, hi=2.0, value=G0);

            z = 1.2 * exp(1i * pi / 5);

            b.setAtoms( ...
                individualIndex=2, ...
                atomIndices=[1; 2], ...
                values=z);

            G = b.asMatrix();

            testCase.verifyEqual(G(2, [1 2]), [z z]);
            testCase.verifyEqual(G(2, 3), G0(2, 3));
            testCase.verifyEqual(G(1, :), G0(1, :));
        end

        function testSetAtomsRejectsBelowDomain(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=2, nAtoms=3, ...
                lo=0.5, hi=2.0);

            f = @() b.setAtoms( ...
                individualIndex=1, ...
                atomIndices=[1; 2], ...
                values=[0.25, 1.0 * exp(1i * pi / 4)]);

            testCase.verifyError(f, ...
                "sfrfs:ComplexMetagenomeBlock:BadValue");
        end

        function testSetAtomsRejectsAboveDomain(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=2, nAtoms=3, ...
                lo=0.5, hi=2.0);

            f = @() b.setAtoms( ...
                individualIndex=1, ...
                atomIndices=[1; 2], ...
                values=[1.0 * exp(1i * pi / 4), 2.5]);

            testCase.verifyError(f, ...
                "sfrfs:ComplexMetagenomeBlock:BadValue");
        end

        function testSetAtomsRejectsLengthMismatch(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=2, nAtoms=3, ...
                lo=0.5, hi=2.0);

            f = @() b.setAtoms( ...
                individualIndex=1, ...
                atomIndices=[1; 2; 3], ...
                values=[1.0 * exp(1i * pi / 4), ...
                        1.2 * exp(-1i * pi / 6)]);

            testCase.verifyError(f, ...
                "sfrfs:ComplexMetagenomeBlock:BadArg");
        end

    end
end