classdef TestRealMutators < matlab.unittest.TestCase
% TestRealMutators
%
% Unit tests for:
%   epistemic.tools.evolutionary.operators.mutation.RealMutators

    methods (Test)

        function InferReturnsCallableMutationFunction(testCase)

            cfg = epistemic.tools.evolutionary.EngineConfig( ...
                powerLawAlpha = 1.5, ...
                powerLawRMin = 1.0e-3);

            mutateFcn = epistemic.tools.evolutionary. ...
                operators.mutation.RealMutators.infer( ...
                config = cfg);

            testCase.verifyClass(mutateFcn, "function_handle");
        end

        function MutateChangesSelectedAtomsOnly(testCase)

            rng(1);

            G0 = [ ...
                0.10  0.20  0.30  0.40  0.50; ...
                0.60  0.70  0.80  0.90  0.95];

            block = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = 0.0, ...
                hi = 1.0, ...
                value = G0);

            cfg = epistemic.tools.evolutionary.EngineConfig( ...
                powerLawAlpha = 1.5, ...
                powerLawRMin = 1.0e-3);

            mutateFcn = epistemic.tools.evolutionary. ...
                operators.mutation.RealMutators.infer( ...
                config = cfg);

            idx = [2; 4];
            mutateFcn(block, 2, idx);

            G = block.asMatrix();

            testCase.verifyEqual(G(1, :), G0(1, :));
            testCase.verifyEqual(G(2, [1 3 5]), G0(2, [1 3 5]));

            testCase.verifyNotEqual(G(2, 2), G0(2, 2));
            testCase.verifyNotEqual(G(2, 4), G0(2, 4));
        end

        function MutateKeepsSelectedAtomsWithinDeclaredDomain(testCase)

            rng(2);

            G0 = [ ...
                0.01  0.20  0.50  0.80  0.99; ...
                0.10  0.30  0.60  0.70  0.90];

            block = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = 0.0, ...
                hi = 1.0, ...
                value = G0);

            cfg = epistemic.tools.evolutionary.EngineConfig( ...
                powerLawAlpha = 0.7, ...
                powerLawRMin = 1.0e-3);

            mutateFcn = epistemic.tools.evolutionary. ...
                operators.mutation.RealMutators.infer( ...
                config = cfg);

            idx = [1; 3; 5];
            mutateFcn(block, 1, idx);

            values = block.getAtoms( ...
                individualIndex = 1, ...
                atomIndices = idx);

            testCase.verifyGreaterThanOrEqual(values, block.lo);
            testCase.verifyLessThanOrEqual(values, block.hi);
        end

    end

end