classdef TestDecoderValidator < matlab.unittest.TestCase
% TestDecoderValidator
%
% Unit tests for:
%   epistemic.tools.evolutionary.internal.DecoderValidator

    properties (Constant, Access = private)
        NIndividuals = 2
    end

    methods (Test)

        function MustHaveAtomCountForShape_PassesForMatchingCount(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            shape = [2 3];
            nAtoms = prod(shape);

            blocks = testCase.makeBlocks_(nAtoms);

            for k = 1:numel(blocks)
                testCase.verifyWarningFree(@() ...
                    epistemic.tools.evolutionary.internal. ...
                    DecoderValidator.mustHaveAtomCountForShape( ...
                    meta, blocks{k}, shape));
            end
        end

        function MustHaveAtomCountForShape_ThrowsForMismatch(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            shape = [2 3];

            block = epistemic.tools.evolutionary.genomes. ...
                BooleanMetagenomeBlock( ...
                nIndividuals=testCase.NIndividuals, ...
                nAtoms=5);

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHaveAtomCountForShape( ...
                meta, block, shape), ...
                "sfrfs:DecoderValidator:BadShape");
        end

        function MustHaveBitsForShape_PassesForValidMultiple(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            shape = [1 3];
            block = epistemic.tools.evolutionary.genomes. ...
                BooleanMetagenomeBlock( ...
                nIndividuals=testCase.NIndividuals, ...
                nAtoms=6, ...
                value=false);

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHaveBitsForShape( ...
                meta, block, shape));
        end

        function MustHaveBitsForShape_ThrowsForNonMultiple(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            shape = [1 3];
            block = epistemic.tools.evolutionary.genomes. ...
                BooleanMetagenomeBlock( ...
                nIndividuals=testCase.NIndividuals, ...
                nAtoms=5, ...
                value=false);

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHaveBitsForShape( ...
                meta, block, shape), ...
                "sfrfs:DecoderValidator:BadShape");
        end

        function MustHaveBitsForShape_ThrowsForZeroBits(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            shape = [2 2];
            block = epistemic.tools.evolutionary.genomes. ...
                BooleanMetagenomeBlock( ...
                nIndividuals=testCase.NIndividuals, ...
                nAtoms=3, ...
                value=false);

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHaveBitsForShape( ...
                meta, block, shape), ...
                "sfrfs:DecoderValidator:BadShape");
        end

        function MustHaveDomainBounds_PassesForValidBounds(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();
            spec.domain = struct();
            spec.domain.lo = 0;
            spec.domain.hi = 3;

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHaveDomainBounds(meta, spec));
        end

        function MustHaveDomainBounds_ThrowsWhenMissingLo(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();
            spec.domain = struct();
            spec.domain.hi = 3;

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHaveDomainBounds(meta, spec), ...
                "sfrfs:DecoderValidator:BadSpec");
        end

        function MustHaveDomainBounds_ThrowsWhenMissingHi(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();
            spec.domain = struct();
            spec.domain.lo = 0;

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHaveDomainBounds(meta, spec), ...
                "sfrfs:DecoderValidator:BadSpec");
        end

        function MustHaveDomainBounds_ThrowsWhenLoGreaterThanHi(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();
            spec.domain = struct();
            spec.domain.lo = 4;
            spec.domain.hi = 3;

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHaveDomainBounds(meta, spec), ...
                "sfrfs:DecoderValidator:BadRange");
        end

        function MustHaveNondegenerateDomainBounds_ThrowsWhenEqual( ...
                testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();
            spec.domain = struct();
            spec.domain.lo = 3;
            spec.domain.hi = 3;

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHaveNondegenerateDomainBounds( ...
                meta, spec), ...
                "sfrfs:DecoderValidator:DegenerateDomain");
        end

        function MustHaveDomainValues_ThrowsWhenMissing(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHaveDomainValues(meta, spec), ...
                "sfrfs:DecoderValidator:EmptyDomain");
        end

        function MustHaveDomainValues_ThrowsWhenEmpty(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();
            spec.domain = struct();
            spec.domain.values = [];

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHaveDomainValues(meta, spec), ...
                "sfrfs:DecoderValidator:EmptyDomain");
        end

        function MustHaveDomainValues_PassesWhenPresent(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();
            spec.domain = struct();
            spec.domain.values = [1 2 3];

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHaveDomainValues(meta, spec));
        end

        function MustHaveAtLeastDomainValues_ThrowsWhenTooSmall(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();
            spec.domain = struct();
            spec.domain.values = [1 2];

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHaveAtLeastDomainValues( ...
                meta, spec, 3), ...
                "sfrfs:DecoderValidator:DomainTooSmall");
        end

        function MustHaveAtLeastDomainValues_PassesWhenLargeEnough(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();
            spec.domain = struct();
            spec.domain.values = [10 20 30];

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHaveAtLeastDomainValues( ...
                meta, spec, 3));
        end

        function MustHavePermutationDomainSize_Passes(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();
            spec.domain = struct();
            spec.domain.n = 4;

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHavePermutationDomainSize( ...
                meta, spec));
        end

        function MustHavePermutationDomainSize_ThrowsWhenMissingDomain( ...
                testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHavePermutationDomainSize( ...
                meta, spec), ...
                "sfrfs:DecoderValidator:BadSpec");
        end

        function MustHavePermutationDomainSize_ThrowsWhenMissingN(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();
            spec.domain = struct();

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHavePermutationDomainSize( ...
                meta, spec), ...
                "sfrfs:DecoderValidator:BadSpec");
        end

        function MustHavePermutationDomainSize_ThrowsWhenBadN(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec1 = struct();
            spec1.domain = struct();
            spec1.domain.n = 0;

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHavePermutationDomainSize( ...
                meta, spec1), ...
                "sfrfs:DecoderValidator:BadSpec");

            spec2 = struct();
            spec2.domain = struct();
            spec2.domain.n = 2.5;

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustHavePermutationDomainSize( ...
                meta, spec2), ...
                "sfrfs:DecoderValidator:BadSpec");
        end

        function MustHavePermutationShapeConsistentWithDomain_Passes( ...
                testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();
            spec.shape = [1 4];
            spec.domain = struct();
            spec.domain.n = 4;

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator. ...
                mustHavePermutationShapeConsistentWithDomain( ...
                meta, spec));
        end

        function MustHavePermutationShapeConsistentWithDomain_Throws( ...
                testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();
            spec.shape = [1 3];
            spec.domain = struct();
            spec.domain.n = 4;

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator. ...
                mustHavePermutationShapeConsistentWithDomain( ...
                meta, spec), ...
                "sfrfs:DecoderValidator:BadShape");
        end

        function MustHavePermutationBlockConsistentWithDomain_Passes( ...
                testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();
            spec.shape = [1 4];
            spec.domain = struct();
            spec.domain.n = 4;

            block = epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals=testCase.NIndividuals, ...
                nAtoms=4);

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator. ...
                mustHavePermutationBlockConsistentWithDomain( ...
                meta, block, spec));
        end

        function MustHavePermutationBlockConsistentWithDomain_Throws( ...
                testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            spec = struct();
            spec.shape = [1 4];
            spec.domain = struct();
            spec.domain.n = 4;

            block = epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals=testCase.NIndividuals, ...
                nAtoms=3);

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator. ...
                mustHavePermutationBlockConsistentWithDomain( ...
                meta, block, spec), ...
                "sfrfs:DecoderValidator:BadShape");
        end

        function MustBeCanonicalPermutationMatrix_Passes(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            G = [1 2 3; 3 1 2];

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustBeCanonicalPermutationMatrix( ...
                G, 2, 3, meta, "BadValue", "value"));
        end

        function MustBeCanonicalPermutationMatrix_ThrowsForSizeMismatch( ...
                testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            G = [1 2; 2 1];

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustBeCanonicalPermutationMatrix( ...
                G, 2, 3, meta, "BadValue", "value"), ...
                "sfrfs:DecoderValidator:BadValue");
        end

        function MustBeCanonicalPermutationMatrix_ThrowsForDuplicates( ...
                testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            G = [1 1 2; 1 2 3];

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustBeCanonicalPermutationMatrix( ...
                G, 2, 3, meta, "BadValue", "value"), ...
                "sfrfs:DecoderValidator:BadValue");
        end

        function MustBeCanonicalPermutationMatrix_ThrowsForBadSupport( ...
                testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            G = [2 3 4; 1 2 3];

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustBeCanonicalPermutationMatrix( ...
                G, 2, 3, meta, "BadValue", "value"), ...
                "sfrfs:DecoderValidator:BadValue");
        end

        function MustBePositiveIntegerScalar_Passes(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustBePositiveIntegerScalar( ...
                meta, 3, "BadArg", "n"));
        end

        function MustBePositiveIntegerScalar_Throws(testCase)
            meta = ?epistemic.tools.evolutionary.internal.DecoderValidator;

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustBePositiveIntegerScalar( ...
                meta, 0, "BadArg", "n"), ...
                "sfrfs:DecoderValidator:BadArg");

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                DecoderValidator.mustBePositiveIntegerScalar( ...
                meta, 2.5, "BadArg", "n"), ...
                "sfrfs:DecoderValidator:BadArg");
        end

    end

    methods (Access = private)

        function blocks = makeBlocks_(testCase, nAtoms)
            nInd = testCase.NIndividuals;

            blocks = { ...
                epistemic.tools.evolutionary.genomes. ...
                BooleanMetagenomeBlock( ...
                    nIndividuals=nInd, ...
                    nAtoms=nAtoms), ...
                epistemic.tools.evolutionary.genomes. ...
                IntegerMetagenomeBlock( ...
                    nIndividuals=nInd, ...
                    nAtoms=nAtoms, ...
                    lo=1, ...
                    hi=7), ...
                epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                    nIndividuals=nInd, ...
                    nAtoms=nAtoms, ...
                    lo=0, ...
                    hi=1), ...
                epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                    nIndividuals=nInd, ...
                    nAtoms=nAtoms, ...
                    lo=0, ...
                    hi=1), ...
                epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                    nIndividuals=nInd, ...
                    nAtoms=nAtoms) ...
                };
        end

    end

end