classdef TestPowerLaw < matlab.unittest.TestCase
% TestPowerLaw
%
% Unit tests for:
%   epistemic.tools.evolutionary.operators.mutation.PowerLaw

    methods (Test)

        function ConstructorStoresParameters(testCase)

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                PowerLaw( ...
                lo = 0.0, ...
                hi = 1.0, ...
                alpha = 1.5, ...
                rMin = 1.0e-2);

            testCase.verifyEqual(obj.lo, 0.0);
            testCase.verifyEqual(obj.hi, 1.0);
            testCase.verifyEqual(obj.alpha, 1.5);
            testCase.verifyEqual(obj.rMin, 1.0e-2);
        end

        function ConstructorUsesDefaultRMin(testCase)

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                PowerLaw( ...
                lo = 0.0, ...
                hi = 1.0, ...
                alpha = 1.5);

            testCase.verifyEqual(obj.rMin, 1.0e-10);
        end

        function ConstructorThrowsForNonPositiveAlpha(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.operators.mutation. ...
                PowerLaw( ...
                lo = 0.0, ...
                hi = 1.0, ...
                alpha = 0.0, ...
                rMin = 1.0e-2), ...
                "sfrfs:PowerLaw:BadAlpha");
        end

        function ConstructorThrowsForNegativeAlpha(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.operators.mutation. ...
                PowerLaw( ...
                lo = 0.0, ...
                hi = 1.0, ...
                alpha = -0.5, ...
                rMin = 1.0e-2), ...
                "sfrfs:PowerLaw:BadAlpha");
        end

        function ConstructorThrowsForNonPositiveRMin(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.operators.mutation. ...
                PowerLaw( ...
                lo = 0.0, ...
                hi = 1.0, ...
                alpha = 1.5, ...
                rMin = 0.0), ...
                "sfrfs:PowerLaw:BadRMin");
        end

        function ConstructorThrowsForTooLargeRMin(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.operators.mutation. ...
                PowerLaw( ...
                lo = 0.0, ...
                hi = 1.0, ...
                alpha = 1.5, ...
                rMin = 0.6), ...
                "sfrfs:PowerLaw:BadRMin");
        end

        function SampleReturnsSameShapeAsInput(testCase)

            rng(1);

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                PowerLaw( ...
                lo = 0.0, ...
                hi = 1.0, ...
                alpha = 1.5, ...
                rMin = 1.0e-2);

            x = [0.2, 0.5, 0.8];
            delta = obj.sample(x);

            testCase.verifySize(delta, size(x));
        end

        function SampleThrowsForValuesBelowDomain(testCase)

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                PowerLaw( ...
                lo = 0.0, ...
                hi = 1.0, ...
                alpha = 1.5, ...
                rMin = 1.0e-2);

            testCase.verifyError(@() obj.sample(-0.1), ...
                "sfrfs:PowerLaw:BadCurrentValues");
        end

        function SampleThrowsForValuesAboveDomain(testCase)

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                PowerLaw( ...
                lo = 0.0, ...
                hi = 1.0, ...
                alpha = 1.5, ...
                rMin = 1.0e-2);

            testCase.verifyError(@() obj.sample(1.1), ...
                "sfrfs:PowerLaw:BadCurrentValues");
        end

        function SampleKeepsMutatedValuesInsideDomain(testCase)

            rng(2);

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                PowerLaw( ...
                lo = 0.0, ...
                hi = 1.0, ...
                alpha = 1.5, ...
                rMin = 1.0e-2);

            x = [0.1, 0.5, 0.9];
            xRep = repmat(x, 1, 2000);

            delta = obj.sample(xRep);
            y = xRep + delta;

            testCase.verifyGreaterThanOrEqual(y, obj.lo);
            testCase.verifyLessThanOrEqual(y, obj.hi);
        end

        function SampleAtCenterIsSymmetricInMean(testCase)

            rng(3);

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                PowerLaw( ...
                lo = 0.0, ...
                hi = 1.0, ...
                alpha = 1.5, ...
                rMin = 1.0e-2);

            x = 0.5 * ones(1, 50000);
            delta = obj.sample(x);

            testCase.verifyLessThan(abs(mean(delta)), 1.0e-2);
        end

        function SampleNearUpperBoundaryIsNonPositiveBeyondTolerance( ...
                testCase)

            rng(4);

            obj = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                PowerLaw( ...
                lo = 0.0, ...
                hi = 1.0, ...
                alpha = 1.5, ...
                rMin = 1.0e-2);

            x = 0.99 * ones(1, 50000);
            delta = obj.sample(x);

            tol = 1.0e-12;
            testCase.verifyLessThanOrEqual(max(delta), 0.01 + tol);
            testCase.verifyGreaterThan(mean(delta), -0.2);
            testCase.verifyLessThan(mean(delta), 0.0);
        end

        function LargerAlphaProducesSmallerTypicalSteps(testCase)

            rng(5);

            objLow = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                PowerLaw( ...
                lo = 0.0, ...
                hi = 1.0, ...
                alpha = 0.7, ...
                rMin = 1.0e-2);

            objHigh = ...
                epistemic.tools.evolutionary.operators.mutation. ...
                PowerLaw( ...
                lo = 0.0, ...
                hi = 1.0, ...
                alpha = 1.5, ...
                rMin = 1.0e-2);

            x = 0.5 * ones(1, 50000);

            deltaLow = objLow.sample(x);
            deltaHigh = objHigh.sample(x);

            meanAbsLow = mean(abs(deltaLow));
            meanAbsHigh = mean(abs(deltaHigh));

            testCase.verifyGreaterThan(meanAbsLow, meanAbsHigh);
        end

    end
end