classdef TestRealMetagenomeBlock < matlab.unittest.TestCase

    methods (Test)

        function testMatrixSizeAndFinite(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 4, nAtoms = 9, lo = -1.5, hi = 2.25);

            G = b.asMatrix();

            testCase.verifySize(G, [4, 9]);
            testCase.verifyTrue(isnumeric(G));
            testCase.verifyTrue(all(isfinite(G(:))));
            testCase.verifyGreaterThanOrEqual(min(G(:)), -1.5);
            testCase.verifyLessThanOrEqual(max(G(:)), 2.25);
        end

        function testBadRangeErrors(testCase)
            f = @() epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 1, nAtoms = 1, lo = 2, hi = 1);

            testCase.verifyError(f, "sfrfs:RealMetagenomeBlock:BadRange");
        end

        function testValueOverridesGeneration(testCase)
            G0 = [-1.2 0.0 3.4; 5.6 -7.8 9.0];

            b = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, nAtoms = 3, ...
                lo = -999, hi = 999, ...
                value = G0);

            G = b.asMatrix();

            testCase.verifyEqual(G, G0);
        end

        function testValueRejectsNonFinite(testCase)
            f = @() epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 1, nAtoms = 2, value = [1 NaN]);

            testCase.verifyError(f, "sfrfs:RealMetagenomeBlock:BadArg");
        end

        function testValueRejectsComplex(testCase)
            f = @() epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 1, nAtoms = 2, value = [1 + 1i, 2]);

            testCase.verifyError(f, "sfrfs:RealMetagenomeBlock:BadArg");
        end

        function testValueRejectsSizeMismatch(testCase)
            f = @() epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, nAtoms = 3, value = zeros(2, 2));

            testCase.verifyError(f, "sfrfs:RealMetagenomeBlock:BadArg");
        end

        function testValueRejectsBelowDeclaredDomain(testCase)
            f = @() epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, nAtoms = 2, ...
                lo = -1.0, hi = 1.0, ...
                value = [-1.1 0.0; 0.2 0.3]);

            testCase.verifyError(f, "sfrfs:RealMetagenomeBlock:BadArg");
        end

        function testValueRejectsAboveDeclaredDomain(testCase)
            f = @() epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, nAtoms = 2, ...
                lo = -1.0, hi = 1.0, ...
                value = [0.0 0.1; 0.2 1.1]);

            testCase.verifyError(f, "sfrfs:RealMetagenomeBlock:BadArg");
        end

        function testStoresDeclaredDomain(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 4, nAtoms = 9, lo = -1.5, hi = 2.25);

            testCase.verifyEqual(b.lo, -1.5);
            testCase.verifyEqual(b.hi, 2.25);
        end

        function testStoresDeclaredDomainWhenValueProvided(testCase)
            G0 = [-1.2 0.0 3.4; 5.6 -7.8 9.0];

            b = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, nAtoms = 3, ...
                lo = -999, hi = 999, ...
                value = G0);

            testCase.verifyEqual(b.asMatrix(), G0);
            testCase.verifyEqual(b.lo, -999);
            testCase.verifyEqual(b.hi, 999);
        end

        function testGetAtomsReturnsSelectedValues(testCase)
            G0 = [ ...
                -1.0  -0.5   0.0   0.5   1.0; ...
                 0.1   0.2   0.3   0.4   0.5];

            b = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = -1.0, ...
                hi = 1.0, ...
                value = G0);

            values = b.getAtoms( ...
                individualIndex = 1, ...
                atomIndices = [2; 4; 5]);

            testCase.verifyEqual(values, [-0.5 0.5 1.0]);
        end

        function testGetAtomsRejectsBadIndividualIndex(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = -1.0, ...
                hi = 1.0, ...
                value = zeros(2, 5));

            f = @() b.getAtoms( ...
                individualIndex = 0, ...
                atomIndices = [1; 2]);

            testCase.verifyError(f, "sfrfs:RealMetagenomeBlock:BadArg");
        end

        function testGetAtomsRejectsBadAtomIndices(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = -1.0, ...
                hi = 1.0, ...
                value = zeros(2, 5));

            f = @() b.getAtoms( ...
                individualIndex = 1, ...
                atomIndices = [1; 6]);

            testCase.verifyError(f, "sfrfs:RealMetagenomeBlock:BadArg");
        end

        function testSetAtomsScalarBroadcast(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = -1.0, ...
                hi = 1.0, ...
                value = zeros(2, 5));

            b.setAtoms( ...
                individualIndex = 2, ...
                atomIndices = [2; 4], ...
                values = 0.25);

            G = b.asMatrix();
            Gexp = zeros(2, 5);
            Gexp(2, [2 4]) = 0.25;

            testCase.verifyEqual(G, Gexp);
        end

        function testSetAtomsVectorAssignment(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = -1.0, ...
                hi = 1.0, ...
                value = zeros(2, 5));

            b.setAtoms( ...
                individualIndex = 1, ...
                atomIndices = [1; 3; 5], ...
                values = [-0.5 0.0 0.75]);

            G = b.asMatrix();
            Gexp = zeros(2, 5);
            Gexp(1, [1 3 5]) = [-0.5 0.0 0.75];

            testCase.verifyEqual(G, Gexp);
        end

        function testSetAtomsRejectsLengthMismatch(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = -1.0, ...
                hi = 1.0, ...
                value = zeros(2, 5));

            f = @() b.setAtoms( ...
                individualIndex = 1, ...
                atomIndices = [1; 3; 5], ...
                values = [0.1 0.2]);

            testCase.verifyError(f, "sfrfs:RealMetagenomeBlock:BadArg");
        end

        function testSetAtomsRejectsBelowDomain(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = -1.0, ...
                hi = 1.0, ...
                value = zeros(2, 5));

            f = @() b.setAtoms( ...
                individualIndex = 1, ...
                atomIndices = [2; 4], ...
                values = [-1.1 0.0]);

            testCase.verifyError(f, "sfrfs:RealMetagenomeBlock:BadArg");
        end

        function testSetAtomsRejectsAboveDomain(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = -1.0, ...
                hi = 1.0, ...
                value = zeros(2, 5));

            f = @() b.setAtoms( ...
                individualIndex = 1, ...
                atomIndices = [2; 4], ...
                values = [0.0 1.1]);

            testCase.verifyError(f, "sfrfs:RealMetagenomeBlock:BadArg");
        end

        function testSetAtomsRejectsBadIndividualIndex(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = -1.0, ...
                hi = 1.0, ...
                value = zeros(2, 5));

            f = @() b.setAtoms( ...
                individualIndex = 3, ...
                atomIndices = [2; 4], ...
                values = [0.0 0.5]);

            testCase.verifyError(f, "sfrfs:RealMetagenomeBlock:BadArg");
        end

        function testSetAtomsRejectsBadAtomIndices(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                lo = -1.0, ...
                hi = 1.0, ...
                value = zeros(2, 5));

            f = @() b.setAtoms( ...
                individualIndex = 1, ...
                atomIndices = [2; 6], ...
                values = [0.0 0.5]);

            testCase.verifyError(f, "sfrfs:RealMetagenomeBlock:BadArg");
        end

    end

end