classdef TestErrors < matlab.unittest.TestCase
% TestErrors
% Unit tests for helpers.Errors.

    methods (Test)
        function testMessageSetsIdAndMessage(testCase)
            try
                helpers.Errors.raise( ...
                    classMeta=?helpers.Errors, ...
                    suffix="BadSpec", ...
                    message="Spec is missing field 'name'.");
                testCase.verifyFail("Expected an error.");
            catch ME
                testCase.verifyEqual( ...
                    string(ME.identifier), ...
                    "sfrfs:Errors:BadSpec");

                testCase.verifyEqual( ...
                    string(ME.message), ...
                    "Spec is missing field 'name'.");
            end
        end

        function testFormatAndArgsSetsIdAndMessage(testCase)
            try
                helpers.Errors.raise( ...
                    classMeta=?helpers.Errors, ...
                    suffix="ErrorNow", ...
                    format="Value is %d.", ...
                    args={1});
                testCase.verifyFail("Expected an error.");
            catch ME
                testCase.verifyEqual( ...
                    string(ME.identifier), ...
                    "sfrfs:Errors:ErrorNow");

                testCase.verifyEqual( ...
                    string(ME.message), ...
                    "Value is 1.");
            end
        end

        function testMetaclassTaggingUsesRuntimeClass(testCase)
            x = table();

            try
                helpers.Errors.raise( ...
                    classMeta=metaclass(x), ...
                    suffix="ErrorNow", ...
                    message="Hello.");
                testCase.verifyFail("Expected an error.");
            catch ME
                testCase.verifyEqual( ...
                    string(ME.identifier), ...
                    "sfrfs:table:ErrorNow");

                testCase.verifyEqual( ...
                    string(ME.message), ...
                    "Hello.");
            end
        end

        function testCustomPrefix(testCase)
            try
                helpers.Errors.raise( ...
                    classMeta=?helpers.Errors, ...
                    suffix="X", ...
                    message="Hi.", ...
                    prefix="unit");
                testCase.verifyFail("Expected an error.");
            catch ME
                testCase.verifyEqual( ...
                    string(ME.identifier), ...
                    "unit:Errors:X");
            end
        end

        function testBadArgsNeitherMessageNorFormat(testCase)
            try
                helpers.Errors.raise( ...
                    classMeta=?helpers.Errors, ...
                    suffix="X");
                testCase.verifyFail("Expected an error.");
            catch ME
                testCase.verifyEqual( ...
                    string(ME.identifier), ...
                    "sfrfs:Errors:BadArgs");
            end
        end

        function testBadArgsMessageAndFormat(testCase)
            try
                helpers.Errors.raise( ...
                    classMeta=?helpers.Errors, ...
                    suffix="X", ...
                    message="Hi.", ...
                    format="x=%d", ...
                    args={1});
                testCase.verifyFail("Expected an error.");
            catch ME
                testCase.verifyEqual( ...
                    string(ME.identifier), ...
                    "sfrfs:Errors:BadArgs");
            end
        end
    end
end
