classdef TestSFRFsEnsembleProcessor < matlab .unittest.TestCase
    properties
        snapshotParams ParametersSnapshot
        operatingConditions OperatingConditions
        bearingParams ParametersRollingBearings
        sfrfsParams SFRFsParametersRollingBearings
        sfrfsProcessorNoFFT SFRFsEnsembleProcessor
        sfrfsProcessorFFT SFRFsEnsembleProcessor
        bearingFrequencyBands BearingFrequencyBands
        temporalSnapshotColumns cell
        brokerNoFFT EnsembleBroker
        brokerFFT EnsembleBroker
        ensembleMockNoFFT EnsembleMock
        ensembleMockFFT EnsembleMock
        speeds double
        loads double
    end
    
    methods (TestMethodSetup)
        function prepareData(testCase)
            % Setup standard parameters
            testCase.snapshotParams = ParametersSnapshot( ...
                'samplingFrequency', 25600, ...
                'duration', 1.28, ...
                'stride', 60);
            
            testCase.speeds = [35; 37.5; 40];
            testCase.loads  = [12; 11; 10];
            testCase.operatingConditions = OperatingConditions( ...
                testCase.speeds, testCase.loads);
            
            testCase.bearingParams = ParametersRollingBearings( ...
                'numRollingElements', 8, ...
                'ballDiameter', 7.92, ...
                'pitchDiameter', 34.55, ...
                'contactAngle', 0);
            
            sharedParams = ...
                SFRFsParameters.createSFRFsParameters( ...
                    'order', 3, ...
                    'numSidebands', 4, ...
                    'numHarmonics', 8, ...
                    'sigmaCenter', [5, 7], ...
                    'sigmaSurround', [12, 3], ...
                    'inhibitionFactor', 0.6);

            testCase.sfrfsParams = SFRFsParametersRollingBearings( ...
                'SameForAllFaultTypes', sharedParams);
            
            testCase.bearingFrequencyBands = BearingFrequencyBands( ...
                'bearingParams', testCase.bearingParams, ...
                'sfrfsParams', testCase.sfrfsParams, ...
                'operatingConditions', testCase.operatingConditions);

            % Ensembles missing spectra
            % Initialize and prepare EnsembleMockNoFFT
            testCase.ensembleMockNoFFT = EnsembleMock( ...
                'numMembers', 3, ...
                'nSamples', testCase.snapshotParams.getTotalSamples(), ...
                'speeds', testCase.speeds, ...
                'loads', testCase.loads);
            testCase.ensembleMockNoFFT.prepare();

            % Use EnsembleMockNoFFT's column names
            testCase.temporalSnapshotColumns = ...
                testCase.ensembleMockNoFFT.temporalSnapshotColumns;

            % Broker with no spectra
            testCase.brokerNoFFT = SFRFsEnsembleBroker( ...
                'ensembleObject', ...
                testCase.ensembleMockNoFFT.fileEnsembleDS, ...
                'getFilesFunction', @(obj) obj.Files, ...
                'temporalSnapshotColumns', ...
                    testCase.temporalSnapshotColumns);
            
            % Create SFRFs processor case no spectra
            testCase.sfrfsProcessorNoFFT = SFRFsEnsembleProcessor( ...
                'numWorkers', testCase.ensembleMockNoFFT.numMembers, ...
                'ensemble', testCase.brokerNoFFT, ...
                'frequencyBands', testCase.bearingFrequencyBands, ...
                'snapshotParameters', testCase.snapshotParams);
            
            % Ensembles with spectra
            % Initialize and prepare EnsembleMock with FFT precomputed
            testCase.ensembleMockFFT = EnsembleMock( ...
                'numMembers', 15, ...
                'nSamples', testCase.snapshotParams.getTotalSamples(), ...
                'speeds', testCase.speeds, ...
                'loads', testCase.loads);
            testCase.ensembleMockFFT.prepare();
    
            % broker with spectra
            testCase.brokerFFT = SFRFsEnsembleBroker( ...
                'ensembleObject', ...
                testCase.ensembleMockFFT.fileEnsembleDS, ...
                'getFilesFunction', @(obj) obj.Files, ...
                'temporalSnapshotColumns', ...
                    testCase.temporalSnapshotColumns);

            % Compute spectra 
            fftProcessor = FFTEnsembleProcessor(...
                ensemble=testCase.brokerFFT,numWorkers=5);
            fftProcessor.process();
            
            % Create SFRFs processor case spectra
            testCase.sfrfsProcessorFFT = SFRFsEnsembleProcessor( ...
                'numWorkers', testCase.ensembleMockFFT.numMembers, ...
                'ensemble', testCase.brokerFFT, ...
                'frequencyBands', testCase.bearingFrequencyBands, ...
                'snapshotParameters', testCase.snapshotParams);

            % Register cleanup automatically
            testCase.addTeardown(@() testCase.ensembleMockNoFFT.cleanup());
            testCase.addTeardown(@() testCase.ensembleMockFFT.cleanup());
        end
    end

    methods (Test)
        function testProcessFailsWithoutFFT(testCase)            
            % Load one member table manually
            t = read(testCase.ensembleMockNoFFT.fileEnsembleDS);
            
            % Confirm that the table does NOT have FFT data yet
            testCase.assertFalse(...
                any(contains(t.Properties.VariableNames, 'FFT')), ...
                'Precondition failed: table should not contain FFT data');
            
            try
                testCase.sfrfsProcessorNoFFT.process();
                testCase.verifyFail('Expected exception was not thrown.');
            catch ME
                % Verify top-level aggregate exception ID
                testCase.verifyEqual(...
                    ME.identifier, 'SFRFsProcessor:ProcessingError');
                
                % Verify nested causes contain the expected exception ID
                causeIds = cellfun(@(c) c.identifier, ...
                    ME.cause, 'UniformOutput', false);
                hasExpected = any(strcmp( ...
                    'sfrfs:EnsembleProcessor:MissingFFTColumn', causeIds));
                testCase.verifyTrue(hasExpected, ...
                    'Expected MissingFFTColumn exception not in causes.');
            end
        end

        function testProcessSucceedsWithFFT(testCase)
            EnsembleDatastoreRegistry.factoryReset();
            EnsembleDatastoreRegistry.addEnsemble( ...
                name="ensembleWithFFT", ...
                datastore=testCase.ensembleMockFFT.fileEnsembleDS);

            EnsembleDatastoreRegistry.reconfigureEnsemble( ...
                name="ensembleWithFFT", ...
                DataVariables=testCase.temporalSnapshotColumns);

            dsReg = EnsembleDatastoreRegistry.getEnsemble("ensembleWithFFT");

            broker = SFRFsEnsembleBroker( ...
                ensembleObject=dsReg, ...
                getFilesFunction=@(obj) obj.Files, ...
                temporalSnapshotColumns=testCase.temporalSnapshotColumns);

            sfrfsProcessor = SFRFsEnsembleProcessor( ...
                numWorkers=testCase.ensembleMockFFT.numMembers, ...
                ensemble=broker, ...
                frequencyBands=testCase.bearingFrequencyBands, ...
                snapshotParameters=testCase.snapshotParams);

            testCase.verifyWarningFree(@() sfrfsProcessor.process());

            sfrfCols = string(cellfun(@(c) broker.mapToSpectralColumn(c), ...
                testCase.temporalSnapshotColumns, 'UniformOutput', false)).';
            sfrfCols = sfrfCols(contains(sfrfCols, "SFRFs"));

            % Apply your updated concatenation fix
            newDataVars = [
                testCase.temporalSnapshotColumns(:);
                sfrfCols(:)];
            newSelectedVars = [
                dsReg.SelectedVariables(:);
                sfrfCols(:)];

            EnsembleDatastoreRegistry.reconfigureEnsemble( ...
                name="ensembleWithFFT", ...
                DataVariables=newDataVars, ...
                SelectedVariables=newSelectedVars);

            dsReg = ...
                EnsembleDatastoreRegistry.getEnsemble("ensembleWithFFT");
            reset(dsReg);
            tAfter = read(dsReg);

            actualVars = tAfter.Properties.VariableNames;
            testCase.verifyTrue(all(ismember(sfrfCols, actualVars)), ...
                "Not all expected SFRFs variables were found in output.");

            numFaults = numel(...
                testCase.bearingFrequencyBands.faultFrequencyCodes);

            for v = sfrfCols(:)'
                col = tAfter.(v{1});
                testCase.verifyClass(col, 'cell', ...
                    sprintf(...
                    'SFRFs variable %s must be a cell array.', v{1}));
                for i = 1:height(tAfter)
                    entry = col{i};
                    testCase.verifyClass(entry, 'double', ...
                        sprintf(...
                        'Entry %d of %s is not double.', i, v{1}));
                    testCase.verifySize(entry, [1, numFaults], ...
                        sprintf(...
                        'Entry %d of %s has wrong size.', i, v{1}));
                    testCase.verifyTrue(all(isfinite(entry)), ...
                        sprintf(...
                        'Entry %d of %s contains NaN or Inf.', i, v{1}));
                end
            end
        end

    end
end
