classdef TestRealDecoders < matlab.unittest.TestCase
% TestRealDecoders
%
% Unit tests for RealDecoders.
%
% Contract:
%   - All decoders operate on MetagenomeBlock instances.
%   - Individuals are represented by rows in the source block.
%   - Output shape is [nIndividuals, p].

    methods (Test)

        function inferRejectsUnknownSourceBlockType(testCase)
            f = @() epistemic.tools.evolutionary.phenotype.decoders. ...
                RealDecoders.infer(sourceBlockType="weird");

            testCase.verifyError( ...
                f, ...
                "sfrfs:RealDecoders:UnsupportedSourceBlockType");
        end

        function inferAcceptsComplexSourceBlockType(testCase)
            decodeFcn = epistemic.tools.evolutionary.phenotype. ...
                decoders.RealDecoders.infer( ...
                sourceBlockType="complex");

            testCase.verifyClass(decodeFcn, "function_handle");
        end

        function fromIntDecodesCircularly(testCase)
            spec = testCase.makeRealSpec_([1 6], 1.5, 4.5);

            G = [-1 0 1 2 3 4];
            loG = min(G(:));
            hiG = max(G(:));

            block = epistemic.tools.evolutionary.genomes. ...
                IntegerMetagenomeBlock( ...
                nIndividuals=1, ...
                nAtoms=6, ...
                lo=loG, ...
                hi=hiG, ...
                value=G);

            actual = epistemic.tools.evolutionary.phenotype. ...
                decoders.RealDecoders.fromInt(block, spec);

            lo = spec.domain.lo;
            hi = spec.domain.hi;
            span = hi - lo;

            expected = lo + mod(double(G) - lo, span);

            testCase.verifyEqual(actual, expected);
        end

        function fromIntPreservesRowwiseIndividuals(testCase)
            spec = testCase.makeRealSpec_([1 3], 1.5, 4.5);

            G = [ ...
                -1 0 1; ...
                 2 3 4];
            loG = min(G(:));
            hiG = max(G(:));

            block = epistemic.tools.evolutionary.genomes. ...
                IntegerMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=3, ...
                lo=loG, ...
                hi=hiG, ...
                value=G);

            actual = epistemic.tools.evolutionary.phenotype. ...
                decoders.RealDecoders.fromInt(block, spec);

            lo = spec.domain.lo;
            hi = spec.domain.hi;
            span = hi - lo;

            expected = lo + mod(double(G) - lo, span);

            testCase.verifyEqual(actual, expected);
        end

        function fromIntRejectsBadShape(testCase)
            spec = testCase.makeRealSpec_([1 5], 1.5, 4.5);

            block = epistemic.tools.evolutionary.genomes. ...
                IntegerMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=4, ...
                lo=0, ...
                hi=10);

            f = @() epistemic.tools.evolutionary.phenotype. ...
                decoders.RealDecoders.fromInt(block, spec);

            testCase.verifyError(f, "sfrfs:RealDecoders:BadShape");
        end

        function fromIntRejectsDegenerateDomain(testCase)
            spec = testCase.makeRealSpec_([1 3], 2.0, 2.0);

            G = [1 2 3];
            loG = min(G(:));
            hiG = max(G(:));

            block = epistemic.tools.evolutionary.genomes. ...
                IntegerMetagenomeBlock( ...
                nIndividuals=1, ...
                nAtoms=3, ...
                lo=loG, ...
                hi=hiG, ...
                value=G);

            f = @() epistemic.tools.evolutionary.phenotype. ...
                decoders.RealDecoders.fromInt(block, spec);

            testCase.verifyError(f, ...
                "sfrfs:RealDecoders:DegenerateDomain");
        end

        function fromBoolDecodesLinearly(testCase)
            spec = testCase.makeRealSpec_([1 4], 2.0, 6.0);

            G = logical([ ...
                0 0 0 1 1 0 1 1; ...
                1 1 1 0 0 1 0 0]);

            block = epistemic.tools.evolutionary.genomes. ...
                BooleanMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=8, ...
                value=G);

            actual = epistemic.tools.evolutionary.phenotype. ...
                decoders.RealDecoders.fromBool(block, spec);

            expected = [ ...
                2.0, 2.0 + 4.0 / 3.0, 2.0 + 8.0 / 3.0, 6.0; ...
                6.0, 2.0 + 8.0 / 3.0, 2.0 + 4.0 / 3.0, 2.0];

            testCase.verifyEqual(actual, expected);
        end

        function fromBoolRejectsBadShape(testCase)
            spec = testCase.makeRealSpec_([1 3], 2.0, 6.0);

            block = epistemic.tools.evolutionary.genomes. ...
                BooleanMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=5, ...
                value=false);

            f = @() epistemic.tools.evolutionary.phenotype. ...
                decoders.RealDecoders.fromBool(block, spec);

            testCase.verifyError(f, "sfrfs:RealDecoders:BadShape");
        end

        function fromBoolRejectsDegenerateDomain(testCase)
            spec = testCase.makeRealSpec_([1 2], 3.0, 3.0);

            block = epistemic.tools.evolutionary.genomes. ...
                BooleanMetagenomeBlock( ...
                nIndividuals=1, ...
                nAtoms=4, ...
                value=false);

            f = @() epistemic.tools.evolutionary.phenotype. ...
                decoders.RealDecoders.fromBool(block, spec);

            testCase.verifyError(f, ...
                "sfrfs:RealDecoders:DegenerateDomain");
        end

        function fromRealDecodesCircularly(testCase)
            spec = testCase.makeRealSpec_([1 6], 1.5, 4.5);

            G = [-1.6 -1.5 -1.4 0.4 0.5 0.6];
            loG = min(G(:));
            hiG = max(G(:));

            block = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals=1, ...
                nAtoms=6, ...
                lo=loG, ...
                hi=hiG, ...
                value=G);

            actual = epistemic.tools.evolutionary.phenotype. ...
                decoders.RealDecoders.fromReal(block, spec);

            lo = spec.domain.lo;
            hi = spec.domain.hi;
            span = hi - lo;

            expected = lo + mod(double(G) - lo, span);

            testCase.verifyEqual(actual, expected);
        end

        function fromRealPreservesRowwiseIndividuals(testCase)
            spec = testCase.makeRealSpec_([1 3], 1.5, 4.5);

            G = [ ...
                -1.6 -0.4 0.6; ...
                 1.4  2.4 3.4];
            loG = min(G(:));
            hiG = max(G(:));

            block = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=3, ...
                lo=loG, ...
                hi=hiG, ...
                value=G);

            actual = epistemic.tools.evolutionary.phenotype. ...
                decoders.RealDecoders.fromReal(block, spec);

            lo = spec.domain.lo;
            hi = spec.domain.hi;
            span = hi - lo;

            expected = lo + mod(double(G) - lo, span);

            testCase.verifyEqual(actual, expected);
        end

        function fromRealRejectsBadShape(testCase)
            spec = testCase.makeRealSpec_([1 5], 1.5, 4.5);

            block = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=4, ...
                lo=-1.0, ...
                hi=1.0);

            f = @() epistemic.tools.evolutionary.phenotype. ...
                decoders.RealDecoders.fromReal(block, spec);

            testCase.verifyError(f, "sfrfs:RealDecoders:BadShape");
        end

        function fromRealRejectsDegenerateDomain(testCase)
            spec = testCase.makeRealSpec_([1 3], 2.0, 2.0);

            G = [0.1 0.2 0.3];
            loG = min(G(:));
            hiG = max(G(:));

            block = epistemic.tools.evolutionary.genomes. ...
                RealMetagenomeBlock( ...
                nIndividuals=1, ...
                nAtoms=3, ...
                lo=loG, ...
                hi=hiG, ...
                value=G);

            f = @() epistemic.tools.evolutionary.phenotype. ...
                decoders.RealDecoders.fromReal(block, spec);

            testCase.verifyError(f, ...
                "sfrfs:RealDecoders:DegenerateDomain");
        end

        function fromComplexDecodesRadially(testCase)
            spec = testCase.makeRealSpec_([1 6], 1.5, 4.5);

            G = [ ...
                0.2 * exp(1i * 0), ...
                0.6 * exp(1i * pi / 3), ...
                1.2 * exp(1i * pi / 2), ...
                1.6 * exp(1i * pi), ...
                2.5 * exp(1i * 3 * pi / 2), ...
                3.6 * exp(1i * pi / 4)];

            block = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=1, ...
                nAtoms=6, ...
                lo=0, ...
                hi=4, ...
                value=G);

            actual = epistemic.tools.evolutionary.phenotype. ...
                decoders.RealDecoders.fromComplex(block, spec);

            lo = spec.domain.lo;
            hi = spec.domain.hi;
            span = hi - lo;

            expected = lo + mod(abs(G) - lo, span);

            testCase.verifyEqual(actual, expected);
        end

        function fromComplexPreservesRowwiseIndividuals(testCase)
            spec = testCase.makeRealSpec_([1 3], 1.5, 4.5);

            G = [ ...
                0.2 * exp(1i * 0), ...
                1.2 * exp(1i * pi / 2), ...
                2.6 * exp(1i * pi); ...
                3.6 * exp(1i * pi / 4), ...
                0.6 * exp(1i * pi / 3), ...
                1.6 * exp(1i * 3 * pi / 2)];

            block = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=3, ...
                lo=0, ...
                hi=4, ...
                value=G);

            actual = epistemic.tools.evolutionary.phenotype. ...
                decoders.RealDecoders.fromComplex(block, spec);

            lo = spec.domain.lo;
            hi = spec.domain.hi;
            span = hi - lo;

            expected = lo + mod(abs(G) - lo, span);

            testCase.verifyEqual(actual, expected);
        end

        function fromComplexRejectsBadShape(testCase)
            spec = testCase.makeRealSpec_([1 5], 1.5, 4.5);

            block = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=2, ...
                nAtoms=4, ...
                lo=0, ...
                hi=2);

            f = @() epistemic.tools.evolutionary.phenotype. ...
                decoders.RealDecoders.fromComplex(block, spec);

            testCase.verifyError(f, "sfrfs:RealDecoders:BadShape");
        end

        function fromComplexRejectsDegenerateDomain(testCase)
            spec = testCase.makeRealSpec_([1 3], 2.0, 2.0);

            G = [1+0i, 2+0i, 3+0i];

            block = epistemic.tools.evolutionary.genomes. ...
                ComplexMetagenomeBlock( ...
                nIndividuals=1, ...
                nAtoms=3, ...
                lo=0, ...
                hi=4, ...
                value=G);

            f = @() epistemic.tools.evolutionary.phenotype. ...
                decoders.RealDecoders.fromComplex(block, spec);

            testCase.verifyError(f, ...
                "sfrfs:RealDecoders:DegenerateDomain");
        end

    end

    methods (Access = private)

        function spec = makeRealSpec_(~, shape, lo, hi)
            spec = struct();
            spec.shape = shape;
            spec.domain = struct();
            spec.domain.lo = lo;
            spec.domain.hi = hi;
        end

    end

end