classdef TestPermutationMetagenomeBlock < matlab.unittest.TestCase

    methods (Test)

        function testExplicitValueRejectsSizeMismatch(testCase)
            f = @() epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 2, nAtoms = 3, value = [1 2 3]);

            testCase.verifyError(f, ...
                "sfrfs:PermutationMetagenomeBlock:BadValue");
        end

        function testBadNTypeErrors(testCase)
            f1 = @() epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 1, nAtoms = 2, n = NaN);

            testCase.verifyError(f1, ...
                "sfrfs:PermutationMetagenomeBlock:BadN");

            f2 = @() epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 1, nAtoms = 2, n = [3 4]);

            testCase.verifyError(f2, ...
                "sfrfs:PermutationMetagenomeBlock:BadN");
        end

        function testExplicitValueRejectsDuplicates(testCase)
            f = @() epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 1, nAtoms = 3, value = [1 1 2]);

            testCase.verifyError(f, ...
                "sfrfs:PermutationMetagenomeBlock:BadValue");
        end

        function testExplicitValueRejectsOutOfRange(testCase)
            f = @() epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 1, nAtoms = 3, value = [0 2 3]);

            testCase.verifyError(f, ...
                "sfrfs:PermutationMetagenomeBlock:BadValue");
        end

        function testExplicitValueAccepted(testCase)
            V = [1 2 3; 3 1 2];

            b = epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 2, nAtoms = 3, value = V);

            G = b.asMatrix();

            testCase.verifyEqual(G, V);
        end

        function testRandomValueIsPermutationPrefix(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 5, nAtoms = 4, n = 10);

            G = b.asMatrix();

            testCase.verifySize(G, [5, 4]);
            testCase.verifyTrue(all(G(:) == floor(G(:))));
            testCase.verifyTrue(all(G(:) >= 1));
            testCase.verifyTrue(all(G(:) <= 10));

            for i = 1:size(G, 1)
                testCase.verifyEqual( ...
                    numel(unique(G(i,:))), size(G,2));
            end
        end

        function testRowSumsEqualEulerFormula(testCase)
            nAtoms = 5;
            nIndividuals = 6;

            b = epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = nIndividuals, ...
                nAtoms = nAtoms, ...
                n = nAtoms);

            G = b.asMatrix();

            rowSums = sum(G, 2);
            expectedSum = nAtoms * (nAtoms + 1) / 2;

            testCase.verifyTrue(all(rowSums == expectedSum));
        end

        function testMutuallyExclusiveArgsError(testCase)
            f = @() epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 1, nAtoms = 2, value = [1, 2], n = 2);

            testCase.verifyError(f, ...
                "sfrfs:PermutationMetagenomeBlock:AmbiguousInit");
        end

        function testBadNErrors(testCase)
            f = @() epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 1, nAtoms = 4, n = 3);

            testCase.verifyError(f, ...
                "sfrfs:PermutationMetagenomeBlock:BadN");
        end

        function testStoresDefaultDomainSize(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 2, nAtoms = 4);

            testCase.verifyEqual(b.n, 4);
        end

        function testStoresExplicitDomainSize(testCase)
            b = epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 2, nAtoms = 4, n = 10);

            testCase.verifyEqual(b.n, 10);
        end

        function testStoresCanonicalDomainSizeWhenValueProvided(testCase)
            V = [1 2 3; 3 1 2];

            b = epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 2, nAtoms = 3, value = V);

            testCase.verifyEqual(b.asMatrix(), V);
            testCase.verifyEqual(b.n, 3);
        end

        function testGetAtomsReturnsSelectedRowLocalValues(testCase)
            G0 = [ ...
                1 2 3 4 5; ...
                5 4 3 2 1];

            b = epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                value = G0);

            values = b.getAtoms( ...
                individualIndex = 2, ...
                atomIndices = [1; 3; 5]);

            testCase.verifyEqual(values, G0(2, [1 3 5]));
        end

        function testGetAtomsRejectsBadIndividualIndex(testCase)
            b = testCase.block_();

            f = @() b.getAtoms( ...
                individualIndex = 0, ...
                atomIndices = [1; 2]);

            testCase.verifyError(f, ...
                "sfrfs:PermutationMetagenomeBlock:BadIndex");
        end

        function testGetAtomsRejectsBadAtomIndices(testCase)
            b = testCase.block_();

            f = @() b.getAtoms( ...
                individualIndex = 1, ...
                atomIndices = [1; 6]);

            testCase.verifyError(f, ...
                "sfrfs:PermutationMetagenomeBlock:BadIndex");
        end

        function testSetAtomsAcceptsValidRowLocalUpdate(testCase)
            G0 = [ ...
                1 2 3 4 5; ...
                5 4 3 2 1];

            b = epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                value = G0);

            b.setAtoms( ...
                individualIndex = 1, ...
                atomIndices = [1; 2], ...
                values = [2 1]);

            G = b.asMatrix();

            testCase.verifyEqual(G(1, :), [2 1 3 4 5]);
            testCase.verifyEqual(G(2, :), G0(2, :));
        end

        function testSetAtomsRejectsPermutationViolation(testCase)
            b = testCase.block_();

            f = @() b.setAtoms( ...
                individualIndex = 1, ...
                atomIndices = [1; 2], ...
                values = [2 2]);

            testCase.verifyError(f, ...
                "sfrfs:PermutationMetagenomeBlock:BadValue");
        end

        function testSwapAtomsSwapsPositions(testCase)
            G0 = [ ...
                1 2 3 4 5; ...
                5 4 3 2 1];

            b = epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                value = G0);

            b.swapAtoms( ...
                individualIndex = 1, ...
                atomIndexA = 2, ...
                atomIndexB = 4);

            G = b.asMatrix();

            testCase.verifyEqual(G(1, :), [1 4 3 2 5]);
            testCase.verifyEqual(G(2, :), G0(2, :));
        end

        function testSwapAtomsIsNoOpForEqualIndices(testCase)
            G0 = [ ...
                1 2 3 4 5; ...
                5 4 3 2 1];

            b = epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                value = G0);

            b.swapAtoms( ...
                individualIndex = 1, ...
                atomIndexA = 3, ...
                atomIndexB = 3);

            testCase.verifyEqual(b.asMatrix(), G0);
        end

        function testSwapAtomsRejectsBadArgs(testCase)
            b = testCase.block_();

            f = @() b.swapAtoms( ...
                individualIndex = 1, ...
                atomIndexA = 0, ...
                atomIndexB = 3);

            testCase.verifyError(f, ...
                "sfrfs:PermutationMetagenomeBlock:BadIndex");
        end

    end

    methods (Access = private)

        function b = block_(~)
            b = epistemic.tools.evolutionary.genomes. ...
                PermutationMetagenomeBlock( ...
                nIndividuals = 2, ...
                nAtoms = 5, ...
                value = [ ...
                    1 2 3 4 5; ...
                    5 4 3 2 1]);
        end
    end
end