classdef TestPhenotypeParametersDescriptor < matlab.unittest.TestCase
% TestPhenotypeParametersDescriptor
%
% Unit tests for phenotype.PhenotypeParametersDescriptor.

    methods (Test)

        function testConstructorEmpty(testCase)
            p = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();

            testCase.verifyEqual(p.nParams(), 0);

            a = p.toArray();
            testCase.verifyEqual(numel(a), 0);
            testCase.verifyTrue(isstruct(a));
        end

        function testRejectsInvalidKind(testCase)
            d = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();
        
            f = @() d.addParam( ...
                name="x", ...
                kind="real", ... % invalid (must be PhenotypeParameterKind)
                shape=[1 1]);
        
            testCase.verifyError(f, ...
                "sfrfs:PhenotypeParametersDescriptor:BadKind");
        end
        
        function testRejectsNonIntegerShape(testCase)
            d = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();
        
            f = @() d.addParam( ...
                name="x", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Real, ...
                shape=[1 2.5], ...
                lo=0, hi=1);
        
            testCase.verifyError(f, ...
                "sfrfs:PhenotypeParametersDescriptor:BadShape");
        end
        
        function testRejectsNonPositiveShape(testCase)
            d = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();
        
            f = @() d.addParam( ...
                name="x", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Real, ...
                shape=[1 0], ...
                lo=0, hi=1);
        
            testCase.verifyError(f, ...
                "sfrfs:PhenotypeParametersDescriptor:BadShape");
        end
        
        function testEnumMissingValues(testCase)
            d = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();
        
            f = @() d.addParam( ...
                name="e", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Enum);
        
            testCase.verifyError(f, ...
                "sfrfs:PhenotypeParametersDescriptor:EnumMissingValues");
        end
        
        function testEnumBadValuesType(testCase)
            d = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();
        
            f = @() d.addParam( ...
                name="e", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Enum, ...
                values=[1 2 3]); % bad type (expects string/cellstr)
        
            testCase.verifyError(f, ...
                "sfrfs:PhenotypeParametersDescriptor:EnumBadValues");
        end


        function testAddRealStoresBoundsInDomain(testCase)
            p = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();

            p.addParam( ...
                name="\Sigma_1", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Real, ...
                lo=5, ...
                hi=10, ...
                shape=[1 1]);

            testCase.verifyEqual(p.nParams(), 1);

            spec = p.getParam(1);
            schema = epistemic.tools.evolutionary.phenotype.structs. ...
                PhenotypeParameterSchema;

            testCase.verifyEqual(spec.(schema.NAME), "\Sigma_1");
            testCase.verifyEqual(spec.(schema.KIND), ...
                epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Real);
            testCase.verifyEqual(spec.(schema.SHAPE), [1 1]);

            dom = spec.(schema.DOMAIN);
            testCase.verifyTrue(isfield(dom, "lo"));
            testCase.verifyTrue(isfield(dom, "hi"));
            testCase.verifyEqual(dom.lo, 5);
            testCase.verifyEqual(dom.hi, 10);
            testCase.verifyFalse(isfield(dom, "bounds"));
        end

        function testAddEnumStoresValuesInDomain(testCase)
            p = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();

            p.addParam( ...
                name="mode", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Enum, ...
                values=["fast","safe"]);

            spec = p.getParam(1);
            schema = epistemic.tools.evolutionary.phenotype.structs. ...
                PhenotypeParameterSchema;

            dom = spec.(schema.DOMAIN);
            testCase.verifyTrue(isfield(dom, "values"));
            testCase.verifyEqual(dom.values, ["fast","safe"]);
        end

        function testAddPermStoresNInDomain(testCase)
            p = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();

            p.addParam( ...
                name="order", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Perm, ...
                n=7);

            spec = p.getParam(1);
            schema = epistemic.tools.evolutionary.phenotype.structs. ...
                PhenotypeParameterSchema;

            dom = spec.(schema.DOMAIN);
            testCase.verifyTrue(isfield(dom, "n"));
            testCase.verifyEqual(dom.n, 7);
        end

        function testAddBoolDomainEmptyStruct(testCase)
            p = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();

            p.addParam( ...
                name="enabled", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Bool);

            spec = p.getParam(1);
            schema = epistemic.tools.evolutionary.phenotype.structs. ...
                PhenotypeParameterSchema;

            dom = spec.(schema.DOMAIN);
            testCase.verifyTrue(isstruct(dom));
            testCase.verifyEmpty(fieldnames(dom));
        end

        function testAddCustomStoresOptionsInDomain(testCase)
            p = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();

            opt = struct("type","complex","maxAbs",2);

            p.addParam( ...
                name="z0", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Custom, ...
                options=opt);

            spec = p.getParam(1);
            schema = epistemic.tools.evolutionary.phenotype.structs. ...
                PhenotypeParameterSchema;

            dom = spec.(schema.DOMAIN);
            testCase.verifyTrue(isfield(dom, "options"));
            testCase.verifyEqual(dom.options, opt);
        end

        function testToArrayReturnsCopy(testCase)
            p = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();

            p.addParam( ...
                name="x", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Real, ...
                lo=0, hi=1);

            a1 = p.toArray();
            a2 = p.toArray();

            testCase.verifyEqual(a1, a2);
            testCase.verifyEqual(numel(a1), 1);
        end

        function testAddParamRejectsDuplicateName(testCase)
            p = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();

            p.addParam( ...
                name="x", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Real, ...
                lo=0, hi=1);

            testCase.verifyError(@() p.addParam( ...
                name="x", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Real, ...
                lo=0, hi=1), ...
                "sfrfs:PhenotypeParametersDescriptor:DuplicateName");
        end

        function testHasParamReflectsPresence(testCase)
            p = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();

            testCase.verifyFalse(p.hasParam("x"));

            p.addParam( ...
                name="x", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Real, ...
                lo=0, hi=1);

            testCase.verifyTrue(p.hasParam("x"));
            testCase.verifyFalse(p.hasParam("y"));
        end

        function testIndexOfUnknownNameErrors(testCase)
            p = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();

            testCase.verifyError(@() p.indexOf("nope"), ...
                "sfrfs:PhenotypeParametersDescriptor:UnknownName");
        end

        function testIndexOfReturnsInsertionIndex(testCase)
            p = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();

            p.addParam(name="a", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Bool);
            p.addParam(name="b", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Bool);
            p.addParam(name="c", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Bool);

            testCase.verifyEqual(p.indexOf("a"), 1);
            testCase.verifyEqual(p.indexOf("b"), 2);
            testCase.verifyEqual(p.indexOf("c"), 3);
        end

        function testGetParamByNameMatchesGetParam(testCase)
            p = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();

            p.addParam( ...
                name="x", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Real, ...
                lo=0, hi=1);

            s1 = p.getParam(1);
            s2 = p.getParamByName("x");

            schema = epistemic.tools.evolutionary.phenotype.structs. ...
                PhenotypeParameterSchema;

            testCase.verifyEqual(s1, s2);
            testCase.verifyEqual(s2.(schema.NAME), "x");
        end

        function testNamesReturnsInInsertionOrder(testCase)
            p = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();

            testCase.verifyEqual(p.names(), string.empty(1, 0));

            p.addParam(name="b", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Bool);
            p.addParam(name="a", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Bool);

            testCase.verifyEqual(p.names(), ["b","a"]);
        end

        function testAddRealAcceptsElementwiseBounds(testCase)
            p = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();

            p.addParam( ...
                name="A", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Real, ...
                shape=[1 3], ...
                lo=[0 1 2], ...
                hi=[3 4 5]);

            spec = p.getParam(1);
            schema = epistemic.tools.evolutionary.phenotype.structs. ...
                PhenotypeParameterSchema;

            dom = spec.(schema.DOMAIN);
            testCase.verifyEqual(dom.lo, [0 1 2]);
            testCase.verifyEqual(dom.hi, [3 4 5]);
        end

        function testAddRealRejectsBoundsShapeMismatch(testCase)
            p = epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParametersDescriptor();

            f = @() p.addParam( ...
                name="A", ...
                kind=epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind.Real, ...
                shape=[1 3], ...
                lo=[0 1], ...
                hi=[3 4]);

            testCase.verifyError(f, ...
                "sfrfs:PhenotypeParametersDescriptor:BoundsShape");
        end

    end
end
