classdef TestConfigValidator < matlab.unittest.TestCase
% TestConfigValidator
%
% Unit tests for:
%   epistemic.tools.evolutionary.internal.ConfigValidator

    methods (Test)

        function ValidateAll_Passes(testCase)

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator.validateAllConfigurationParameters( ...
                100, ...
                100, ...
                0.01, ...
                1.5, ...
                1.0e-10));
        end

        function ValidateAll_BadPopulation_Throws(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator.validateAllConfigurationParameters( ...
                0, ...
                100, ...
                0.01, ...
                1.5, ...
                1.0e-10), ...
                "sfrfs:ConfigValidator:BadPopulationSize");
        end

        function ValidateAll_BadMaxGenerations_Throws(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator.validateAllConfigurationParameters( ...
                100, ...
                0, ...
                0.01, ...
                1.5, ...
                1.0e-10), ...
                "sfrfs:ConfigValidator:BadMaxGenerations");
        end

        function ValidateAll_BadMutationRateShape_Throws(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator.validateAllConfigurationParameters( ...
                100, ...
                100, ...
                [0.01 0.02], ...
                1.5, ...
                1.0e-10), ...
                "sfrfs:ConfigValidator:BadMutationRate");
        end

        function ValidateAll_MutationRateBelowRange_Throws(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator.validateAllConfigurationParameters( ...
                100, ...
                100, ...
                -0.01, ...
                1.5, ...
                1.0e-10), ...
                "sfrfs:ConfigValidator:MutationRateOutOfRange");
        end

        function ValidateAll_MutationRateAboveRange_Throws(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator.validateAllConfigurationParameters( ...
                100, ...
                100, ...
                1.01, ...
                1.5, ...
                1.0e-10), ...
                "sfrfs:ConfigValidator:MutationRateOutOfRange");
        end

        function ValidateAll_BadPowerLawAlpha_Throws(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator.validateAllConfigurationParameters( ...
                100, ...
                100, ...
                0.01, ...
                0, ...
                1.0e-10), ...
                "sfrfs:ConfigValidator:BadPowerLawAlpha");
        end

        function ValidateAll_BadPowerLawRMin_Throws(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator.validateAllConfigurationParameters( ...
                100, ...
                100, ...
                0.01, ...
                1.5, ...
                0), ...
                "sfrfs:ConfigValidator:BadPowerLawRMin");
        end

        function PopulationSize_PositiveInteger_Passes(testCase)

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator. ...
                validatePopulationSizeIsPositiveIntegerScalar(1));
        end

        function PopulationSize_Invalid_Throws(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator. ...
                validatePopulationSizeIsPositiveIntegerScalar(0), ...
                "sfrfs:ConfigValidator:BadPopulationSize");

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator. ...
                validatePopulationSizeIsPositiveIntegerScalar(2.5), ...
                "sfrfs:ConfigValidator:BadPopulationSize");
        end

        function MaxGenerations_PositiveInteger_Passes(testCase)

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator. ...
                validateMaxGenerationsIsPositiveIntegerScalar(1));
        end

        function MaxGenerations_Invalid_Throws(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator. ...
                validateMaxGenerationsIsPositiveIntegerScalar(0), ...
                "sfrfs:ConfigValidator:BadMaxGenerations");

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator. ...
                validateMaxGenerationsIsPositiveIntegerScalar(3.2), ...
                "sfrfs:ConfigValidator:BadMaxGenerations");
        end

        function MutationRate_FiniteScalar_Passes(testCase)

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator.validateMutationRateIsNumericScalar( ...
                0.01));
        end

        function MutationRate_NotScalar_Throws(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator.validateMutationRateIsNumericScalar( ...
                [0.01 0.02]), ...
                "sfrfs:ConfigValidator:BadMutationRate");
        end

        function MutationRate_UnitInterval_Passes(testCase)

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator. ...
                validateMutationRateIsWithinClosedUnitInterval(0));

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator. ...
                validateMutationRateIsWithinClosedUnitInterval(1));
        end

        function MutationRate_OutOfRange_Throws(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator. ...
                validateMutationRateIsWithinClosedUnitInterval(-eps), ...
                "sfrfs:ConfigValidator:MutationRateOutOfRange");

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator. ...
                validateMutationRateIsWithinClosedUnitInterval( ...
                1 + eps), ...
                "sfrfs:ConfigValidator:MutationRateOutOfRange");
        end

        function PowerLawAlpha_PositiveScalar_Passes(testCase)

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator.validatePowerLawAlphaIsPositiveScalar( ...
                1.5));
        end

        function PowerLawAlpha_Invalid_Throws(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator.validatePowerLawAlphaIsPositiveScalar( ...
                0), ...
                "sfrfs:ConfigValidator:BadPowerLawAlpha");

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator.validatePowerLawAlphaIsPositiveScalar( ...
                -0.5), ...
                "sfrfs:ConfigValidator:BadPowerLawAlpha");
        end

        function PowerLawRMin_PositiveScalar_Passes(testCase)

            testCase.verifyWarningFree(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator.validatePowerLawRMinIsPositiveScalar( ...
                1.0e-10));
        end

        function PowerLawRMin_Invalid_Throws(testCase)

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator.validatePowerLawRMinIsPositiveScalar( ...
                0), ...
                "sfrfs:ConfigValidator:BadPowerLawRMin");

            testCase.verifyError(@() ...
                epistemic.tools.evolutionary.internal. ...
                ConfigValidator.validatePowerLawRMinIsPositiveScalar( ...
                -1.0e-6), ...
                "sfrfs:ConfigValidator:BadPowerLawRMin");
        end

    end

end