classdef TestSFRFsParametersRollingBearings < matlab.unittest.TestCase
    % Test suite for the SFRFsParametersRollingBearings class.
    %
    % Covers:
    %   - Construction in Mode 1 (all faults specified)
    %   - Construction in Mode 2 (SameForAllFaultTypes specified)
    %   - Validation errors for missing required fields
    %   - Validation errors for mode conflict

    properties
        completeParams
        paramsNoSidebands
        partialParams
    end

    methods (TestMethodSetup)
        function prepareParameters(testCase)
            % Fully specified valid SFRFs parameters
            testCase.completeParams = ...
                SFRFsParameters.createSFRFsParameters(...
                'order', 3, ...
                'numSidebands', 4, ...
                'numHarmonics', 8, ...
                'sigmaCenter', [5, 7], ...
                'sigmaSurround', [12, 3], ...
                'inhibitionFactor', 0.6);
            testCase.paramsNoSidebands = ...
                SFRFsParameters.createSFRFsParameters( ...
                'order', 3, ...
                'numSidebands', 0, ...
                'numHarmonics', 8, ...
                'sigmaCenter', [5, 7], ...
                'sigmaSurround', [12, 3], ...
                'inhibitionFactor', 0.6);

            % Partially specified (missing required fields) for error tests
            testCase.partialParams = struct('order', 1);
        end
    end

    methods (Test)
        function testMode1ValidConstruction(testCase)
            % All four faults specified with valid structs
            obj = SFRFsParametersRollingBearings( ...
                'outerRace', testCase.paramsNoSidebands, ...
                'innerRace', testCase.completeParams, ...
                'ball',      testCase.completeParams, ...
                'cage',      testCase.paramsNoSidebands);

            % Verify all properties were assigned correctly
            testCase.verifyEqual(...
                obj.outerRace, testCase.paramsNoSidebands);
            testCase.verifyEqual(obj.innerRace, testCase.completeParams);
            testCase.verifyEqual(obj.ball, testCase.completeParams);
            testCase.verifyEqual(obj.cage, testCase.paramsNoSidebands);
        end

        function testMode2ValidConstruction(testCase)
            % Only SameForAllFaultTypes specified
            obj = SFRFsParametersRollingBearings( ...
                'SameForAllFaultTypes', testCase.completeParams);

            % All four should match the shared struct, but for sidebands
            testCase.verifyEqual(...
                obj.outerRace, testCase.paramsNoSidebands);
            testCase.verifyEqual(obj.innerRace, testCase.completeParams);
            testCase.verifyEqual(obj.ball, testCase.completeParams);
            testCase.verifyEqual(obj.cage, testCase.paramsNoSidebands);
        end

        function testMissingFieldsError(testCase)
            % Missing required fields in one fault type should error
            testCase.verifyError(@() ...
                SFRFsParametersRollingBearings( ...
                    'outerRace', testCase.partialParams, ...
                    'innerRace', testCase.completeParams, ...
                    'ball',      testCase.completeParams, ...
                    'cage',      testCase.completeParams), ...
                ['sfrfs:SFRFsParametersRollingBearings:validateInputs:' ...
                'MissingSFRFsParameters']);
        end

        function testMutualExclusivityError(testCase)
            % Providing both SameForAllFaultTypes and others should error
            testCase.verifyError(@() ...
                SFRFsParametersRollingBearings( ...
                    'SameForAllFaultTypes', testCase.completeParams, ...
                    'outerRace', testCase.completeParams), ...
                ['sfrfs:SFRFsParametersRollingBearings:validateInputs:'...
                'ConflictingArguments']);
        end

        function testMissingFaultTypeError(testCase)
            % innerRace missing entirely, cage empty
            complete = testCase.completeParams; % from TestMethodSetup

            testCase.verifyError(@() ...
                SFRFsParametersRollingBearings( ...
                'outerRace', complete, ...
                'ball',      complete, ...
                'cage',      struct() ), ...
                ['sfrfs:SFRFsParametersRollingBearings:validateInputs:'...
                'MissingArguments']);
        end

        function testOrderValidation(testCase)
            % Negative order should error
            f = @()SFRFsParameters.createSFRFsParameters(...
                'order', -1);
            testCase.verifyError(f, 'MATLAB:validators:mustBeNonnegative');
    
            % Non-integer order should error
            f = @()SFRFsParameters.createSFRFsParameters(...
                'order', 2.5);
            testCase.verifyError(f, 'MATLAB:validators:mustBeInteger');
        end
    
        function testNumSidebandsValidation(testCase)
            % Negative numSidebands should error
            f = @()SFRFsParameters.createSFRFsParameters(...
                'numSidebands', -1);
            testCase.verifyError(f, 'MATLAB:validators:mustBeNonnegative');
    
            % Non-integer numSidebands should error
            f = @()SFRFsParameters.createSFRFsParameters(...
                'numSidebands', 1.5);
            testCase.verifyError(f, 'MATLAB:validators:mustBeInteger');
        end
    
        function testNumHarmonicsValidation(testCase)
            % Zero or less numHarmonics should error
            f = @()SFRFsParameters.createSFRFsParameters(...
                'numHarmonics', 0);
            testCase.verifyError(f, 'MATLAB:validators:mustBePositive');
    
            % Non-integer numHarmonics should error
            f = @()SFRFsParameters.createSFRFsParameters(...
                'numHarmonics', 2.2);
            testCase.verifyError(f, 'MATLAB:validators:mustBeInteger');
        end
    
        function testSigmaCenterValidation(testCase)
            % Negative element in sigmaCenter should error
            f = @()SFRFsParameters.createSFRFsParameters(...
                'sigmaCenter', [-1 6]);
            testCase.verifyError(f, 'MATLAB:validators:mustBePositive');
    
            % Wrong size for sigmaCenter should error
            f = @()SFRFsParameters.createSFRFsParameters(...
                'sigmaCenter', [4 6 8]);
            testCase.verifyError(f, 'MATLAB:validation:IncompatibleSize');
        end
    
        function testSigmaSurroundValidation(testCase)
            % Zero or negative element in sigmaSurround should error
            f = @()SFRFsParameters.createSFRFsParameters(...
                'sigmaSurround', [0 1]);
            testCase.verifyError(f, 'MATLAB:validators:mustBePositive');
    
            % Wrong size for sigmaSurround should error
            f = @()SFRFsParameters.createSFRFsParameters(...
                'sigmaSurround', [12 1 2]);
            testCase.verifyError(f, 'MATLAB:validation:IncompatibleSize');
        end
    
        function testInhibitionFactorValidation(testCase)
            % Inhibition factor below zero should error
            f = @()SFRFsParameters.createSFRFsParameters(...
                'inhibitionFactor', -0.1);
            testCase.verifyError(f, ...
                'MATLAB:validators:mustBeGreaterThanOrEqual');
    
            % Inhibition factor above one should error
            f = @()SFRFsParameters.createSFRFsParameters(...
                'inhibitionFactor', 1.1);
            testCase.verifyError(f, ...
                'MATLAB:validators:mustBeLessThanOrEqual');
        end

        function testMode1ValidConstructionWithMasks(testCase)
            % New interface: buildSFRFsParameters
            pNoSidebands = SFRFsParameters.buildSFRFsParameters( ...
                order=3, numSidebands=0, numHarmonics=8, ...
                centerMask = ...
                GaussianMaskParameters('bandwidth',5,'sigmaRule',7), ...
                surroundMask = ...
                GaussianMaskParameters('bandwidth',12,'sigmaRule',3), ...
                inhibitionFactor=0.6);
        
            pFull = SFRFsParameters.buildSFRFsParameters( ...
                order=3, numSidebands=4, numHarmonics=8, ...
                centerMask = ...
                GaussianMaskParameters('bandwidth',5,'sigmaRule',7), ...
                surroundMask = ...
                SuperGaussianMaskParameters('alpha',12,'beta',4), ...
                inhibitionFactor=0.6);
        
            obj = SFRFsParametersRollingBearings( ...
                'outerRace', pNoSidebands, ...
                'innerRace', pFull, ...
                'ball',      pFull, ...
                'cage',      pNoSidebands);
        
            testCase.verifyEqual(obj.outerRace, pNoSidebands);
            testCase.verifyEqual(obj.innerRace, pFull);
            testCase.verifyEqual(obj.ball, pFull);
            testCase.verifyEqual(obj.cage, pNoSidebands);
        
            % Sanity: mask objects exist and are MaskParameters
            testCase.verifyTrue( ...
                isa(obj.innerRace.centerMask, 'MaskParameters'));
            testCase.verifyTrue( ...
                isa(obj.innerRace.surroundMask, 'MaskParameters'));
        end
        
        function testMode2ValidConstructionWithMasks(testCase)
            % SameForAllFaultTypes with mask interface
            shared = SFRFsParameters.buildSFRFsParameters( ...
                order = 3, ...
                numSidebands = 4 , ...
                numHarmonics = 8, ...
                centerMask = ...
                GaussianMaskParameters('bandwidth',5,'sigmaRule',7), ...
                surroundMask = ...
                SuperGaussianMaskParameters('alpha',12,'beta',4), ...
                inhibitionFactor = 0.6);
        
            obj = SFRFsParametersRollingBearings( ...
                'SameForAllFaultTypes', shared);
        
            % OuterRace and Cage must be forced to 0 sidebands
            testCase.verifyEqual(obj.outerRace.numSidebands, 0);
            testCase.verifyEqual(obj.cage.numSidebands, 0);
        
            % Inner + Ball preserve shared sidebands
            testCase.verifyEqual( ...
                obj.innerRace.numSidebands, shared.numSidebands);
            testCase.verifyEqual( ...
                obj.ball.numSidebands, shared.numSidebands);
        
            % Masks preserved
            testCase.verifyTrue( ...
                isa(obj.innerRace.centerMask, 'MaskParameters'));
            testCase.verifyTrue(isa( ...
                obj.innerRace.surroundMask, 'MaskParameters'));
        end
        
        function testOuterRaceSidebandsNotAllowedLegacy(testCase)
            % Legacy interface: outerRace must have 0 sidebands
            pOuterBad = SFRFsParameters.createSFRFsParameters( ...
                'order', 1, 'numSidebands', 2, 'numHarmonics', 8, ...
                'sigmaCenter', [5 7], 'sigmaSurround', [12 3], ...
                'inhibitionFactor', 0.6);
        
            pOk = testCase.completeParams; 
            pNoSb = testCase.paramsNoSidebands;
        
            f = @() SFRFsParametersRollingBearings( ...
                'outerRace', pOuterBad, ...
                'innerRace', pOk, ...
                'ball',      pOk, ...
                'cage',      pNoSb);
        
            testCase.verifyError(f, ...
                ['sfrfs:SFRFsParametersRollingBearings:' ...
                 'InvalidNumSidebands']);
        end
        
        function testCageSidebandsNotAllowedLegacy(testCase)
        % Legacy interface: cage must have 0 sidebands
            pCageBad = SFRFsParameters.createSFRFsParameters( ...
                'order', 1, 'numSidebands', 1, 'numHarmonics', 8, ...
                'sigmaCenter', [5 7], 'sigmaSurround', [12 3], ...
                'inhibitionFactor', 0.6);
        
            pOk = testCase.completeParams;
            pNoSb = testCase.paramsNoSidebands;
        
            f = @() SFRFsParametersRollingBearings( ...
                'outerRace', pNoSb, ...
                'innerRace', pOk, ...
                'ball',      pOk, ...
                'cage',      pCageBad);
        
            testCase.verifyError(f, ...
                'sfrfs:SFRFsParametersRollingBearings:InvalidNumSidebands');
        end
        
        function testOuterRaceSidebandsNotAllowedMasks(testCase)
        % Mask interface: outerRace must have 0 sidebands
            pOuterBad = SFRFsParameters.buildSFRFsParameters( ...
                order = 1, ...
                numSidebands = 2, ...
                numHarmonics = 8, ...
                centerMask = ...
                GaussianMaskParameters('bandwidth',5,'sigmaRule',7), ...
                surroundMask = ...
                GaussianMaskParameters('bandwidth',12,'sigmaRule',3), ...
                inhibitionFactor = 0.6);
        
            pOk = SFRFsParameters.buildSFRFsParameters( ...
                order = 1, ...
                numSidebands = 4, ...
                numHarmonics = 8, ...
                centerMask = ...
                GaussianMaskParameters('bandwidth',5,'sigmaRule',7), ...
                surroundMask = ...
                SuperGaussianMaskParameters('alpha',12,'beta',4), ...
                inhibitionFactor = 0.6);
        
            pNoSb = SFRFsParameters.buildSFRFsParameters( ...
                order = 1, ...
                numSidebands = 0, ...
                numHarmonics = 8, ...
                centerMask = ...
                GaussianMaskParameters('bandwidth',5,'sigmaRule',7), ...
                surroundMask = ...
                GaussianMaskParameters('bandwidth',12,'sigmaRule',3), ...
                inhibitionFactor=0.6);
        
            f = @() SFRFsParametersRollingBearings( ...
                'outerRace', pOuterBad, ...
                'innerRace', pOk, ...
                'ball',      pOk, ...
                'cage',      pNoSb);
        
            testCase.verifyError(f, ...
                ['sfrfs:SFRFsParametersRollingBearings:' ...
                 'InvalidNumSidebands']);
        end
        
        function testCageSidebandsNotAllowedMasks(testCase)
        % Mask interface: cage must have 0 sidebands
            pCageBad = SFRFsParameters.buildSFRFsParameters( ...
                order = 1, ...
                numSidebands = 1, ...
                numHarmonics = 8, ...
                centerMask = ...
                GaussianMaskParameters('bandwidth',5,'sigmaRule',7), ...
                surroundMask = ...
                GaussianMaskParameters('bandwidth',12,'sigmaRule',3), ...
                inhibitionFactor = 0.6);
        
            pOk = SFRFsParameters.buildSFRFsParameters( ...
                order = 1, ...
                numSidebands = 4, ...
                numHarmonics = 8, ...
                centerMask = ...
                GaussianMaskParameters('bandwidth',5,'sigmaRule',7), ...
                surroundMask = ...
                SuperGaussianMaskParameters('alpha',12,'beta',4), ...
                inhibitionFactor = 0.6);
        
            pNoSb = SFRFsParameters.buildSFRFsParameters( ...
                order = 1, ...
                numSidebands = 0, ...
                numHarmonics = 8, ...
                centerMask = ...
                GaussianMaskParameters('bandwidth',5,'sigmaRule',7), ...
                surroundMask = ...
                GaussianMaskParameters('bandwidth',12,'sigmaRule',3), ...
                inhibitionFactor = 0.6);
        
            f = @() SFRFsParametersRollingBearings( ...
                'outerRace', pNoSb, ...
                'innerRace', pOk, ...
                'ball',      pOk, ...
                'cage',      pCageBad);
        
            testCase.verifyError(f, ...
                ['sfrfs:SFRFsParametersRollingBearings:' ...
                 'InvalidNumSidebands']);
        end
        
        function testMissingCoreFieldsShouldError(testCase)
        % Missing core field numHarmonics (legacy path)
            p = struct( ...
                'order', 1, ...
                'numSidebands', 0, ...
                'sigmaCenter', [5 7], ...
                'sigmaSurround', [12 3], ...
                'inhibitionFactor', 0.6);
        
            f = @() SFRFsParametersRollingBearings( ...
                'outerRace', p, ...
                'innerRace', testCase.completeParams, ...
                'ball',      testCase.completeParams, ...
                'cage',      testCase.paramsNoSidebands);
        
            testCase.verifyError(f, ...
                ['sfrfs:SFRFsParametersRollingBearings:' ...
                 'validateInputs:MissingSFRFsParameters']);
        end
        
        function testMissingMaskFieldsShouldError(testCase)
        % Core is present, but mask fields are missing
            p = struct( ...
                'order', 1, ...
                'numSidebands', 0, ...
                'numHarmonics', 8, ...
                'inhibitionFactor', 0.6);
                % missing centerMask and surroundMask
        
            f = @() SFRFsParametersRollingBearings( ...
                'outerRace', p, ...
                'innerRace', testCase.completeParams, ...
                'ball',      testCase.completeParams, ...
                'cage',      testCase.paramsNoSidebands);

            testCase.verifyError(f, ...
                ['sfrfs:SFRFsParametersRollingBearings:' ...
                 'validateInputs:MissingSFRFsParameters']);
        end

        function testMixedLegacyAndMaskStructShouldError(testCase)
        % Mixed struct: has both sigma* and *Mask fields and
        % they are incosistent.
            p = struct( ...
                'order', 1, ...
                'numSidebands', 0, ...
                'numHarmonics', 8, ...
                'sigmaCenter', [5 7], ...
                'sigmaSurround', [12 3], ...
                'centerMask', ...
                GaussianMaskParameters('bandwidth',5,'sigmaRule',9), ...
                'surroundMask', ...
                GaussianMaskParameters('bandwidth',12,'sigmaRule',3), ...
                'inhibitionFactor', 0.6);

            f = @() SFRFsParametersRollingBearings( ...
                'outerRace', p, ...
                'innerRace', testCase.completeParams, ...
                'ball',      testCase.completeParams, ...
                'cage',      testCase.paramsNoSidebands);

            testCase.verifyError(f, ...
                ['sfrfs:SFRFsParametersRollingBearings:'...
                'validateInputs:DuplicateCenterParameterization']);
        end

        function testMode1LegacyParamsShouldPass(testCase)
        % Legacy constructor output should be accepted.

            pNoSb = SFRFsParameters.createSFRFsParameters( ...
                'order', 1, 'numSidebands', 0, 'numHarmonics', 8, ...
                'sigmaCenter', [5 7], 'sigmaSurround', [12 3], ...
                'inhibitionFactor', 0.6);

            pOk = SFRFsParameters.createSFRFsParameters( ...
                'order', 2, 'numSidebands', 4, 'numHarmonics', 8, ...
                'sigmaCenter', [5 7], 'sigmaSurround', [12 3], ...
                'inhibitionFactor', 0.6);

            obj = SFRFsParametersRollingBearings( ...
                'outerRace', pNoSb, ...
                'innerRace', pOk, ...
                'ball',      pOk, ...
                'cage',      pNoSb);

            testCase.verifyEqual(obj.outerRace, pNoSb);
            testCase.verifyEqual(obj.innerRace, pOk);
            testCase.verifyEqual(obj.ball,      pOk);
            testCase.verifyEqual(obj.cage,      pNoSb);
        end


        function testMode1MaskParamsShouldPass(testCase)
        % New interface (mask-based) should be accepted.

            pNoSb = SFRFsParameters.buildSFRFsParameters( ...
                'order', 1, 'numSidebands', 0, 'numHarmonics', 8, ...
                'centerMask',   ...
                GaussianMaskParameters('bandwidth', 5, 'sigmaRule', 7), ...
                'surroundMask', ...
                GaussianMaskParameters('bandwidth',7, 'sigmaRule', 3), ...
                'inhibitionFactor', 0.6);

            pOk = SFRFsParameters.buildSFRFsParameters( ...
                'order', 2, 'numSidebands', 4, 'numHarmonics', 8, ...
                'centerMask',   ...
                GaussianMaskParameters('bandwidth', 5, 'sigmaRule', 7), ...
                'surroundMask', ...
                SuperGaussianMaskParameters('alpha', 7, 'beta', 4), ...
                'inhibitionFactor', 0.6);

            obj = SFRFsParametersRollingBearings( ...
                'outerRace', pNoSb, ...
                'innerRace', pOk, ...
                'ball',      pOk, ...
                'cage',      pNoSb);

            testCase.verifyEqual(obj.outerRace, pNoSb);
            testCase.verifyEqual(obj.innerRace, pOk);
            testCase.verifyEqual(obj.ball,      pOk);
            testCase.verifyEqual(obj.cage,      pNoSb);
        end


        function testMode2LegacySameForAllShouldPass(testCase)
        % Legacy constructor output should be accepted.
        % Also checks outerRace/cage sidebands forced to 0.

            shared = SFRFsParameters.createSFRFsParameters( ...
                'order', 3, 'numSidebands', 4, 'numHarmonics', 8, ...
                'sigmaCenter', [5 7], 'sigmaSurround', [12 3], ...
                'inhibitionFactor', 0.6);

            obj = SFRFsParametersRollingBearings( ...
                'SameForAllFaultTypes', shared);

            testCase.verifyEqual(obj.innerRace, shared);
            testCase.verifyEqual(obj.ball,      shared);

            % OuterRace & Cage must be forced to 0 sidebands
            expectedNoSb = shared;
            expectedNoSb.numSidebands = 0;

            testCase.verifyEqual(obj.outerRace, expectedNoSb);
            testCase.verifyEqual(obj.cage,      expectedNoSb);
        end


        function testMode2MaskSameForAllShouldPass(testCase)
        % Mask-based interface should be accepted.
        % Also checks outerRace/cage sidebands forced to 0.

            shared = SFRFsParameters.buildSFRFsParameters( ...
                'order', 3, 'numSidebands', 4, 'numHarmonics', 8, ...
                'centerMask',   ...
                GaussianMaskParameters('bandwidth', 5, 'sigmaRule', 7), ...
                'surroundMask', ...
                SuperGaussianMaskParameters('alpha', 12, 'beta', 4), ...
                'inhibitionFactor', 0.6);

            obj = SFRFsParametersRollingBearings( ...
                'SameForAllFaultTypes', shared);

            testCase.verifyEqual(obj.innerRace, shared);
            testCase.verifyEqual(obj.ball,      shared);

            expectedNoSb = shared;
            expectedNoSb.numSidebands = 0;

            testCase.verifyEqual(obj.outerRace, expectedNoSb);
            testCase.verifyEqual(obj.cage,      expectedNoSb);
        end

    end
end
