classdef BooleanMetagenomeBlockValidator
% BooleanMetagenomeBlockValidator
%
% Structural validation helpers for BooleanMetagenomeBlock.
%
% Scope
%   - Constructor admission control
%   - Probability validation
%   - Explicit value validation
%   - Local atom-update validation

    methods (Static)

        function validateConstructorInputs( ...
                classMeta, nIndividuals, nAtoms, value, probability)

            arguments
                classMeta (1,1) meta.class
                nIndividuals
                nAtoms
                value = []
                probability = []
            end

            V = epistemic.tools.evolutionary.internal.ValidationUtils;

            V.mustBePositiveIntegerScalar( ...
                nIndividuals, classMeta, ...
                "BadNIndividuals", ...
                "nIndividuals must be a positive integer scalar.");

            V.mustBePositiveIntegerScalar( ...
                nAtoms, classMeta, ...
                "BadNAtoms", ...
                "nAtoms must be a positive integer scalar.");

            V.mustBeMutuallyExclusive( ...
                value, probability, classMeta, ...
                "AmbiguousInit", ...
                "Exactly one of value and probability may be specified.");

            if ~isempty(probability)
                epistemic.tools.evolutionary.internal. ...
                    BooleanMetagenomeBlockValidator. ...
                    validateProbability( ...
                        classMeta, probability);
            end

            if isempty(value)
                return
            end

            epistemic.tools.evolutionary.internal. ...
                BooleanMetagenomeBlockValidator.validateExplicitValue( ...
                classMeta, value, nIndividuals, nAtoms);
        end

        function validateProbability(classMeta, probability)
            arguments
                classMeta (1,1) meta.class
                probability
            end

            V = epistemic.tools.evolutionary.internal.ValidationUtils;

            V.mustBeFiniteScalar( ...
                probability, classMeta, "BadArg", "probability");

            V.mustBeInRange( ...
                probability, 0, 1, classMeta, ...
                "BadArg", ...
                "probability must satisfy 0 <= probability <= 1.");
        end

        function validateExplicitValue( ...
                classMeta, value, nIndividuals, nAtoms)

            arguments
                classMeta (1,1) meta.class
                value
                nIndividuals
                nAtoms
            end

            V = epistemic.tools.evolutionary.internal.ValidationUtils;

            V.mustBePositiveIntegerScalar( ...
                nIndividuals, classMeta, ...
                "BadNIndividuals", ...
                "nIndividuals must be a positive integer scalar.");

            V.mustBePositiveIntegerScalar( ...
                nAtoms, classMeta, ...
                "BadNAtoms", ...
                "nAtoms must be a positive integer scalar.");

            if islogical(value) && isscalar(value)
                return
            end

            V.mustBeLogicalMatrix( ...
                value, classMeta, "BadArg", "value");

            V.mustHaveSize( ...
                value, nIndividuals, nAtoms, classMeta, ...
                "BadArg", "value");
        end

        function mustBeValidAtomIndices( ...
                classMeta, block, individualIndex, atomIndices)

            arguments
                classMeta (1,1) meta.class
                block (1,1) ...
                    epistemic.tools.evolutionary.genomes. ...
                    BooleanMetagenomeBlock
                individualIndex
                atomIndices
            end

            V = epistemic.tools.evolutionary.internal.ValidationUtils;

            V.mustBePositiveIntegerScalar( ...
                individualIndex, classMeta, ...
                "BadArg", ...
                "individualIndex must be a positive integer scalar.");

            if individualIndex > block.nIndividuals
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadArg", ...
                    message=[ ...
                    "individualIndex exceeds number of individuals." ...
                    ]);
            end

            if isempty(atomIndices)
                return
            end

            if ~(isnumeric(atomIndices) && isvector(atomIndices) && ...
                    all(isfinite(atomIndices)) && ...
                    all(atomIndices == floor(atomIndices)) && ...
                    all(atomIndices >= 1))
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadArg", ...
                    message=...
                    "atomIndices must be a positive integer vector.");
            end

            if any(atomIndices > block.nAtoms)
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadArg", ...
                    message="atomIndices exceed number of atoms.");
            end
        end

        function mustBeValidAtomUpdate( ...
                classMeta, block, individualIndex, atomIndices, values)

            arguments
                classMeta (1,1) meta.class
                block (1,1) ...
                    epistemic.tools.evolutionary.genomes. ...
                    BooleanMetagenomeBlock
                individualIndex
                atomIndices
                values
            end

            epistemic.tools.evolutionary.internal. ...
                BooleanMetagenomeBlockValidator. ...
                mustBeValidAtomIndices( ...
                classMeta, block, individualIndex, atomIndices);

            if isempty(atomIndices)
                return
            end

            if ~(islogical(values) || isnumeric(values))
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadArg", ...
                    message=[ ...
                    "values must be logical or numeric " ...
                    "for logical conversion." ...
                    ]);
            end

            if ~(isscalar(values) || numel(values) == numel(atomIndices))
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadArg", ...
                    message=[ ...
                    "values must be scalar or match atomIndices " ...
                    "in length." ...
                    ]);
            end
        end

    end

end