classdef ComplexMetagenomeBlockValidator
% ComplexMetagenomeBlockValidator
%
% Structural validation helpers for ComplexMetagenomeBlock.
%
% Scope
%   - Constructor admission control
%   - Domain validation for the annulus { z : lo <= |z| <= hi }
%   - Explicit value validation
%   - Row-local atom index validation
%   - Row-local atom update validation

    methods (Static)

        function validateConstructorInputs( ...
                classMeta, nIndividuals, nAtoms, lo, hi, value)

            arguments
                classMeta (1,1) meta.class
                nIndividuals (1,1) double
                nAtoms (1,1) double
                lo (1,1) double
                hi (1,1) double
                value = []
            end

            V = epistemic.tools.evolutionary.internal.ValidationUtils;

            V.mustBePositiveIntegerScalar( ...
                nIndividuals, classMeta, ...
                "BadNIndividuals", ...
                "nIndividuals must be a positive integer scalar.");

            V.mustBePositiveIntegerScalar( ...
                nAtoms, classMeta, ...
                "BadNAtoms", ...
                "nAtoms must be a positive integer scalar.");

            epistemic.tools.evolutionary.internal. ...
                ComplexMetagenomeBlockValidator.validateDomain( ...
                classMeta, lo, hi);

            if isempty(value)
                return
            end

            epistemic.tools.evolutionary.internal. ...
                ComplexMetagenomeBlockValidator.validateExplicitValue( ...
                classMeta, value, nIndividuals, nAtoms, lo, hi);
        end

        function validateDomain(classMeta, lo, hi)
            arguments
                classMeta (1,1) meta.class
                lo (1,1) double
                hi (1,1) double
            end

            V = epistemic.tools.evolutionary.internal.ValidationUtils;

            V.mustBeNonnegativeFiniteScalar( ...
                lo, classMeta, "BadArg", ...
                "lo must be a nonnegative finite scalar.");

            V.mustBeFiniteScalar( ...
                hi, classMeta, "BadArg", ...
                "hi must be a finite scalar.");

            if lo > hi
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadRange", ...
                    message= ...
                        "Lower radial bound must be <= upper radial " + ...
                        "bound.");
            end
        end

        function validateExplicitValue( ...
                classMeta, value, nIndividuals, nAtoms, lo, hi)

            arguments
                classMeta (1,1) meta.class
                value
                nIndividuals (1,1) double
                nAtoms (1,1) double
                lo (1,1) double
                hi (1,1) double
            end

            V = epistemic.tools.evolutionary.internal.ValidationUtils;

            V.mustBeFiniteComplexMatrix( ...
                value, classMeta, "BadArg", "value");

            V.mustHaveSize( ...
                value, nIndividuals, nAtoms, classMeta, ...
                "BadArg", "value");

            V.mustHaveModulusInRange( ...
                value, lo, hi, classMeta, ...
                "BadValue", ...
                "value must satisfy lo <= abs(z) <= hi.");
        end

        function mustBeValidAtomIndices( ...
                classMeta, obj, individualIndex, atomIndices)

            arguments
                classMeta (1,1) meta.class
                obj (1,1) ...
                    epistemic.tools.evolutionary.genomes. ...
                    ComplexMetagenomeBlock
                individualIndex (1,1) double
                atomIndices
            end

            if ~isfinite(individualIndex) || ...
                    individualIndex ~= floor(individualIndex) || ...
                    individualIndex < 1 || ...
                    individualIndex > obj.nIndividuals

                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadArg", ...
                    message="individualIndex must be a valid row index.");
            end

            if isempty(atomIndices)
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadArg", ...
                    message="atomIndices must be nonempty.");
            end

            if ~isnumeric(atomIndices) || ~isreal(atomIndices) || ...
                    ~isvector(atomIndices) || ...
                    any(~isfinite(atomIndices(:))) || ...
                    any(atomIndices(:) ~= floor(atomIndices(:))) || ...
                    any(atomIndices(:) < 1) || ...
                    any(atomIndices(:) > obj.nAtoms)

                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadArg", ...
                    message="atomIndices must be a vector of valid " + ...
                        "atom indices.");
            end
        end

        function mustBeValidAtomUpdate( ...
                classMeta, obj, individualIndex, atomIndices, values)

            arguments
                classMeta (1,1) meta.class
                obj (1,1) ...
                    epistemic.tools.evolutionary.genomes. ...
                    ComplexMetagenomeBlock
                individualIndex (1,1) double
                atomIndices
                values
            end

            epistemic.tools.evolutionary.internal. ...
                ComplexMetagenomeBlockValidator.mustBeValidAtomIndices( ...
                classMeta, obj, individualIndex, atomIndices);

            idx = atomIndices(:);

            V = epistemic.tools.evolutionary.internal.ValidationUtils;

            V.mustBeFiniteComplexMatrix( ...
                values, classMeta, "BadArg", "values");

            if ~(isscalar(values) || numel(values) == numel(idx))
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadArg", ...
                    message="values must be scalar or match the " + ...
                        "number of atom indices.");
            end

            V.mustHaveModulusInRange( ...
                values, obj.lo, obj.hi, classMeta, ...
                "BadValue", ...
                "Assigned values must satisfy lo <= abs(z) <= hi.");
        end

    end

end