classdef ConfigValidator
% ConfigValidator
%
% Domain-level validation for EngineConfig parameters.

    methods (Static)

        function validateAllConfigurationParameters( ...
                populationSize, ...
                maxGenerations, ...
                mutationRate, ...
                powerLawAlpha, ...
                powerLawRMin)

            CV = epistemic.tools.evolutionary.internal.ConfigValidator;

            CV.validatePopulationSizeIsPositiveIntegerScalar( ...
                populationSize);

            CV.validateMaxGenerationsIsPositiveIntegerScalar( ...
                maxGenerations);

            CV.validateMutationRateIsNumericScalar( ...
                mutationRate);

            CV.validateMutationRateIsWithinClosedUnitInterval( ...
                mutationRate);

            CV.validatePowerLawAlphaIsPositiveScalar( ...
                powerLawAlpha);

            CV.validatePowerLawRMinIsPositiveScalar( ...
                powerLawRMin);

        end

        function validatePopulationSizeIsPositiveIntegerScalar(x)

            meta = ?epistemic.tools.evolutionary.internal. ...
                ConfigValidator;

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBePositiveIntegerScalar( ...
                x, meta, ...
                "BadPopulationSize", ...
                "populationSize must be a positive integer scalar.");

        end

        function validateMaxGenerationsIsPositiveIntegerScalar(x)

            meta = ?epistemic.tools.evolutionary.internal. ...
                ConfigValidator;

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBePositiveIntegerScalar( ...
                x, meta, ...
                "BadMaxGenerations", ...
                "maxGenerations must be a positive integer scalar.");

        end

        function validateMutationRateIsNumericScalar(x)

            meta = ?epistemic.tools.evolutionary.internal. ...
                ConfigValidator;

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBeFiniteScalar( ...
                x, meta, ...
                "BadMutationRate", ...
                "mutationRate must be a finite scalar.");

        end

        function validateMutationRateIsWithinClosedUnitInterval(x)

            meta = ?epistemic.tools.evolutionary.internal. ...
                ConfigValidator;

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBeInRange( ...
                x, 0, 1, ...
                meta, ...
                "MutationRateOutOfRange", ...
                "mutationRate must lie in the interval [0,1].");

        end

        function validatePowerLawAlphaIsPositiveScalar(x)

            meta = ?epistemic.tools.evolutionary.internal. ...
                ConfigValidator;

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBePositiveScalar( ...
                x, meta, ...
                "BadPowerLawAlpha", ...
                "powerLawAlpha must be a positive scalar.");

        end

        function validatePowerLawRMinIsPositiveScalar(x)

            meta = ?epistemic.tools.evolutionary.internal. ...
                ConfigValidator;

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBePositiveScalar( ...
                x, meta, ...
                "BadPowerLawRMin", ...
                "powerLawRMin must be a positive scalar.");

        end

    end

end