classdef DecoderValidator
% DecoderValidator
%
% Structural validation helpers for decoder wiring.

    methods (Static)

        function mustHaveBitsForShape(classMeta, block, shape)
            arguments
                classMeta (1,1) meta.class
                block (1,1) epistemic.tools.evolutionary.genomes. ...
                    MetagenomeBlock
                shape (1,:) double
            end

            p = prod(shape);
            nAtoms = block.nAtoms;

            if nAtoms < p || mod(nAtoms, p) ~= 0
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadShape", ...
                    message=[ ...
                    "block.nAtoms must equal prod(shape) * nBits " + ...
                    "for some positive integer nBits."]);
            end
        end

        function mustHaveAtomCountForShape(classMeta, block, shape, suffix)
            arguments
                classMeta (1,1) matlab.metadata.Class
                block (1,1) epistemic.tools.evolutionary.genomes. ...
                    MetagenomeBlock
                shape (1,:) double
                suffix (1,1) string = "BadShape"
            end

            p = prod(shape);

            if block.nAtoms ~= p
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix=suffix, ...
                    format= ...
                        "prod(shape) must equal nAtoms (%d); got %d.", ...
                    args={p, block.nAtoms});
            end
        end

        function [lo, hi] = getDomainBounds(classMeta, spec)
            if ~isfield(spec, "domain") || ~isstruct(spec.domain)
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadSpec", ...
                    message="spec.domain must be defined.");
            end

            domain = spec.domain;

            if ~isfield(domain, "lo")
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadSpec", ...
                    message="spec.domain.lo must be defined.");
            end

            if ~isfield(domain, "hi")
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadSpec", ...
                    message="spec.domain.hi must be defined.");
            end

            lo = domain.lo;
            hi = domain.hi;

            if ~(isscalar(lo) && isnumeric(lo) && isfinite(lo))
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadSpec", ...
                    message="spec.domain.lo must be a finite scalar.");
            end

            if ~(isscalar(hi) && isnumeric(hi) && isfinite(hi))
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadSpec", ...
                    message="spec.domain.hi must be a finite scalar.");
            end
        end

        function mustHaveDomainBounds(classMeta, spec)
            [lo, hi] = epistemic.tools.evolutionary.internal. ...
                DecoderValidator.getDomainBounds(classMeta, spec);

            if lo > hi
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadRange", ...
                    message="spec.domain.lo must be <= spec.domain.hi.");
            end
        end

        function mustHaveNondegenerateDomainBounds(classMeta, spec)
            [lo, hi] = epistemic.tools.evolutionary.internal. ...
                DecoderValidator.getDomainBounds(classMeta, spec);

            if lo >= hi
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="DegenerateDomain", ...
                    message="Decoding requires hi > lo.");
            end
        end

        function mustHaveDomainValues(classMeta, spec, suffix)
            arguments
                classMeta (1,1) matlab.metadata.Class
                spec (1,1) struct
                suffix (1,1) string = "EmptyDomain"
            end

            hasDomain = isfield(spec, "domain") && isstruct(spec.domain);
            hasValues = hasDomain && isfield(spec.domain, "values");

            if ~hasValues
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix=suffix, ...
                    message="spec.domain.values is required.");
            end

            values = spec.domain.values;

            if isempty(values)
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix=suffix, ...
                    message="spec.domain.values must be non-empty.");
            end
        end

        function mustHaveAtLeastDomainValues(classMeta, spec, nMin, suffix)
            arguments
                classMeta (1,1) matlab.metadata.Class
                spec (1,1) struct
                nMin (1,1) double {mustBeInteger, mustBePositive}
                suffix (1,1) string = "DomainTooSmall"
            end

            epistemic.tools.evolutionary.internal.DecoderValidator. ...
                mustHaveDomainValues(classMeta, spec, "EmptyDomain");

            n = numel(spec.domain.values);

            if n < nMin
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix=suffix, ...
                    format= ...
                        "Domain must have at least %d values; got %d.", ...
                    args={nMin, n});
            end
        end

        function n = mustHavePermutationDomainSize(classMeta, spec)
            if ~isfield(spec, "domain") || ~isstruct(spec.domain)
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadSpec", ...
                    message="spec.domain must be defined.");
            end

            if ~isfield(spec.domain, "n")
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadSpec", ...
                    message="spec.domain.n must be defined.");
            end

            n = spec.domain.n;

            if ~(isscalar(n) && isnumeric(n) && isfinite(n) && ...
                    (n == floor(n)) && (n > 0))
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadSpec", ...
                    message="spec.domain.n must be a positive integer.");
            end
        end

        function mustHavePermutationShapeConsistentWithDomain( ...
                classMeta, spec)

            n = epistemic.tools.evolutionary.internal.DecoderValidator. ...
                mustHavePermutationDomainSize(classMeta, spec);

            if prod(spec.shape) ~= n
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadShape", ...
                    format= ...
                        "prod(shape) must equal domain.n (%d); got %d.", ...
                    args={n, prod(spec.shape)});
            end
        end

        function mustHavePermutationBlockConsistentWithDomain( ...
                classMeta, block, spec)

            n = epistemic.tools.evolutionary.internal.DecoderValidator. ...
                mustHavePermutationDomainSize(classMeta, spec);

            if block.nAtoms ~= n
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadShape", ...
                    format= ...
                        "block.nAtoms must equal domain.n (%d); got %d.", ...
                    args={n, block.nAtoms});
            end
        end

        function mustBeCanonicalPermutationMatrix( ...
                G, nIndividuals, nAtoms, classMeta, suffix, name)

            arguments
                G
                nIndividuals (1,1) double
                nAtoms (1,1) double
                classMeta (1,1) matlab.metadata.Class
                suffix (1,1) string = "BadValue"
                name (1,1) string = "value"
            end

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustHaveSize( ...
                    G, nIndividuals, nAtoms, classMeta, suffix, name);

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBeIntegerMatrix( ...
                    G, classMeta, suffix, name);

            if any(G(:) < 1)
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix=suffix, ...
                    message=name + " entries must be positive indices.");
            end

            for i = 1:size(G, 1)
                row = G(i, :);

                if numel(unique(row)) ~= nAtoms
                    helpers.Errors.raise( ...
                        classMeta=classMeta, ...
                        suffix=suffix, ...
                        message="Each row must contain unique indices.");
                end

                if min(row) ~= 1 || max(row) ~= nAtoms
                    helpers.Errors.raise( ...
                        classMeta=classMeta, ...
                        suffix=suffix, ...
                        message=[ ...
                        "Each row must be a permutation of 1:nAtoms."]);
                end
            end
        end

        function mustBePositiveIntegerScalar(classMeta, x, suffix, name)
            if ~(isscalar(x) && isnumeric(x) && isfinite(x) && ...
                    (x == floor(x)) && (x > 0))
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix=suffix, ...
                    message=name + " must be a positive integer scalar.");
            end
        end

    end

end