classdef MutationAgendaValidator
% MutationAgendaValidator
%
% Structural validation for MutationAgenda construction.
%
% Scope
%   - Validate constructor inputs only
%   - Delegate primitives to ValidationUtils
%   - Enforce stable error suffix contracts
%
% Notes
%   - No stochastic checks
%   - No agenda-content checks
%   - No mutation semantics

    methods (Static)

        function validateConstructorInputs( ...
                classMeta, ...
                nGenerations, ...
                nIndividuals, ...
                nAtomsPerBlock, ...
                rho)

            V = epistemic.tools.evolutionary.internal.ValidationUtils;

            % --- nGenerations
            V.mustBePositiveIntegerScalar( ...
                nGenerations, classMeta, ...
                "BadNGenerations", ...
                "nGenerations must be a positive integer scalar.");

            % --- nIndividuals
            V.mustBePositiveIntegerScalar( ...
                nIndividuals, classMeta, ...
                "BadNIndividuals", ...
                "nIndividuals must be a positive integer scalar.");

            % --- nAtomsPerBlock
            
            if isempty(nAtomsPerBlock)
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="EmptyAtomsPerBlock", ...
                    message="nAtomsPerBlock must be non-empty.");
            end
            
            V.mustBeRowVector( ...
                nAtomsPerBlock, classMeta, ...
                "BadAtomsPerBlockShape", ...
                "nAtomsPerBlock must be a row vector.");
            
            V.mustBeIntegerValued( ...
                nAtomsPerBlock, classMeta, ...
                "BadAtomsPerBlockType", ...
                "nAtomsPerBlock must contain integer values.");
            
            if any(nAtomsPerBlock <= 0)
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="NonPositiveAtoms", ...
                    message="All entries in nAtomsPerBlock must be > 0.");
            end

            % --- rho
            V.mustBeFiniteScalar( ...
                rho, classMeta, ...
                "BadRho", ...
                "rho must be a finite scalar.");

            V.mustBeInRange( ...
                rho, 0, 1, classMeta, ...
                "RhoOutOfRange", ...
                "rho must satisfy 0 <= rho <= 1.");

        end

    end

end