classdef PermutationMetagenomeBlockValidator
% PermutationMetagenomeBlockValidator
%
% Structural validation helpers for PermutationMetagenomeBlock.
%
% Scope
%   - Constructor admission control
%   - Effective ambient domain resolution
%   - Explicit permutation value validation
%   - Row-local atom index validation
%   - Row-local atom update validation
%   - Swap argument validation

    methods (Static)

        function mustBeSampleWithoutReplacementRow( ...
                row, n, classMeta, suffix, name)

            arguments
                row
                n (1,1) double
                classMeta (1,1) matlab.metadata.Class
                suffix (1,1) string = "BadValue"
                name (1,1) string = "row"
            end

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBeIntegerMatrix( ...
                    row, classMeta, suffix, name);

            if ~isvector(row) || size(row, 1) ~= 1
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix=suffix, ...
                    message=name + " must be a row vector.");
            end

            if any(row(:) < 1) || any(row(:) > n)
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix=suffix, ...
                    message=name + ...
                        " entries must lie in the domain 1:n.");
            end

            if numel(unique(row)) ~= numel(row)
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix=suffix, ...
                    message=name + ...
                        " must be a sample without replacement.");
            end
        end

        function validateConstructorInputs( ...
                classMeta, nIndividuals, nAtoms, value, n)

            arguments
                classMeta (1,1) meta.class
                nIndividuals (1,1) double
                nAtoms (1,1) double
                value = []
                n = []
            end

            V = epistemic.tools.evolutionary.internal.ValidationUtils;

            V.mustBePositiveIntegerScalar( ...
                nIndividuals, classMeta, ...
                "BadNIndividuals", ...
                "nIndividuals must be a positive integer scalar.");

            V.mustBePositiveIntegerScalar( ...
                nAtoms, classMeta, ...
                "BadNAtoms", ...
                "nAtoms must be a positive integer scalar.");

            V.mustBeMutuallyExclusive( ...
                value, n, classMeta, ...
                "AmbiguousInit", ...
                "Exactly one of value and n may be specified.");
        end

        function validateExplicitValue( ...
                classMeta, value, nIndividuals, nAtoms)

            epistemic.tools.evolutionary.internal.DecoderValidator. ...
                mustBeCanonicalPermutationMatrix( ...
                value, ...
                nIndividuals, ...
                nAtoms, ...
                classMeta, ...
                "BadValue", ...
                "value");
        end

        function nEff = resolveDomainSize(classMeta, nAtoms, value, n)
        % resolveDomainSize
        % Resolve effective ambient domain size.
        %
        % Rules
        %   - explicit value => nEff = nAtoms
        %   - explicit n     => nEff = n
        %   - otherwise      => nEff = nAtoms

            V = epistemic.tools.evolutionary.internal.ValidationUtils;

            if ~isempty(value)
                nEff = nAtoms;
                return
            end

            if isempty(n)
                nEff = nAtoms;
                return
            end

            V.mustBePositiveIntegerScalar( ...
                n, classMeta, ...
                "BadN", ...
                "n must be a positive integer scalar.");

            if n < nAtoms
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadN", ...
                    message="n must be >= nAtoms.");
            end

            nEff = n;
        end

        function mustBeValidAtomIndices( ...
                classMeta, obj, individualIndex, atomIndices)

            arguments
                classMeta (1,1) meta.class
                obj (1,1) ...
                    epistemic.tools.evolutionary.genomes. ...
                    PermutationMetagenomeBlock
                individualIndex (1,1) double
                atomIndices
            end

            V = epistemic.tools.evolutionary.internal.ValidationUtils;

            V.mustBePositiveIntegerScalar( ...
                individualIndex, classMeta, ...
                "BadIndex", ...
                "individualIndex must be a positive integer scalar.");

            if individualIndex > obj.nIndividuals
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadIndex", ...
                    message="individualIndex must be a valid row index.");
            end

            if isempty(atomIndices)
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadIndex", ...
                    message="atomIndices must be nonempty.");
            end

            if ~isnumeric(atomIndices) || ~isreal(atomIndices) || ...
                    ~isvector(atomIndices) || ...
                    any(~isfinite(atomIndices(:))) || ...
                    any(atomIndices(:) ~= floor(atomIndices(:))) || ...
                    any(atomIndices(:) < 1) || ...
                    any(atomIndices(:) > obj.nAtoms)

                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadIndex", ...
                    message="atomIndices must be a vector of valid " + ...
                        "atom indices.");
            end
        end

        function mustBeValidAtomUpdate( ...
                classMeta, obj, individualIndex, atomIndices, values)

            arguments
                classMeta (1,1) meta.class
                obj (1,1) ...
                    epistemic.tools.evolutionary.genomes. ...
                    PermutationMetagenomeBlock
                individualIndex (1,1) double
                atomIndices
                values
            end

            epistemic.tools.evolutionary.internal. ...
                PermutationMetagenomeBlockValidator. ...
                mustBeValidAtomIndices( ...
                classMeta, obj, individualIndex, atomIndices);

            idx = atomIndices(:);

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBeIntegerMatrix( ...
                values, classMeta, "BadValue", "values");

            if ~(isscalar(values) || numel(values) == numel(idx))
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadValue", ...
                    message="values must be scalar or match indices.");
            end

            row = obj.asMatrix();
            row = row(individualIndex, :);

            if isscalar(values)
                row(idx) = values;
            else
                row(idx) = reshape(values, 1, []);
            end

            epistemic.tools.evolutionary.internal. ...
                PermutationMetagenomeBlockValidator. ...
                mustBeSampleWithoutReplacementRow( ...
                row, ...
                obj.n, ...
                classMeta, ...
                "BadValue", ...
                "updated row");
        end

        function mustBeValidSwapArgs( ...
                classMeta, obj, individualIndex, atomIndexA, atomIndexB)

            arguments
                classMeta (1,1) meta.class
                obj (1,1) ...
                    epistemic.tools.evolutionary.genomes. ...
                    PermutationMetagenomeBlock
                individualIndex (1,1) double
                atomIndexA (1,1) double
                atomIndexB (1,1) double
            end

            V = epistemic.tools.evolutionary.internal.ValidationUtils;

            V.mustBePositiveIntegerScalar( ...
                individualIndex, classMeta, ...
                "BadIndex", ...
                "individualIndex must be a positive integer scalar.");

            V.mustBePositiveIntegerScalar( ...
                atomIndexA, classMeta, ...
                "BadIndex", ...
                "atomIndexA must be a positive integer scalar.");

            V.mustBePositiveIntegerScalar( ...
                atomIndexB, classMeta, ...
                "BadIndex", ...
                "atomIndexB must be a positive integer scalar.");

            if individualIndex > obj.nIndividuals || ...
                    atomIndexA > obj.nAtoms || ...
                    atomIndexB > obj.nAtoms

                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix="BadIndex", ...
                    message="Swap indices must lie within block bounds.");
            end
        end

    end

end