classdef PhenotypeParameterValidator
% PhenotypeParameterValidator
% Internal, stateless validation utilities for phenotype parameters.
%
% Contract:
%   - spec follows PhenotypeParameterSchema (name, kind, domain, shape).
%   - value is [nIndividuals, prod(shape)].

    methods (Static)

        function mustBeValidValue(spec, value, nIndividuals)
            meta = epistemic.tools.evolutionary.internal. ...
                PhenotypeParameterValidator.meta_();

            epistemic.tools.evolutionary.internal. ...
                PhenotypeParameterValidator.mustBeSpecStruct_( ...
                    meta, spec);

            epistemic.tools.evolutionary.internal. ...
                ValidationUtils.mustBeNonnegativeIntegerScalar( ...
                    nIndividuals, meta, "BadScalar", ...
                    "nIndividuals must be a nonnegative integer.");

            u = epistemic.tools.evolutionary.internal. ...
                PhenotypeParameterSpecUtils;

            name = u.getName(spec, meta, "BadSpec");
            kind = u.getKind(spec, meta, "BadSpec");
            shape = u.getShape(spec, meta, "BadShape", name);
            domain = u.getDomain(spec, meta, "BadDomain", name);

            expCols = prod(shape);

            epistemic.tools.evolutionary.internal. ...
                ValidationUtils.mustHaveSize( ...
                    value, nIndividuals, expCols, meta, ...
                    "ShapeMismatch", ...
                    "Value has unexpected size.");

            pk = epistemic.tools.evolutionary.internal. ...
                PhenotypeParameterValidator.kinds_();

            switch kind
                case pk.real
                    epistemic.tools.evolutionary.internal. ...
                        ValidationUtils.mustBeFiniteNumeric( ...
                            value, meta, "NonFinite", ...
                            "Value must be finite real numeric.");

                    epistemic.tools.evolutionary.internal. ...
                        PhenotypeParameterValidator.mustRespectLoHi_( ...
                            meta, name, shape, domain, value);

                case pk.int
                    epistemic.tools.evolutionary.internal. ...
                        ValidationUtils.mustBeFiniteNumeric( ...
                            value, meta, "NonFinite", ...
                            "Value must be finite real numeric.");

                    epistemic.tools.evolutionary.internal. ...
                        ValidationUtils.mustBeIntegerValued( ...
                            value, meta, "NonInteger", ...
                            "Value has non-integers.");

                    epistemic.tools.evolutionary.internal. ...
                        PhenotypeParameterValidator.mustRespectLoHi_( ...
                            meta, name, shape, domain, value);

                case pk.bool
                    epistemic.tools.evolutionary.internal. ...
                        PhenotypeParameterValidator.mustBeBoolLike_( ...
                            meta, name, value);

                case pk.enum
                    epistemic.tools.evolutionary.internal. ...
                        PhenotypeParameterValidator.mustBeEnumLike_( ...
                            meta, name, domain, value);

                case pk.perm
                    epistemic.tools.evolutionary.internal. ...
                        PhenotypeParameterValidator.mustBePermutation_( ...
                            meta, name, domain, value);

                otherwise
                    % Custom: no assumptions.
            end
        end

    end

    methods (Static, Access = private)

        function meta = meta_()
            meta = ?epistemic.tools.evolutionary.internal. ...
                PhenotypeParameterValidator;
        end

        function mustBeSpecStruct_(meta, spec)
            if ~(isstruct(spec) && isscalar(spec))
                helpers.Errors.raise( ...
                    'classMeta', meta, ...
                    'suffix', "BadSpec", ...
                    'message', "spec must be a scalar struct.");
            end
        end

        function mustBeBoolLike_(meta, name, v)
            if islogical(v)
                return
            end

            ok = isnumeric(v) && isreal(v) && all(v == 0 | v == 1, "all");
            if ok
                return
            end

            helpers.Errors.raise( ...
                'classMeta', meta, ...
                'suffix', "BoolType", ...
                'format', "Param '%s' must be logical or {0,1}.", ...
                'args', {name});
        end

        function mustRespectLoHi_(meta, name, shape, domain, v)
            if ~isfield(domain, "lo") || ~isfield(domain, "hi")
                return
            end

            [lo, hi] = epistemic.tools.evolutionary.internal. ...
                PhenotypeParameterValidator.getLoHi_( ...
                    meta, name, shape, domain);

            if any(v < lo | v > hi, "all")
                helpers.Errors.raise( ...
                    'classMeta', meta, ...
                    'suffix', "OutOfBounds", ...
                    'format', "Param '%s' violates [lo,hi] bounds.", ...
                    'args', {name});
            end
        end

        function [lo, hi] = getLoHi_(meta, name, shape, domain)
            lo = domain.lo;
            hi = domain.hi;

            if ~isnumeric(lo) || ~isnumeric(hi)
                helpers.Errors.raise( ...
                    'classMeta', meta, ...
                    'suffix', "BoundsType", ...
                    'format', "Param '%s' domain.lo/hi must be numeric.", ...
                    'args', {name});
            end

            expCols = prod(shape);

            lo = epistemic.tools.evolutionary.internal. ...
                PhenotypeParameterValidator.reshapeBound_( ...
                    meta, name, "domain.lo", lo, shape, expCols);

            hi = epistemic.tools.evolutionary.internal. ...
                PhenotypeParameterValidator.reshapeBound_( ...
                    meta, name, "domain.hi", hi, shape, expCols);

            if any(~isfinite(lo), "all") || any(~isfinite(hi), "all")
                helpers.Errors.raise( ...
                    'classMeta', meta, ...
                    'suffix', "BoundsNonFinite", ...
                    'format', "Param '%s' bounds must be finite.", ...
                    'args', {name});
            end
        end

        function b = reshapeBound_(meta, name, field, b, shape, expCols)
            if isscalar(b)
                return
            end

            if isequal(size(b), shape)
                b = reshape(double(b), 1, expCols);
                return
            end

            if isvector(b) && numel(b) == expCols
                b = reshape(double(b), 1, expCols);
                return
            end

            helpers.Errors.raise( ...
                'classMeta', meta, ...
                'suffix', "BoundsShape", ...
                'format', "Param '%s' %s must match shape.", ...
                'args', {name, string(field)});
        end

        function mustBeEnumLike_(meta, name, domain, v)
            if ~isfield(domain, "values")
                helpers.Errors.raise( ...
                    'classMeta', meta, ...
                    'suffix', "EnumMissingValues", ...
                    'format', "Enum '%s' requires domain.values.", ...
                    'args', {name});
            end

            allowed = string(domain.values(:)).';

            if isstring(v)
                vals = v(:);
            elseif iscellstr(v)
                vals = string(v(:));
            else
                helpers.Errors.raise( ...
                    'classMeta', meta, ...
                    'suffix', "EnumType", ...
                    'format', "Enum '%s' must be string/cellstr.", ...
                    'args', {name});
            end

            if any(~ismember(vals, allowed))
                helpers.Errors.raise( ...
                    'classMeta', meta, ...
                    'suffix', "EnumInvalid", ...
                    'format', "Enum '%s' has invalid value(s).", ...
                    'args', {name});
            end
        end

        function mustBePermutation_(meta, name, domain, v)
            if ~isfield(domain, "n") || ~isscalar(domain.n)
                helpers.Errors.raise( ...
                    'classMeta', meta, ...
                    'suffix', "PermMissingN", ...
                    'format', "Perm '%s' requires scalar domain.n.", ...
                    'args', {name});
            end

            n = domain.n;

            if ~isnumeric(v) || ~isreal(v)
                helpers.Errors.raise( ...
                    'classMeta', meta, ...
                    'suffix', "PermType", ...
                    'format', "Perm '%s' must be real numeric.", ...
                    'args', {name});
            end

            if size(v, 2) ~= n
                helpers.Errors.raise( ...
                    'classMeta', meta, ...
                    'suffix', "PermWidth", ...
                    'format', "Perm '%s' expected %d cols.", ...
                    'args', {name, n});
            end

            if any(v ~= round(v), "all")
                helpers.Errors.raise( ...
                    'classMeta', meta, ...
                    'suffix', "PermNonInteger", ...
                    'format', "Perm '%s' has non-integers.", ...
                    'args', {name});
            end

            if any(v < 1 | v > n, "all")
                helpers.Errors.raise( ...
                    'classMeta', meta, ...
                    'suffix', "PermRange", ...
                    'format', "Perm '%s' must be in 1..%d.", ...
                    'args', {name, n});
            end

            for r = 1:size(v, 1)
                if numel(unique(v(r, :))) ~= n
                    helpers.Errors.raise( ...
                        'classMeta', meta, ...
                        'suffix', "PermDuplicates", ...
                        'format', ...
                        "Perm '%s' row %d has duplicates.", ...
                        'args', {name, r});
                end
            end
        end

        function k = kinds_()
            k.real = ...
                epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParameterKind.Real;

            k.int = ...
                epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParameterKind.Int;

            k.bool = ...
                epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParameterKind.Bool;

            k.enum = ...
                epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParameterKind.Enum;

            k.perm = ...
                epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParameterKind.Perm;

            k.custom = ...
                epistemic.tools.evolutionary.phenotype. ...
                PhenotypeParameterKind.Custom;
        end

    end
end
