classdef PhenotypeParametersDescriptorValidator
% PhenotypeParametersDescriptorValidator
% Internal, stateless validation utilities for 
% PhenotypeParametersDescriptor.
%
% Design
%   - Static checks only.
%   - Single error funnel via helpers.Errors.raise.
%   - Produces DEM/descriptor-scoped error identifiers.

    methods (Static)

        function mustMatchParameterNames(descMeta, descriptor, theta)
            epistemic.tools.evolutionary.internal. ...
                PhenotypeParametersDescriptorValidator.mustBeDescriptor( ...
                    descMeta, descriptor);
        
            if ~(isstruct(theta) && isscalar(theta))
                helpers.Errors.raise( ...
                    'classMeta', descMeta, ...
                    'suffix', "BadTheta", ...
                    'message', "theta must be a scalar struct.");
            end
        
            specs = descriptor.toArray();
            expected = string({specs.name});
            actual = string(fieldnames(theta)).';
        
            missing = setdiff(expected, actual);
            extra = setdiff(actual, expected);
        
            if ~isempty(missing)
                helpers.Errors.raise( ...
                    'classMeta', descMeta, ...
                    'suffix', "MissingParam", ...
                    'format', "theta is missing parameter(s): %s", ...
                    'args', {strjoin(missing, ", ")});
            end
        
            if ~isempty(extra)
                helpers.Errors.raise( ...
                    'classMeta', descMeta, ...
                    'suffix', "UnknownParam", ...
                    'format', "theta has unknown parameter(s): %s", ...
                    'args', {strjoin(extra, ", ")});
            end
        end

        function mustBeDescriptor(descMeta, descriptor)
            ok = isa(descriptor, ...
                'epistemic.tools.evolutionary.phenotype.' + ...
                "PhenotypeParametersDescriptor") && isscalar(descriptor);
        
            if ~ok
                helpers.Errors.raise( ...
                    classMeta=descMeta, ...
                    suffix="BadDescriptor", ...
                    message=[ ...
                    'descriptor must be a scalar ' ...
                    'PhenotypeParametersDescriptor.']);
            end
        end
    
        function mustBeValidExpression(...
                descMeta, descriptor, theta, nIndividuals)
            epistemic.tools.evolutionary.internal. ...
                PhenotypeParametersDescriptorValidator.mustBeDescriptor(...
                    descMeta, descriptor);
        
            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBeNonnegativeIntegerScalar( ...
                    nIndividuals, descMeta, "BadScalar", ...
                    "nIndividuals must be a nonnegative integer.");
        
            epistemic.tools.evolutionary.internal. ...
                PhenotypeParametersDescriptorValidator. ...
                mustMatchParameterNames( ...
                    descMeta, descriptor, theta);
        
            specs = descriptor.toArray();
        
            for k = 1:numel(specs)
                spec = specs(k);
                name = string(spec.name);
        
                % Field must exist by mustMatchParameterNames.
                value = theta.(name);
        
                epistemic.tools.evolutionary.internal. ...
                    PhenotypeParameterValidator.mustBeValidValue( ...
                        spec, value, nIndividuals);
            end
        end

        function mustHaveParamName(descMeta, nameToIndex, name)
            import epistemic.tools.evolutionary.internal.ValidationUtils
        
            % Defensive: keep these funnel based.
            ValidationUtils.mustBeMetaClass( ...
                descMeta, descMeta, "BadMeta", ...
                "descMeta must be a meta.class scalar.");
        
            ValidationUtils.mustBeContainersMap( ...
                nameToIndex, descMeta, "BadNameMap", ...
                "nameToIndex must be a containers.Map.");
        
            % Name checks: these must yield BadName (not BadIndex).
            ValidationUtils.mustBeStringScalar( ...
                name, descMeta, "BadName", ...
                "name must be a string scalar.");
        
            if strlength(name) == 0
                helpers.Errors.raise( ...
                    classMeta=descMeta, ...
                    suffix="BadName", ...
                    message="name must be non-empty.");
            end
        
            key = char(name);
            if ~isKey(nameToIndex, key)
                helpers.Errors.raise( ...
                    classMeta=descMeta, ...
                    suffix="UnknownName", ...
                    format="Unknown parameter name '%s'.", ...
                    args={key});
            end
        end

        function mustBeValidAddParamArgs(descMeta, args, nameExists)
            import epistemic.tools.evolutionary.internal.ValidationUtils

            ValidationUtils.mustBeStringScalar( ...
                args.name, descMeta, "BadName", ...
                "name must be a string scalar.");

            if strlength(args.name) == 0
                helpers.Errors.raise( ...
                    classMeta=descMeta, ...
                    suffix="BadName", ...
                    message="name must be non-empty.");
            end

            if nameExists
                helpers.Errors.raise( ...
                    classMeta=descMeta, ...
                    suffix="DuplicateName", ...
                    format="Parameter name '%s' is already defined.", ...
                    args={char(args.name)});
            end

            if ~isa(args.kind, ...
                    'epistemic.tools.evolutionary.phenotype.' + ...
                    "PhenotypeParameterKind") || ...
                    ~isscalar(args.kind)
                helpers.Errors.raise( ...
                    classMeta=descMeta, ...
                    suffix="BadKind", ...
                    format="Param '%s' has invalid kind.", ...
                    args={char(args.name)});
            end

            ValidationUtils.mustBeRowVector( ...
                args.shape, descMeta, "BadShape", ...
                "shape must be a row vector.");

            if isempty(args.shape) || any(~isfinite(args.shape))
                helpers.Errors.raise( ...
                    classMeta=descMeta, ...
                    suffix="BadShape", ...
                    format="Param '%s' has invalid shape.", ...
                    args={char(args.name)});
            end

            if any(args.shape ~= floor(args.shape)) || any(args.shape <= 0)
                helpers.Errors.raise( ...
                    classMeta=descMeta, ...
                    suffix="BadShape", ...
                    format= ...
                        "Param '%s' shape must be positive integers.", ...
                    args={char(args.name)});
            end

            epistemic.tools.evolutionary.internal. ...
                PhenotypeParametersDescriptorValidator. ...
                mustBeValidKindSpecific_(descMeta, args);
        end

        function domain = buildDomain(descMeta, args)
            import epistemic.tools.evolutionary.phenotype.PhenotypeParameterKind

            nameKey = char(args.name);
            shape = args.shape;

            switch args.kind
                case {PhenotypeParameterKind.Real, ...
                      PhenotypeParameterKind.Int}
                    [lo, hi] = epistemic.tools.evolutionary.internal. ...
                        PhenotypeParametersDescriptorValidator. ...
                        resolveBounds_(descMeta, nameKey, shape, ...
                        args.lo, args.hi);
                    domain = struct("lo", lo, "hi", hi);

                case PhenotypeParameterKind.Enum
                    domain = struct("values", args.values);

                case PhenotypeParameterKind.Perm
                    domain = struct("n", args.n);

                case PhenotypeParameterKind.Bool
                    domain = struct();

                case PhenotypeParameterKind.Custom
                    domain = struct("options", args.options);

                otherwise
                    domain = struct();
            end
        end

    end

    methods (Static, Access = private)

        function mustBeValidKindSpecific_(descMeta, args)
            import epistemic.tools.evolutionary.phenotype.PhenotypeParameterKind

            nameKey = char(args.name);

            switch args.kind
                case PhenotypeParameterKind.Enum
                    if isempty(args.values)
                        helpers.Errors.raise( ...
                            classMeta=descMeta, ...
                            suffix="EnumMissingValues", ...
                            format="Enum '%s' requires values.", ...
                            args={nameKey});
                    end

                    if ~isstring(args.values)
                        helpers.Errors.raise( ...
                            classMeta=descMeta, ...
                            suffix="EnumBadValues", ...
                            format="Enum '%s' values must be string.", ...
                            args={nameKey});
                    end

                case PhenotypeParameterKind.Perm
                    n = args.n;
                    ok = isnumeric(n) && isreal(n) && isscalar(n) && ...
                        isfinite(n) && (n > 0) && (n == floor(n));
                    if ~ok
                        helpers.Errors.raise( ...
                            classMeta=descMeta, ...
                            suffix="BadPermN", ...
                            format= ...
                              "Perm '%s' requires positive integer n.", ...
                            args={nameKey});
                    end

                otherwise
                    % No additional checks.
            end
        end

        function [lo, hi] = resolveBounds_( ...
                descMeta, nameKey, shape, loIn, hiIn)

            expCols = prod(shape);

            [lo, loIsScalar] = epistemic.tools.evolutionary.internal. ...
                PhenotypeParametersDescriptorValidator. ...
                normalizeBound_(descMeta, nameKey, "lo", loIn, ...
                shape, expCols);

            [hi, hiIsScalar] = epistemic.tools.evolutionary.internal. ...
                PhenotypeParametersDescriptorValidator. ...
                normalizeBound_(descMeta, nameKey, "hi", hiIn, ...
                shape, expCols);

            if loIsScalar && hiIsScalar
                if ~(isnan(lo) || isnan(hi)) && (lo > hi)
                    helpers.Errors.raise( ...
                        classMeta=descMeta, ...
                        suffix="BadBounds", ...
                        format="Param '%s' expects lo <= hi.", ...
                        args={nameKey});
                end
                return
            end

            mask = ~isnan(lo(:)) & ~isnan(hi(:));
            if any(mask & (lo(:) > hi(:)))
                helpers.Errors.raise( ...
                    classMeta=descMeta, ...
                    suffix="BadBounds", ...
                    format= ...
                        "Param '%s' expects elementwise lo <= hi.", ...
                    args={nameKey});
            end
        end

        function [b, isScalar] = normalizeBound_( ...
                descMeta, nameKey, which, bIn, shape, expCols)

            if ~(isnumeric(bIn) && isreal(bIn))
                helpers.Errors.raise( ...
                    classMeta=descMeta, ...
                    suffix="BoundsType", ...
                    format="Param '%s' %s must be real numeric.", ...
                    args={nameKey, which});
            end

            if isscalar(bIn)
                b = double(bIn);
                isScalar = true;
                return
            end

            isScalar = false;

            if isequal(size(bIn), shape)
                b = reshape(double(bIn), 1, expCols);
                return
            end

            if isvector(bIn) && (numel(bIn) == expCols)
                b = reshape(double(bIn), 1, expCols);
                return
            end

            helpers.Errors.raise( ...
                classMeta=descMeta, ...
                suffix="BoundsShape", ...
                format="Param '%s' %s must match shape.", ...
                args={nameKey, which});
        end

    end
end
