classdef PhenotypeParameterSpecUtils
% PhenotypeParameterSpecUtils
% Internal helpers for extracting fields from a parameter spec struct.
%
% Errors:
%   - via helpers.Errors.raise only
%   - caller supplies classMeta and suffix

    methods (Static)
        function name = getName(spec, classMeta, suffix)
            if ~(isstruct(spec) && isscalar(spec))
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', "spec must be a scalar struct.");
            end

            if ~isfield(spec, "name")
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', "Spec is missing field 'name'.");
            end

            name = string(spec.name);
        end

        function kind = getKind(spec, classMeta, suffix)
            if ~(isstruct(spec) && isscalar(spec))
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', "spec must be a scalar struct.");
            end

            if ~isfield(spec, "kind")
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', "Spec is missing field 'kind'.");
            end

            kind = spec.kind;
        end

        function shape = getShape(spec, classMeta, suffix, name)
            if ~(isstruct(spec) && isscalar(spec))
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', "spec must be a scalar struct.");
            end

            if ~isfield(spec, "shape")
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', "Spec is missing field 'shape'.");
            end

            shape = spec.shape;

            ok = ~isempty(shape) && isnumeric(shape) && isreal(shape) && ...
                all(isfinite(shape(:))) && all(shape(:) >= 1) && ...
                all(shape(:) == floor(shape(:)));

            if ~ok
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'format', "Param '%s' has invalid shape.", ...
                    'args', {string(name)});
            end
        end

        function domain = getDomain(spec, classMeta, suffix, name)
            if ~(isstruct(spec) && isscalar(spec))
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', "spec must be a scalar struct.");
            end

            if ~isfield(spec, "domain")
                domain = struct();
                return
            end

            domain = spec.domain;

            if ~isstruct(domain)
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'format', "Param '%s' domain must be a struct.", ...
                    'args', {string(name)});
            end
        end
    end
end
