classdef ValidationUtils
% ValidationUtils
%
% Internal, stateless validation primitives shared across the toolbox.
%
% Purpose
%   ValidationUtils provides a collection of low-level, reusable validation
%   checks intended to be used by domain-specific validator classes
%   (e.g. MetagenomeValidator, PhenotypeParameterValidator, etc.).
%   The class centralizes generic validation logic so that domain
%   validators can express intent clearly without duplicating boilerplate
%   checks.
%
% Design principles
%   - Stateless and static:
%       All methods are static and side-effect free.
%
%   - Single error funnel:
%       All validation failures are reported exclusively via
%       helpers.Errors.raise. No direct calls to error(), assert(), or
%       argument-block validation are permitted.
%
% Intended usage
%   ValidationUtils hosts generic validation functions such as:
%     - scalar and matrix shape checks
%     - numeric finiteness and integrality checks
%     - range checks
%     - logical scalar checks
%     - mutual exclusivity checks
%     - predicate-based cell validation
%
% Conventions
%   - Method signature convention:
%       Each validation method follows the general pattern
%
%           validationTarget, classMeta, suffix, message
%
%       where:
%         * validationTarget
%             The value (or values) being validated.
%
%         * classMeta
%             A metaclass handle (e.g. ?MyValidator) identifying the
%             logical owner of the validation. This is used solely for
%             error identifier attribution and must not be inspected or
%             manipulated by the validator.
%
%         * suffix
%             A short, stable error suffix identifying the validation
%             failure. Suffixes are part of the public contract and are
%             asserted in unit tests.
%
%         * message
%             A human-readable diagnostic message. Messages are not part
%             of the contract and may change without affecting tests.
%
%       Additional parameters may appear before classMeta when required
%       by the specific check (e.g. bounds, expected sizes, predicates),
%       but the trailing (classMeta, suffix, message) convention is
%       preserved consistently.
%
%   - Error messages are treated as diagnostics only; unit tests assert
%     error identifiers, not messages.

    methods (Static)

        function mustBePositiveScalar(x, classMeta, suffix, msg)
            % mustBePositiveScalar
            % Require x to be a finite real scalar satisfying x > 0.
            
                epistemic.tools.evolutionary.internal.ValidationUtils. ...
                    mustBeFiniteScalar( ...
                    x, classMeta, suffix, msg);
            
                if ~(x > 0)
                    helpers.Errors.raise( ...
                        classMeta=classMeta, ...
                        suffix=string(suffix), ...
                        message=string(msg));
                end
            end

        function mustBeInClosedInterval( ...
                x, lo, hi, classMeta, suffix, msg)

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustHaveStrictOrder( ...
                lo, hi, classMeta, "BadBounds", ...
                "Require finite bounds with lo < hi.");

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBeFiniteNumeric( ...
                x, classMeta, "BadValue", ...
                "x must be finite and real.");

            if any(x(:) < lo | x(:) > hi)
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustBeInOpenInterval( ...
                x, lo, hi, classMeta, suffix, msg)

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustHaveStrictOrder( ...
                lo, hi, classMeta, "BadBounds", ...
                "Require finite bounds with lo < hi.");

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBeFiniteNumeric( ...
                x, classMeta, "BadValue", ...
                "x must be finite and real.");

            if any(x(:) <= lo | x(:) >= hi)
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end


        function mustHaveStrictOrder(lo, hi, classMeta, suffix, msg)
            % mustHaveStrictOrder
            % Require finite real scalar bounds satisfying lo < hi.
            
                epistemic.tools.evolutionary.internal.ValidationUtils. ...
                    mustBeFiniteScalar( ...
                    lo, classMeta, "BadLo", ...
                    "lo must be a finite real scalar.");
            
                epistemic.tools.evolutionary.internal.ValidationUtils. ...
                    mustBeFiniteScalar( ...
                    hi, classMeta, "BadHi", ...
                    "hi must be a finite real scalar.");
            
                if ~(lo < hi)
                    helpers.Errors.raise( ...
                        'classMeta', classMeta, ...
                        'suffix', string(suffix), ...
                        'message', string(msg));
                end
            end

        function mustContainKey( ...
                classMeta, map, key, suffix, format, args)
            arguments
                classMeta
                map
                key
                suffix (1,1) string
                format (1,1) string
                args cell = {key}
            end
    
            if ~isKey(map, key)
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix=suffix, ...
                    format=format, ...
                    args=args);
            end
        end

        function mustBeLogicalMatrix(x, classMeta, suffix, msg)
            ok = islogical(x) && ismatrix(x);
            if ~ok
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustBeNonnegativeFiniteScalar( ...
                x, classMeta, suffix, msg)

            ok = isnumeric(x) && isreal(x) && isscalar(x) && ...
                isfinite(x) && (x >= 0);

            if ~ok
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustHaveModulusInRange( ...
                x, lo, hi, classMeta, suffix, msg)

            okLo = isnumeric(lo) && isreal(lo) && isscalar(lo) && ...
                isfinite(lo);

            okHi = isnumeric(hi) && isreal(hi) && isscalar(hi) && ...
                isfinite(hi);

            if ~(okLo && okHi)
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', "BadRange", ...
                    'message', ...
                    "lo and hi must be finite real scalars.");
            end

            if lo < 0 || lo > hi
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', "BadRange", ...
                    'message', ...
                    "Expected 0 <= lo <= hi.");
            end

            if any(abs(x(:)) < lo | abs(x(:)) > hi)
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustBeFiniteComplexMatrix(x, classMeta, suffix, msg)
            ok = isnumeric(x) && ismatrix(x) && ...
                all(isfinite(real(x(:)))) && all(isfinite(imag(x(:))));
            if ~ok
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end
        
        function mustBeFiniteComplexScalar(x, classMeta, suffix, msg)
            ok = isnumeric(x) && isscalar(x) && ...
                isfinite(real(x)) && isfinite(imag(x));
            if ~ok
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustBeFiniteMatrix(x, classMeta, suffix, msg)
            % mustBeFiniteMatrix
            % Require x to be a finite, real, numeric matrix.
            
                ok = isnumeric(x) && isreal(x) && ismatrix(x) && ...
                        all(isfinite(x(:)));
                if ~ok
                    helpers.Errors.raise( ...
                        'classMeta', classMeta, ...
                        'suffix', string(suffix), ...
                        'message', string(msg));
                end
            end

        function mustBeNonEmptyStringScalar(x, classMeta, suffix, message)
        % mustBeNonEmptyStringScalar
        % Require x to be a string scalar with strlength(x) > 0.
        
            arguments
                x
                classMeta (1,1) meta.class
                suffix (1,1) string
                message (1,1) string
            end
        
            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBeStringScalar(x, classMeta, suffix, message);
        
            if strlength(x) == 0
                helpers.Errors.raise( ...
                    classMeta=classMeta, ...
                    suffix=suffix, ...
                    message=message);
            end
        end

        function mustBeIndexAtMost(idx, n, classMeta, suffix, format, args)
        % mustBeIndexAtMost
        % Funnel guard: require idx <= n.
        %
        % Notes:
        %   - Intended to be paired with 
        %       mustBePositiveIntegerScalar(idx,...)
        %   - "format" is a sprintf-style format string.
        %   - "args" is a cell array of sprintf arguments.

            if nargin < 6
                args = cell(1, 0);
            end

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBeMetaClass( ...
                    classMeta, ...
                    ?epistemic.tools.evolutionary.internal. ...
                    ValidationUtils, ...
                    "BadClassMeta", ...
                    "classMeta must be a scalar meta.class.");

            okN = isnumeric(n) && isreal(n) && isscalar(n) && ...
                isfinite(n) && (n == floor(n)) && (n >= 0);
            if ~okN
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', "BadN", ...
                    'message', "n must be a nonnegative integer scalar.");
            end

            okIdx = isnumeric(idx) && isreal(idx) && isscalar(idx) && ...
                isfinite(idx);
            if ~okIdx
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', "idx must be a finite real scalar.");
            end

            if idx > n
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'format', string(format), ...
                    'args', args);
            end
        end

        function mustBeIndexInRange(idx, n, classMeta, suffix)
        % mustBeIndexInRange
        % Require idx in 1..n (with n >= 0).

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBePositiveIntegerScalar( ...
                    idx, classMeta, suffix, ...
                    "idx must be a positive integer scalar.");

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBeIndexAtMost( ...
                    idx, n, classMeta, suffix, ...
                    "idx %d is out of range.", {idx});
        end

        function mustBeMetaClass(x, classMeta, suffix, msg)
        % mustBeMetaClass
        % Funnel-style check that x is a scalar meta.class.

            ok = isa(x, "meta.class") && isscalar(x);
            if ~ok
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustBeContainersMap(x, classMeta, suffix, msg)
        % mustBeContainersMap
        % Funnel-style check that x is a containers.Map handle.

            if ~isa(x, "containers.Map")
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustBeStringScalar(x, classMeta, suffix, message)
            if ~(isstring(x) && isscalar(x))
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(message));
            end
        end

        function mustBeRowVector(x, classMeta, suffix, message)
            ok = isnumeric(x) && isreal(x) && isvector(x) && isrow(x);
            if ~ok
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(message));
            end
        end

        function mustBeNonEmptyCell(x, classMeta, suffix, msg)
            if ~iscell(x) || isempty(x)
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustBeFiniteNumeric(x, classMeta, suffix, msg)
            ok = isnumeric(x) && isreal(x) && all(isfinite(x(:)));
            if ~ok
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustBeFiniteScalar(x, classMeta, suffix, msg)
            ok = isnumeric(x) && isreal(x) && isscalar(x) && isfinite(x);
            if ~ok
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustBeIntegerValued(x, classMeta, suffix, msg)
            ok = isnumeric(x) && isreal(x) && all(isfinite(x(:))) && ...
                all(x(:) == floor(x(:)));
            if ~ok
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustBeIntegerMatrix(x, classMeta, suffix, msg)
            if ~ismatrix(x)
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBeIntegerValued(x, classMeta, suffix, msg);
        end

        function mustBeIntegerScalar(x, classMeta, suffix, msg)
            ok = isnumeric(x) && isreal(x) && isscalar(x) && ...
                isfinite(x) && (x == floor(x));
            if ~ok
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustBeNonnegativeIntegerScalar(x, classMeta, suffix, msg)
            ok = isnumeric(x) && isreal(x) && isscalar(x) && ...
                isfinite(x) && (x == floor(x)) && (x >= 0);
            if ~ok
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustBePositiveIntegerScalar(x, classMeta, suffix, msg)
            ok = isnumeric(x) && isreal(x) && isscalar(x) && ...
                isfinite(x) && (x == floor(x)) && (x > 0);
            if ~ok
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustBeLogicalScalar(x, classMeta, suffix, msg)
            if ~(islogical(x) && isscalar(x))
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustBeMutuallyExclusive(a, b, classMeta, suffix, msg)
            if ~isempty(a) && ~isempty(b)
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustHaveSize(x, nRows, nCols, classMeta, suffix, msg)
            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBeNonnegativeIntegerScalar( ...
                    nRows, classMeta, "BadRows", ...
                    "nRows must be a nonnegative integer scalar.");

            epistemic.tools.evolutionary.internal.ValidationUtils. ...
                mustBeNonnegativeIntegerScalar( ...
                    nCols, classMeta, "BadCols", ...
                    "nCols must be a nonnegative integer scalar.");

            if ~ismatrix(x) || size(x, 1) ~= nRows || size(x, 2) ~= nCols
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustBeInRange(x, lo, hi, classMeta, suffix, msg)
            if any(x(:) < lo | x(:) > hi)
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', string(suffix), ...
                    'message', string(msg));
            end
        end

        function mustAllSatisfy(xs, predicateFn, classMeta, suffix, msg)
            if ~iscell(xs) || ~isrow(xs)
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', "BadInputs", ...
                    'message', "xs must be a 1-by-N cell.");
            end

            if ~isa(predicateFn, "function_handle") || ...
                    ~isscalar(predicateFn)
                helpers.Errors.raise( ...
                    'classMeta', classMeta, ...
                    'suffix', "BadInputs", ...
                    'message', "predicateFn must be a scalar handle.");
            end

            for k = 1:numel(xs)
                ok = predicateFn(xs{k});
                if ~islogical(ok) || ~isscalar(ok) || ~ok
                    helpers.Errors.raise( ...
                        'classMeta', classMeta, ...
                        'suffix', string(suffix), ...
                        'message', string(msg));
                end
            end
        end

    end
end
