classdef Decoders
% Decoders
%
% Minimal semantic dispatch for genotype → phenotype decoding.
%
% inferDecoder(args) returns:
%   decodeFcn(block, spec)

    methods (Static)

        function decodeFcn = inferDecoder(args)
            arguments
                args.sourceBlockType (1,1) string
                args.targetParameterType (1,1) ...
                    epistemic.tools.evolutionary.phenotype. ...
                    PhenotypeParameterKind
                args.options (1,1) struct = struct()
            end

            kind = args.targetParameterType;

            switch kind

                case epistemic.tools.evolutionary.phenotype. ...
                        PhenotypeParameterKind.Real
                    decodeFcn = epistemic.tools.evolutionary. ...
                        phenotype.decoders.RealDecoders.infer( ...
                        sourceBlockType=args.sourceBlockType, ...
                        options=args.options);

                case epistemic.tools.evolutionary.phenotype. ...
                        PhenotypeParameterKind.Int
                    decodeFcn = epistemic.tools.evolutionary. ...
                        phenotype.decoders.IntDecoders.infer( ...
                        sourceBlockType=args.sourceBlockType, ...
                        options=args.options);

                case epistemic.tools.evolutionary.phenotype. ...
                        PhenotypeParameterKind.Bool
                    decodeFcn = epistemic.tools.evolutionary. ...
                        phenotype.decoders.BoolDecoders.infer( ...
                        sourceBlockType=args.sourceBlockType);

                case epistemic.tools.evolutionary.phenotype. ...
                        PhenotypeParameterKind.Enum
                    decodeFcn = epistemic.tools.evolutionary. ...
                        phenotype.decoders.EnumDecoders.infer( ...
                        sourceBlockType=args.sourceBlockType);

                case epistemic.tools.evolutionary.phenotype. ...
                        PhenotypeParameterKind.Perm
                    decodeFcn = epistemic.tools.evolutionary. ...
                        phenotype.decoders.PermDecoders.infer( ...
                        sourceBlockType=args.sourceBlockType, ...
                        options=args.options);

                case epistemic.tools.evolutionary.phenotype. ...
                        PhenotypeParameterKind.Custom
                    helpers.Errors.raise( ...
                        classMeta=?Decoders, ...
                        suffix="CustomKindUnsupported", ...
                        message="Custom kind requires user decoder.");

                otherwise
                    helpers.Errors.raise( ...
                        classMeta=?Decoders, ...
                        suffix="UnsupportedKind", ...
                        format="Unsupported kind: %s.", ...
                        args={string(kind)});
            end
        end

    end
end